
export type UserRole = 'student';

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  avatar?: string;
}

// ---- Backend-aligned detection types ----

/** A single bounding box returned by the YOLO backend */
export interface BoundingBox {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  confidence: number;
  class_id: number;
  class_name: string;
  area_px: number;
  area_pct: number;
}

/** A spatial cluster of detections */
export interface SpatialCluster {
  cluster_id: number;
  centroid_x: number;
  centroid_y: number;
  member_count: number;
  dominant_class: string;
  avg_confidence: number;
  spread_px: number;
  density: number;
}

/** Colony Health Score —  0–100 composite metric */
export interface ColonyHealthScore {
  score: number;
  grade: 'Healthy' | 'Stressed' | 'Critical' | 'Collapse Risk';
  color: 'green' | 'yellow' | 'red';
  emoji: string;
  components: {
    threat_penalty: number;
    nesting_bonus: number;
    life_stage_bonus: number;
    colony_size: number;
  };
}

/** Raw response from POST /api/detect */
export interface DetectionResponse {
  success: boolean;
  message: string;
  original_image: string;
  annotated_image: string;
  detections: BoundingBox[];
  total_detections: number;
  summary?: WildlifeSummary;
  debug_info?: DebugInfo;
  spatial_clusters: SpatialCluster[];
  heatmap_image?: string | null;
  colony_health_score?: ColonyHealthScore | null;
}

/** Diagnostic metadata from the YOLO inference run */
export interface DebugInfo {
  raw_box_count: number;
  final_box_count: number;
  imgsz_used: number;
  conf_used: number;
  iou_used: number;
  model_name: string;
  image_width: number;
  image_height: number;
  image_mode: string;
  class_names: string[];
  inference_ms: number;
  sliced_inference: boolean;
  slice_grid: string;
  total_slices: number;
  merge_strategy: string;
  pre_nms_count: number;
  post_nms_count: number;
  tiny_object_count: number;
  spatial_clusters: number;
  model_type?: string;
  louisiana_mode?: boolean;
}

/** High-level wildlife summary (generated by backend from YOLO results) */
export interface WildlifeSummary {
  species: string;
  count: number;
  confidence: number;
  habitatType: string;
  nestingDetected: boolean;
  notes: string;
  threats: string[];
  conservation_priority: 'Standard' | 'Elevated' | 'Critical';
  recommended_actions: string[];
  colony_health_score?: ColonyHealthScore | null;
  life_stages?: Record<string, number> | null;
  colony_site?: string | null;
}

/** A stored detection record (persisted on backend) */
export interface DetectionRecord {
  id: string;
  species: string;
  count: number;
  confidence: number;
  habitatType: string;
  nestingDetected: boolean;
  notes: string;
  threats: string[];
  lat: number;
  lng: number;
  timestamp: string;
  imageUrl: string;
  annotatedImageUrl: string;
  boundingBoxes: BoundingBox[];
  conservation_priority: string;
  recommended_actions: string[];
  spatial_clusters: SpatialCluster[];
  colony_health_score?: ColonyHealthScore | null;
  life_stages?: Record<string, number> | null;
  colony_site?: string | null;
}

/** Kept for backward compat — alias to DetectionRecord */
export type DetectionResult = DetectionRecord;

export interface Alert {
  id: string;
  severity: 'Critical' | 'High' | 'Medium' | 'Low';
  category?: string;
  title: string;
  location: string;
  description: string;
  timestamp: string;
  action: string;
  species?: string;
  detectionId?: string;
  resolved?: boolean;
}

export interface OperationalRecommendation {
  threat_detected: string;
  trigger_condition: string;
  recommended_action: string;
  reasoning: string;
  priority_level: 'Low' | 'Medium' | 'High' | 'Critical';
  estimated_response_time: 'Immediate' | '24 hrs' | '3 days' | '1 week';
  responsible_agency: string;
  expected_impact: string;
  ai_driven: boolean;
}

export interface AlertNotifyResponse {
  success: boolean;
  sent_via: 'sendgrid' | 'mock';
  recipient: string;
  recipient_name: string;
  subject: string;
  timestamp: string;
  mock: boolean;
}

export interface DashboardStats {
  totalImages: number;
  totalDetections: number;
  nestsDetected: number;
  speciesCount: number;
  speciesList: string[];
  landLossAlerts: number;
  avgColonyHealth?: number | null;
  criticalSites?: number | null;
}

/** Colony health data per monitoring site */
export interface ColonySiteHealth {
  name: string;
  lat: number;
  lng: number;
  habitat: string;
  species: string[];
  health_score: number | null;
  health_grade: string;
  survey_count: number;
  nest_events: number;
  last_survey: string | null;
  top_threats: { threat: string; count: number }[];
}

/** Species population trend data */
export interface PopulationTrend {
  date: string;
  count: number;
  confidence: number;
  health_score: number | null;
  nesting: boolean;
  site: string | null;
}

/** Model transparency card */
export interface ModelCard {
  model_name: string;
  model_architecture: string;
  base_model: string;
  version: string;
  last_updated: string;
  total_classes: number;
  class_categories: Record<string, number>;
  overall_f1: number;
  overall_map50: number;
  training_images: number;
  validation_images: number;
  label_strategy: string;
  dataset_sources: DatasetSource[];
  class_performance: ClassPerformance[];
  known_limitations: string[];
  deployment_notes: string;
  geographic_scope: string;
}

export interface DatasetSource {
  name: string;
  type: string;
  source_url: string;
  license: string;
  image_count: number;
  classes_covered: string[];
  geographic_region: string;
  date_range: string;
  annotation_method: string;
}

export interface ClassPerformance {
  name: string;
  precision: number;
  recall: number;
  f1: number;
  train_images: number;
}

/** Backend auth response from /api/auth/login */
export interface AuthResponse {
  success: boolean;
  message: string;
  access_token: string;
  refresh_token: string;
  user: {
    id: string;
    email: string;
    full_name: string;
  };
}
