
export type UserRole = 'student';

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  avatar?: string;
}

// ---- Backend-aligned detection types ----

/** A single bounding box returned by the YOLO backend */
export interface BoundingBox {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  confidence: number;
  class_id: number;
  class_name: string;
}

/** Raw response from POST /api/detect */
export interface DetectionResponse {
  success: boolean;
  message: string;
  original_image: string;   // e.g. "/static/uploads/abc.jpg"
  annotated_image: string;  // e.g. "/static/results/annotated_abc.jpg"
  detections: BoundingBox[];
  total_detections: number;
  // Extended fields from enriched backend
  summary?: WildlifeSummary;
}

/** High-level wildlife summary (generated by backend from YOLO results) */
export interface WildlifeSummary {
  species: string;
  count: number;
  confidence: number;
  habitatType: 'Marsh' | 'Barrier Island' | 'Swamp' | 'Open Water';
  nestingDetected: boolean;
  notes: string;
  threats: string[];
}

/** A stored detection record (persisted on backend) */
export interface DetectionRecord {
  id: string;
  species: string;
  count: number;
  confidence: number;
  habitatType: 'Marsh' | 'Barrier Island' | 'Swamp' | 'Open Water';
  nestingDetected: boolean;
  notes: string;
  threats: string[];
  lat: number;
  lng: number;
  timestamp: string;
  imageUrl: string;          // URL to original image
  annotatedImageUrl: string; // URL to annotated image
  boundingBoxes: BoundingBox[];
}

/** Kept for backward compat — alias to DetectionRecord */
export type DetectionResult = DetectionRecord;

export interface Alert {
  id: string;
  severity: 'High' | 'Medium' | 'Low';
  title: string;
  location: string;
  description: string;
  timestamp: string;
  action: string;
}

export interface DashboardStats {
  totalImages: number;
  totalDetections: number;
  nestsDetected: number;
  speciesCount: number;
  speciesList: string[];
  landLossAlerts: number;
}

/** Backend auth response from /api/auth/login */
export interface AuthResponse {
  success: boolean;
  message: string;
  access_token: string;
  refresh_token: string;
  user: {
    id: string;
    email: string;
    full_name: string;
  };
}
