
export type UserRole = 'student';

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  avatar?: string;
}

// ---- Backend-aligned detection types ----

/** A single bounding box returned by the YOLO backend */
export interface BoundingBox {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  confidence: number;
  class_id: number;
  class_name: string;
  area_px: number;
  area_pct: number;
}

/** A spatial cluster of detections */
export interface SpatialCluster {
  cluster_id: number;
  centroid_x: number;
  centroid_y: number;
  member_count: number;
  dominant_class: string;
  avg_confidence: number;
  spread_px: number;
  density: number;
}

/** Raw response from POST /api/detect */
export interface DetectionResponse {
  success: boolean;
  message: string;
  original_image: string;
  annotated_image: string;
  detections: BoundingBox[];
  total_detections: number;
  summary?: WildlifeSummary;
  debug_info?: DebugInfo;
  spatial_clusters: SpatialCluster[];
  heatmap_image?: string | null;
}

/** Diagnostic metadata from the YOLO inference run */
export interface DebugInfo {
  raw_box_count: number;
  final_box_count: number;
  imgsz_used: number;
  conf_used: number;
  iou_used: number;
  model_name: string;
  image_width: number;
  image_height: number;
  image_mode: string;
  class_names: string[];
  // Advanced pipeline info
  inference_ms: number;
  sliced_inference: boolean;
  slice_grid: string;
  total_slices: number;
  merge_strategy: string;
  pre_nms_count: number;
  post_nms_count: number;
  tiny_object_count: number;
  spatial_clusters: number;
}

/** High-level wildlife summary (generated by backend from YOLO results) */
export interface WildlifeSummary {
  species: string;
  count: number;
  confidence: number;
  habitatType: 'Marsh' | 'Barrier Island' | 'Swamp' | 'Open Water';
  nestingDetected: boolean;
  notes: string;
  threats: string[];
  conservation_priority: 'Standard' | 'Elevated' | 'Critical';
  recommended_actions: string[];
}

/** A stored detection record (persisted on backend) */
export interface DetectionRecord {
  id: string;
  species: string;
  count: number;
  confidence: number;
  habitatType: 'Marsh' | 'Barrier Island' | 'Swamp' | 'Open Water';
  nestingDetected: boolean;
  notes: string;
  threats: string[];
  lat: number;
  lng: number;
  timestamp: string;
  imageUrl: string;
  annotatedImageUrl: string;
  boundingBoxes: BoundingBox[];
  conservation_priority: string;
  recommended_actions: string[];
  spatial_clusters: SpatialCluster[];
}

/** Kept for backward compat — alias to DetectionRecord */
export type DetectionResult = DetectionRecord;

export interface Alert {
  id: string;
  severity: 'High' | 'Medium' | 'Low';
  title: string;
  location: string;
  description: string;
  timestamp: string;
  action: string;
}

export interface DashboardStats {
  totalImages: number;
  totalDetections: number;
  nestsDetected: number;
  speciesCount: number;
  speciesList: string[];
  landLossAlerts: number;
}

/** Backend auth response from /api/auth/login */
export interface AuthResponse {
  success: boolean;
  message: string;
  access_token: string;
  refresh_token: string;
  user: {
    id: string;
    email: string;
    full_name: string;
  };
}
