(function(g){var window=this;'use strict';var UQ=function(M){M.publish("cardstatechange",M.Xp()&&M.Uk()?1:0)},CC=function(M,W){var b=g.mL(W);
const T=b?W:arguments;for(b=b?0:1;b<T.length;b++){if(M==null)return;M=M[T[b]]}return M},$PV=function(M){const W=g.de(M);
M=g.we(M);return new g.re(W.x,W.y,M.width,M.height)},MUE=function(M,W,b){let T;
return T=g.o$(M,W,function(){g.cV(T);b.apply(M,arguments)},{})},vU=function(M){M=g.Zl(M);
delete k6[M];g.P$(k6)&&KC&&KC.stop()},brc=function(){KC||(KC=new g.d9(function(){WRI()},20));
const M=KC;M.isActive()||M.start()},WRI=function(){var M=g.Hy();
g.NE(k6,function(W){Te4(W,M)});
g.P$(k6)||brc()},mN=function(M,W,b,T){g.TH.call(this);
if(!Array.isArray(M)||!Array.isArray(W))throw Error("Start and end parameters must be arrays");if(M.length!=W.length)throw Error("Start and end points must be the same length");this.V=M;this.W=W;this.duration=b;this.S=T;this.coords=[];this.progress=this.C=0;this.A=null},Te4=function(M,W){W<M.startTime&&(M.endTime=W+M.endTime-M.startTime,M.startTime=W);
M.progress=(W-M.startTime)/(M.endTime-M.startTime);M.progress>1&&(M.progress=1);M.C=1E3/(W-M.A);M.A=W;qSr(M,M.progress);M.progress==1?(M.Z=0,vU(M),M.onFinish(),M.pD()):M.isPlaying()&&M.W5()},qSr=function(M,W){typeof M.S==="function"&&(W=M.S(W));
M.coords=Array(M.V.length);for(let b=0;b<M.V.length;b++)M.coords[b]=(M.W[b]-M.V[b])*W+M.V[b]},X59=function(M,W){g.wi.call(this,M);
this.coords=W.coords;this.x=W.coords[0];this.y=W.coords[1];this.z=W.coords[2];this.duration=W.duration;this.progress=W.progress;this.fps=W.C;this.state=W.Z},LC=function(M,W,b,T,q){mN.call(this,W,b,T,q);
this.element=M},ld=function(M,W,b,T,q){if(W.length!=2||b.length!=2)throw Error("Start and end points must be 2D");
LC.call(this,M,W,b,T,q)},j5E=function(M){return Math.pow(M,3)},GrB=function(M){return 3*M*M-2*M*M*M},tn=function(M){return M.baseUrl||null},Z8=function(M,W){return g.et(g.dG(M,W),b=>!!b)},VUA=function(M,W,b){function T(Lt){var St=Lt.hovercardButton;
if(!St)return null;St=St.subscribeButtonRenderer;if(!St)return null;const oJ=X(St.unsubscribedButtonText),NR=X(St.subscribedButtonText);let Oq,Ly;St.subscribed?(Oq=X(St.subscriberCountWithUnsubscribeText),Ly=X(St.subscriberCountText)):(Oq=X(St.subscriberCountText),Ly=X(St.subscriberCountWithSubscribeText));let eu=null;return Lt.signinEndpoint&&((eu=CC(Lt,"signinEndpoint","webNavigationEndpointData","url"))||(eu=g.z(St.signInEndpoint?.commandMetadata,g.vL)?.url),!eu)?null:oJ&&(NR||eu)?{subscribed:St.subscribed,
subscribeText:oJ,subscribeCount:Oq,unsubscribeText:NR,unsubscribeCount:Ly,enabled:St.enabled,signinUrl:eu,classic:Lt.useClassicSubscribeButton}:null}
function q(Lt){if(Lt){var St=[],oJ=Lt.videoId;oJ&&St.push("v="+oJ);(oJ=Lt.playlistId)&&St.push("list="+oJ);(Lt=Lt.startTimeSeconds)&&St.push("t="+Lt);return"/watch?"+St.join("&")}}
function X(Lt){if(!Lt)return null;const St=Lt.simpleText;return St?St:Lt.runs?g.dG(Lt.runs,oJ=>oJ.text).join(""):null}
W=W.endscreenElementRenderer;if(!W)return null;const G=W.style,V=W.endpoint||{};let J=null;var B=null,D=!1;let a=null,E=null,n=null,C=null;var l=!1;let N=null,R=null;var f=null;let x=null,A=null,qa=null;if(G==="VIDEO")g.z(V,g.HF)?J=g.z(V,g.HF).url:(qa=g.z(V,g.Jj),J=q(qa)),B=!1,a=M,W.thumbnailOverlays?(D=W.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,E=X(D.text),D=D.style==="LIVE"):E=X(W.videoDuration);else if(G==="PLAYLIST")g.z(V,g.HF)?J=g.z(V,g.HF).url:(qa=g.z(V,g.Jj),J=q(qa)),B=!1,a=
M,n=X(W.playlistLength);else if(G==="CHANNEL"){if(l=CC(V,"browseEndpoint","browseId"))C=l,J=`/channel/${C}`;B=!1;a="new";(l=!!W.isSubscribe)?N=T(W):R=X(W.subscribersText)}else G==="WEBSITE"?((f=CC(V,"urlEndpoint","url"))&&(J=f),B=!0,a="new",f=W.icon.thumbnails[0].url):G==="CREATOR_MERCHANDISE"&&(W.productPrice&&(x=X(W.productPrice)),W.additionalFeesText&&(A=X(W.additionalFeesText)),(B=CC(V,"urlEndpoint","url"))&&(J=B),B=!0,a="new");M=CC(W,"title","accessibility","accessibilityData","label");const Xs=
W.endpoint?W.endpoint.clickTrackingParams:null;let uQ="";if(W.metadata){const Lt=X(W.metadata);Lt&&(uQ=Lt)}return{id:`element-${b}`,type:G,title:X(W.title),metadata:uQ,callToAction:X(W.callToAction),qr:W.image,iconUrl:f,left:Number(W.left),width:Number(W.width),top:Number(W.top),aspectRatio:Number(W.aspectRatio),startMs:Math.floor(Number(W.startMs)),endMs:Math.floor(Number(W.endMs)),videoDuration:E,SC:D,playlistLength:n,channelId:C,subscribeButton:N,subscribersText:R,isSubscribe:l,targetUrl:J||null,
j8:B,sessionData:Xs?{itct:Xs}:null,IW:a,Dq:M?M:null,isPlaceholder:W.isPlaceholder,impressionUrls:Z8(W.impressionUrls||[],tn),Bm:Z8(W.hovercardShowUrls||[],tn),clickUrls:Z8(V.loggingUrls||[],tn),visualElement:g.BW(W.trackingParams),productPrice:x,additionalFeesText:A,watchEndpoint:qa||null}},IM=function(M,W){const b={startMs:Math.floor(Number(M.startMs)),
impressionUrls:Z8(M.impressionUrls||[],tn),elements:Z8(M.elements||[],(T,q)=>VUA(W,T,q))};
M.trackingParams&&(b.visualElement=g.BW(M.trackingParams));return b},N7=function(M){return M.player.G().playerStyle==="creator-endscreen-editor"},JWE=function(M){return M.player.getVideoData().uN?"current":M.X?"new":"current"},HU=function(M,W,b=!0){M.player.lN("creatorendscreen");
M.B&&(M.B.dispose(),M.B=null,M.S.dispose(),M.S=null);for(var T of Object.values(M.V))T.dispose();M.V={};M.C={};M.D.length>0&&(M.D.forEach(q=>{q.dispose()}),M.D.length=0);
M.Z&&(g.Mw(M.Z,"ytp-ce-element-show"),M.Z.setAttribute("aria-hidden","true"));M.W=0;if((M.endscreen=W)&&W.elements){b&&BeA(M);b=[];T=new g.Ap(W.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});b.push(T);M.player.G().V||(M.B=new g.w({K:"div",N:"ytp-ce-shadow"}),g.Im(M.player,M.B.element,4),M.S=new g.Ol(M.B,200));for(T=0;T<W.elements.length;++T){const q=W.elements[T],X=DPB(M,q);if(!X){g.lR(new g.EF("buildEndscreenElement null",q));continue}M.V[q.id]=X;M.C[q.id]=q;g.Im(M.player,
X.element,4);const G=new g.Ap(q.startMs,q.endMs,{id:"ytp-ce-element-"+q.id,namespace:"creatorendscreen"});b.push(G);a3r(M,X,q)}M.player.QV(b);M.XT()}},Eth=function(M){var W=M.player.getVideoData(),b=W.videoId;
M.A&&M.A.abort();b={method:"POST",onFinish:q=>{var X=M.A=null;q.status===200&&(q=q.responseText,q.substring(0,3)===")]}"&&(q=q.substring(3),X=JSON.parse(q),X=IM(X,JWE(M))));HU(M,X)},
urlParams:{v:b},withCredentials:!0};M.X&&(b.urlParams.ptype="embedded");const T=W.NI;T&&(b.postParams={ad_tracking:T});if(W=g.q5l(W))if(W=g.zp(W),W=g.Fh(W))M.A=g.Pe(W,b)},BeA=function(M){const W=g.EB(),b=g.nT();
b&&W&&M.endscreen.visualElement&&g.Je(g.PW)(void 0,b,W,M.endscreen.visualElement)},DPB=function(M,W){var b=null;
switch(W.type){case "VIDEO":M={K:"div",rK:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":W.Dq||"","aria-hidden":"true"},U:[{K:"div",N:"ytp-ce-element-shadow"},{K:"div",N:"ytp-ce-covering-image",Y:fC(W)},{K:"div",N:"ytp-ce-covering-shadow-top"},{K:"a",N:"ytp-ce-covering-overlay",Y:{href:RM(M,W.targetUrl),tabindex:"-1"},U:[{K:"div",rK:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.Dj(W.title||"")},R0:W.title},{K:"div",N:W.SC?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
R0:W.videoDuration||void 0}]}]};b=new g.w(M);break;case "PLAYLIST":M={K:"div",rK:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":W.Dq||"","aria-hidden":"true"},U:[{K:"div",N:"ytp-ce-element-shadow"},{K:"div",N:"ytp-ce-covering-image",Y:fC(W)},{K:"div",N:"ytp-ce-covering-shadow-top"},{K:"a",N:"ytp-ce-covering-overlay",Y:{href:RM(M,W.targetUrl),tabindex:"-1"},U:[{K:"div",rK:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.Dj(W.title||"")},R0:W.title},{K:"div",N:"ytp-ce-playlist-count",
U:[{K:"div",N:"ytp-ce-playlist-icon"},{K:"div",N:"ytp-ce-playlist-count-text",R0:W.playlistLength||void 0}]}]}]};b=new g.w(M);break;case "CHANNEL":b={K:"div",rK:["ytp-ce-element","ytp-ce-channel",W.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":W.Dq||"","aria-hidden":"true"},U:[{K:"div",N:"ytp-ce-element-shadow"},{K:"div",N:"ytp-ce-expanding-overlay",U:[{K:"div",N:"ytp-ce-expanding-overlay-hider"},{K:"div",N:"ytp-ce-expanding-overlay-background"},{K:"div",N:"ytp-ce-expanding-overlay-content",
U:[{K:"div",N:"ytp-ce-expanding-overlay-body",U:[{K:"div",N:"ytp-ce-expanding-overlay-body-padding",U:[{K:"a",rK:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:RM(M,W.targetUrl),target:"_blank",tabindex:"-1",dir:g.Dj(W.title||"")},R0:W.title},W.subscribeButton?{K:"div",N:"ytp-ce-subscribe-container",U:[{K:"div",N:"ytp-ce-channel-subscribe"}]}:"",W.subscribersText?{K:"div",N:"ytp-ce-channel-subscribers-text",R0:W.subscribersText}:"",W.metadata?{K:"div",rK:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],R0:W.metadata}:""]}]}]}]},{K:"div",N:"ytp-ce-expanding-image",Y:fC(W)}]};b=new g.w(b);const q=g.sa(document,"div","ytp-ce-channel-subscribe",b.element)[0];if(W.subscribeButton&&W.channelId){g.pY(q,"ytp-ce-subscribe-button");let X;if(M.player.G().V){var T=null;X=W.sessionData.itct}else T="endscreen",X=null;T=new g.nA(W.subscribeButton.subscribeText,W.subscribeButton.subscribeCount,W.subscribeButton.unsubscribeText,W.subscribeButton.unsubscribeCount,!!W.subscribeButton.enabled,!!W.subscribeButton.classic,
W.channelId,!!W.subscribeButton.subscribed,T,X,M.player,!1);q.appendChild(T.element);M.D.push(T)}break;case "WEBSITE":M={K:"div",rK:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":W.Dq||"","aria-hidden":"true"},U:[{K:"div",N:"ytp-ce-element-shadow"},{K:"div",N:"ytp-ce-expanding-overlay",U:[{K:"div",N:"ytp-ce-expanding-overlay-hider"},{K:"div",N:"ytp-ce-expanding-overlay-background"},{K:"div",N:"ytp-ce-expanding-overlay-content",U:[{K:"div",N:"ytp-ce-expanding-overlay-body",U:[{K:"div",
N:"ytp-ce-expanding-overlay-body-padding",U:[{K:"div",N:"ytp-ce-website-title",Y:{dir:g.Dj(W.title||"")},R0:W.title},{K:"div",N:"ytp-ce-website-metadata",R0:W.metadata},{K:"a",rK:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:RM(M,W.targetUrl),target:"_blank",tabindex:"-1"},R0:W.callToAction}]}]}]}]},{K:"div",N:"ytp-ce-expanding-image",Y:fC(W)},{K:"div",N:"ytp-ce-expanding-icon",Y:nt5(W.iconUrl)}]};b=new g.w(M);break;case "CREATOR_MERCHANDISE":b="",W.productPrice&&(b={K:"div",N:"ytp-ce-merchandise-price-container",
U:[{K:"div",N:"ytp-ce-merchandise-price",R0:W.productPrice}]},W.additionalFeesText&&b.U.push({K:"div",N:"ytp-ce-merchandise-additional-fees",R0:W.additionalFeesText})),M={K:"div",rK:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":W.Dq||"","aria-hidden":"true"},U:[{K:"div",N:"ytp-ce-element-shadow"},{K:"div",N:"ytp-ce-expanding-overlay",U:[{K:"div",N:"ytp-ce-expanding-overlay-hider"},{K:"div",N:"ytp-ce-expanding-overlay-background"},{K:"div",N:"ytp-ce-expanding-overlay-content",
U:[{K:"div",N:"ytp-ce-expanding-overlay-body",U:[{K:"div",N:"ytp-ce-expanding-overlay-body-padding",U:[{K:"div",N:"ytp-ce-merchandise-title",Y:{dir:g.Dj(W.title||"")},R0:W.title},b,{K:"div",N:"ytp-ce-merchandise-metadata",R0:W.metadata},{K:"a",rK:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:RM(M,W.targetUrl),target:"_blank",tabindex:"-1"},R0:W.callToAction}]}]}]}]},{K:"div",N:"ytp-ce-expanding-image",Y:fC(W)},{K:"div",N:"ytp-ce-merchandise-invideo-cta-container",U:[{K:"div",N:"ytp-ce-merchandise-invideo-cta",
R0:W.callToAction||void 0}]}]},b=new g.w(M)}W.isPlaceholder&&g.pY(b.element,"ytp-ce-placeholder");return b},a3r=function(M,W,b){function T(){G(1)}
function q(){G(-1)}
W.listen("mouseenter",()=>{rT(M,W,b)});
W.listen("mouseleave",()=>{x6(M,W,b)});
M.player.G().V||W.listen("click",()=>{g.pY(W.element,"ytp-ce-element-hover")});
W.listen("click",V=>{yWc(M,b,V)});
W.listen("keypress",V=>{yWc(M,b,V)});
W.listen("focus",()=>{rT(M,W,b)});
W.listen("blur",()=>{x6(M,W,b)});
W.listen("touchstart",()=>{rT(M,W,b)});
var X=g.wP("ytp-ce-expanding-overlay-hider",W.element);X&&W.J(X,"touchstart",V=>{V.stopPropagation();g.Mw(W.element,"ytp-ce-element-hover");g.Mw(W.element,"ytp-ce-force-expand")});
W.listen("keydown",V=>{M.gK=V.keyCode===9&&!V.shiftKey});
const G=V=>{M.W+=V;M.W>0?(g.pY(W.element,"ytp-ce-force-expand"),FF(M,b.id,!0)):(g.Mw(W.element,"ytp-ce-force-expand"),g.Mw(W.element,"ytp-ce-element-hover"),FF(M,b.id,!1))};
X=V=>{V&&(W.listen("blur",()=>{V.style.display!="none"&&M.gK&&V.focus()}),W.J(V,"focus",T),W.J(V,"blur",q))};
X(g.wP("ytp-sb-subscribe",W.element));X(g.wP("ytp-sb-unsubscribe",W.element));W.listen("focus",T);W.listen("blur",q)},id=function(M,W,b){function T(){X||(q++,q===W.length&&(G.stop(),b&&b()))}
if(!W||W.length===0||N7(M))b&&b();else{W=UP$(M,W);var q=0,X=!1,G=new g.d9(()=>{X=!0;b&&b()},1E3,M);
G.start();for(M=0;M<W.length;M++)g.zu(W[M],T)}},fC=function(M){let W;
M.qr&&(W=M.qr.thumbnails);return nt5(W?W[W.length-1].url:null)},RM=function(M,W){M=M.player.G();
if(W){if(W.startsWith("//"))return M.protocol+":"+W;if(W.startsWith("/"))return g.lb(M)+W}else return"";return W},nt5=function(M){return M?{style:"background-image: url("+M+")"}:{}},rT=function(M,W,b){g.w9(W.element,"ytp-ce-element-hover")||(b.type==="VIDEO"||b.type==="PLAYLIST"?g.pY(W.element,"ytp-ce-element-hover"):M.player.G().V?(new g.d9(()=>{g.pY(W.element,"ytp-ce-element-hover")},200)).start():g.pY(W.element,"ytp-ce-element-hover"),id(M,b.Bm),FF(M,b.id,!0))},x6=function(M,W,b){g.Mw(W.element,
"ytp-ce-element-hover");
g.Mw(W.element,"ytp-ce-force-expand");FF(M,b.id,!1)},yWc=function(M,W,b){if(W.targetUrl&&(!b||b.type!=="keypress"||b.keyCode===13)){for(var T=b.target;T&&!g.w9(T,"ytp-ce-element");){g.w9(T,"subscribe-label")&&hn(M,W);
if(g.w9(T,"ytp-ce-channel-subscribe"))return;T=T.parentElement||null}if(!T||g.w9(T,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(T=M.V[W.id])x6(M,T,W),T.element.blur();if(b.ctrlKey||b.metaKey||W.IW==="new")hn(M,W),M.player.sendVideoStatsEngageEvent(17,void 0),M.player.pauseVideo(),b=g.zp(RM(M,W.targetUrl)),b=g.Fh(b),g.pu(b,void 0,W.sessionData);else{const q=g.Zk(M.player.G())||M.player.getVideoData().uN,X=()=>{var G=RM(M,W.targetUrl),V=W.sessionData,J=W.watchEndpoint;const B=
g.UX(G);q&&B&&(B.v||B.list)?M.player.jA(B.v,V,B.list,!1,void 0,J||void 0):g.wB(G,V)};
hn(M,W,()=>{M.player.sendVideoStatsEngageEvent(17,X)})}}}},FF=function(M,W,b){M.B&&(b?M.S.show():M.S.hide());
for(const T of Object.keys(M.V))T!==W&&g.H(M.V[T].element,"ytp-ce-element-shadow-show",b)},hn=function(M,W,b){id(M,W.clickUrls,b);
(M=g.nT())&&W.j8&&g.$X(M,W.visualElement)},UP$=function(M,W){var b=M.player.getVideoData().clientPlaybackNonce;
M=M.player.getCurrentTime().toFixed(2);b={CPN:b,AD_CPN:b,MT:M};M=[];for(let T=0;T<W.length;T++)M.push(Cq9(W[T],b));return M},Cq9=function(M,W){return M.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,b=>{let T=unescape(b);
T=T.substring(1,T.length-1);return W[T]?escape(W[T]):b})},kr$=function(M){return typeof M==="string"?M:""},An=function(M,W,b){for(const T in W)if(W[T]===M)return M;
return b},zf=function(M){if(!M)return null;
var W=g.zp(kr$(M.value));W=g.Fh(W);if(!W)return null;const b=An(M.target,KRQ,"current");if(b==null)M=null;else{var T=M.show_link_icon;M=new vtQ(W,b,T==="true"||T==="false"?T==="true":!0,M.pause_on_navigation!=null?M.pause_on_navigation:!0)}return M},tU9=function(M){if(!M)return null;
const W=An(M.type,mP5),b=An(M.trigger,LR5);M=M.url;M=Array.isArray(M)&&M.length?M[0]:M;M=zf(M?M:null);return W?new l35(W,b,M):null},ZrA=function(M,W){return g.pt(M.action,W)},ud=function(M,W){M="background-image: url("+M+");";
const b=[];W&&b.push(W);return{K:"div",N:"iv-card-image",Y:{style:M},U:b}},OQ=function(M){return M.customMessage?Sd("div","iv-card-message",M.customMessage):""},PU=function(M){if(!M.metaInfo||M.metaInfo.length===0)return"";
const W=[];for(const b of M.metaInfo)W.push(Sd("li","",b));return{K:"ul",N:"iv-card-meta-info",U:W}},ed=function(M,W,b,T){if(T)for(const q of W)M.Z(q,T,b.id,b.sessionData,b.RZ.click,5)},Sd=function(M,W,b){W?typeof W==="string"?W={"class":W}:Array.isArray(W)&&(W={"class":W.join(" ")}):W={};
W.dir=g.Dj(b);return{K:M,Y:W,R0:b}},I3V=function(M){if(!M.customMessage)return"";
const W=["iv-card-action","iv-card-primary-link"],b={};M.Qg&&(W.push("iv-card-action-icon"),b.style="background-image: url("+M.Qg+");");b.dir=g.Dj(M.customMessage);const T=[{K:"span",R0:M.customMessage}];M.showLinkIcon&&(T.push("\u00a0"),T.push({K:"span",N:"iv-card-link-icon"}));return{K:"div",rK:W,Y:b,U:T}},Ne5=function(M){var W;
(W=M)&&!(W=M.length>1?M.charAt(0)==="/"&&M.charAt(1)!=="/":M==="/")&&(W=M.replace(/^(https?:)?\/\//,"").split("/",1),W=!W||W.length<1||!W[0]?[]:W[0].toLowerCase().split(".").reverse(),W=W[0]==="com"&&W[1]==="youtube"||W[0]==="be"&&W[1]==="youtu");return W?M.indexOf("/redirect?")===-1:!1},Hrh=function(M,W){return W?W:Ne5(M)?"current":"new"},dT=function(M,W,b,T,q,X,G){M.context.Z.listen(W,"click",V=>{M.jT(b,T,q,X||[],G||0,V)});
M.context.Z.listen(W,"touchstart",()=>{M.XX=!1});
M.context.Z.listen(W,"touchmove",()=>{M.XX=!0})},f3r=function(M){if(g.z(M,g.HF)?.url)return g.z(M,g.HF).url;
if((M=g.z(M,g.Jj))&&M.videoId){let W="/watch?v="+M.videoId;M.playlistId&&(W+="&list="+M.playlistId);M.index&&(W+="&index="+M.index);M.startTimeSeconds&&(W+="&t="+M.startTimeSeconds);return W}return null},oM=function(M,W,b){return{c9:(M.impressionLoggingUrlsV2s||[]).map(T=>T.baseUrl||""),
click:(b.loggingUrls||[]).map(T=>T.baseUrl||""),
close:(W.dismissLoggingUrlsV2s||[]).map(T=>T.baseUrl||""),
Mb:(W.impressionLoggingUrlsV2s||[]).map(T=>T.baseUrl||""),
au:(W.clickLoggingUrlsV2s||[]).map(T=>T.baseUrl||"")}},sQ=function(M,W){if(W.onClickCommand&&g.z(W.onClickCommand,g.x7t)?.targetId==="engagement-panel-error-corrections"){M.O=W;
var b=!0}else b=!1;if(!b||RB4(M,W))if(b=rWA(M,W)){var T={Ma:W,cA:b.element,tK:!1};if(W.onClickCommand)M.L.j("web_infocards_teaser_show_logging_fix")&&(M.vP||FRE(M),cU(M,W.id),b=M.findLastIndex(T),g.nJ(M.cards,b,0,T));else{M.isInitialized||xP5(M);cU(M,W.id);const q=M.findLastIndex(T);g.nJ(M.cards,q,0,T);b.cY(M.V,q);M.BY()}W.autoOpen?M.addCueRange(W.startMs,0x8000000000000,W.id,()=>{M.B||(M.Z=T,Qu(M),irp(M,T),gT(M,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(b=M.context.L.getCurrentTime()*1E3,b<5E3&&b>W.startMs&&
hBA(M,T),M.addCueRange(W.startMs,W.startMs+1,W.id,()=>{hBA(M,T)}),Qu(M))}},wT=function(M){M.B&&(M.EY.hide(),M.MK.V(),g.Mw(M.context.L.getRootNode(),g.Vg.IV_DRAWER_OPEN),M.B=!1,UQ(M.L),M.C&&M.C.stop(),M.C=new g.d9(()=>{M.An&&(M.An.focus(),M.An=null)},330),M.C.start())},AW9=function(M,W){W=W.data;
W.autoOpenMs&&M.addCueRange(W.autoOpenMs,0x8000000000000,"",()=>{gT(M,"YOUTUBE_DRAWER_AUTO_OPEN")});
W.autoCloseMs&&M.addCueRange(W.autoCloseMs,0x8000000000000,"",()=>{wT(M)});
const b=W.headerText;g.nr(M.d9,b);M.S&&(M.L.j("player_tooltip_data_title_killswitch")?M.S.setAttribute("title",b):M.S.setAttribute("data-tooltip-title",b));W.eventId&&(M.eventId=W.eventId);M.lV=g.BW(W.trackingParams);M.D=g.BW(W.closeTrackingParams);M.J_=g.BW(W.iconTrackingParams)},pC=function(M,W,b){let T=-1,q=-1;
for(let X=0;X<M.length;X++){if(M[X].height===W||M[X].width===b)return M[X];((M[X].height||0)<W||(M[X].width||0)<b)&&(T<0||(M[T].height||0)<(M[X].height||0)||(M[T].width||0)<(M[X].width||0))?T=X:((M[X].height||0)>=W||(M[X].width||0)>=b)&&(q<0||(M[q].height||0)>(M[X].height||0)||(M[q].width||0)>(M[X].width||0))&&(q=X)}return M[q>=0?q:T]},Y6=function(M,W,b,T){return{feature:b.feature?b.feature:"cards",
src_vid:M.context.videoData.videoId,annotation_id:W,ei:M.context.videoData.eventId||"",itct:T.trackingParams||""}},zBJ=function(M,W){const b=W.cardId?W.cardId:`cr:${M.W}`;
var T=M.L.G().experiments.FX("enable_error_corrections_infocard_web_client");if(!W.content&&W.teaser.simpleCardTeaserRenderer&&T){T=W.teaser.simpleCardTeaserRenderer;var q=W.icon?W.icon.infoCardIconRenderer:null;if(T.channelAvatar&&T.channelAvatar.thumbnails&&T.channelAvatar.thumbnails.length>0)var X=pC(T.channelAvatar.thumbnails,22,22).url;W={id:b,timestamp:M.W,type:"simple",teaserText:g.Ga(T.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),
autoOpen:!!W.autoOpen,sessionData:{},sponsored:!1,RZ:{},XH:null,eG:T.trackingParams?g.BW(T.trackingParams):null,J_:q&&q.trackingParams?g.BW(q.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,Qg:null,title:"",customMessage:"",url:null,onClickCommand:T.onTapCommand||null,Dj:X};sQ(M,W)}else if(W.content?.simpleCardContentRenderer){if(!W.cueRanges.length)return;X=W.content?.simpleCardContentRenderer;T=W.teaser.simpleCardTeaserRenderer;q=W.icon?W.icon.infoCardIconRenderer:null;W={id:b,
timestamp:M.W,type:"simple",teaserText:g.Ga(T.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:Y6(M,b,W,X),sponsored:!1,RZ:oM(X,T,X.command),XH:X.trackingParams?g.BW(X.trackingParams):null,eG:T.trackingParams?g.BW(T.trackingParams):null,J_:q&&q.trackingParams?g.BW(q.trackingParams):null,imageUrl:pC(X.image.thumbnails,290,290).url,displayDomain:X.displayDomain?g.Ga(X.displayDomain):null,showLinkIcon:!!X.showLinkIcon,
Qg:null,title:X.title?g.Ga(X.title):"",customMessage:X.callToAction?g.Ga(X.callToAction):"",url:g.z(X.command,g.HF).url?zf({pause_on_navigation:!M.context.videoData.isLivePlayback,target:"new",value:g.z(X.command,g.HF).url}):null,onClickCommand:null};sQ(M,W)}else if(W.content?.collaboratorInfoCardContentRenderer){if(!W.cueRanges.length)return;X=W.content?.collaboratorInfoCardContentRenderer;T=W.teaser.simpleCardTeaserRenderer;q=W.icon?W.icon.infoCardIconRenderer:null;W={id:b,timestamp:M.W,type:"collaborator",
teaserText:g.Ga(T.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:Y6(M,b,W,X),sponsored:!1,RZ:oM(X,T,X.endpoint),XH:X.trackingParams?g.BW(X.trackingParams):null,eG:T.trackingParams?g.BW(T.trackingParams):null,J_:q&&q.trackingParams?g.BW(q.trackingParams):null,channelId:g.z(X.endpoint,g.VL).browseId,customMessage:X.customText?g.Ga(X.customText):null,profileImageUrl:pC(X.channelAvatar.thumbnails,290,
290).url,title:X.channelName?g.Ga(X.channelName):"",metaInfo:[X.subscriberCountText?g.Ga(X.subscriberCountText):""],url:zf({pause_on_navigation:!M.context.videoData.isLivePlayback,target:"new",value:g.z(X.endpoint,g.VL).canonicalBaseUrl?g.z(X.endpoint,g.VL).canonicalBaseUrl:`/channel/${g.z(X.endpoint,g.VL).browseId}`}),onClickCommand:null};sQ(M,W)}else if(W.content?.playlistInfoCardContentRenderer){if(!W.cueRanges.length)return;X=W.content?.playlistInfoCardContentRenderer;T=W.teaser.simpleCardTeaserRenderer;
q=W.icon?W.icon.infoCardIconRenderer:null;W={id:b,timestamp:M.W,type:"playlist",teaserText:g.Ga(T.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:Y6(M,b,W,X),sponsored:!1,RZ:oM(X,T,X.action),XH:X.trackingParams?g.BW(X.trackingParams):null,eG:T.trackingParams?g.BW(T.trackingParams):null,J_:q&&q.trackingParams?g.BW(q.trackingParams):null,G0:pC(X.playlistThumbnail.thumbnails,258,290).url,customMessage:X.customMessage?
g.Ga(X.customMessage):null,playlistVideoCount:g.Ga(X.playlistVideoCount),title:X.playlistTitle?g.Ga(X.playlistTitle):"",metaInfo:[X.channelName?g.Ga(X.channelName):"",X.videoCountText?g.Ga(X.videoCountText):""],url:zf({pause_on_navigation:!M.context.videoData.isLivePlayback,target:"new",value:f3r(X.action)}),onClickCommand:null};sQ(M,W)}else if(W.content?.videoInfoCardContentRenderer){if(!W.cueRanges.length)return;X=W.content?.videoInfoCardContentRenderer;T=W.teaser.simpleCardTeaserRenderer;q=W.icon?
W.icon.infoCardIconRenderer:null;W={id:b,timestamp:M.W,type:"video",teaserText:g.Ga(T.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:Y6(M,b,W,X),sponsored:!1,RZ:oM(X,T,X.action),XH:X.trackingParams?g.BW(X.trackingParams):null,eG:T.trackingParams?g.BW(T.trackingParams):null,J_:q&&q.trackingParams?g.BW(q.trackingParams):null,G0:pC(X.videoThumbnail.thumbnails,258,290).url,videoDuration:X.lengthString?
g.Ga(X.lengthString):null,customMessage:X.customMessage?g.Ga(X.customMessage):null,title:X.videoTitle?g.Ga(X.videoTitle):"",metaInfo:[X.channelName?g.Ga(X.channelName):"",X.viewCountText?g.Ga(X.viewCountText):""],isLiveNow:!!X.badge,url:zf({pause_on_navigation:!M.context.videoData.isLivePlayback,target:"new",value:f3r(X.action)}),onClickCommand:null};sQ(M,W)}M.W++},u$V=function(M,W){return g.pt(M.cards,b=>b.Ma.id===W)},Qu=function(M){g.H(M.L.getRootNode(),"ytp-cards-shopping-active",SS9(M))},cU=function(M,
W){if(W=u$V(M,W))W===M.Z&&(M.Z=null),M.L.removeCueRange(W.Ma.id),g.a5(W.cA),g.X9(M.cards,W),M.BY(),Qu(M)},gT=function(M,W,b){if(!M.B){M.EY.show();
M.Lp=new g.d9(()=>{g.pY(M.context.L.getRootNode(),g.Vg.IV_DRAWER_OPEN)},0);
M.Lp.start();M.MK.J(M.V,"mousewheel",q=>{M.yz.start();q.preventDefault();q=q||window.event;let X=0;q.type=="MozMousePixelScroll"?X=0==(q.axis==q.HORIZONTAL_AXIS)?q.detail:0:window.opera?X=q.detail:X=q.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?q.wheelDeltaY/-30:q.wheelDeltaY/-1.2:q.wheelDelta/-1.6:q.wheelDeltaY/-3;if(q=X)M.V.scrollTop+=q});
M.B=!0;var T=g.nT();T&&M.lV&&M.D&&g.pT(T,[M.lV,M.D]);W={TRIGGER_TYPE:W};for(const q of M.cards)q.tK||(q.tK=!0,OrI(M.context.logger,q.Ma.RZ.c9,W)),T&&g.pT(T,[q.Ma.XH]);UQ(M.L);b&&(M.C=new g.d9(()=>{M.An=M.S;M.OY.focus()},330),M.C.start())}},xP5=function(M){g.Yc(M.BP(),[g.Vg.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.Im(M.L,M.A,5);M.qG();M.S=g.wP("ytp-cards-button",M.L.getRootNode());M.OY=g.wP("iv-drawer-close-button",M.A);M.isInitialized=!0},FRE=function(M){M.gK.push(g.Yw("iv-teaser-shown",M.fv,M));
M.gK.push(g.Yw("iv-teaser-hidden",M.s2,M));M.gK.push(g.Yw("iv-teaser-clicked",M.cP,M));M.vP=!0},RB4=function(M,W){M.O=W;
var b=M.L.getVideoData();if(!b)return!1;b=g.cQ(b);if(b?.markersMap)for(let q=0;b?.markersMap.length>q;q++){var T=b?.markersMap[q];if(T.key==="ERROR_CORRECTION_MARKERS"&&(T=T.value?.markers)&&T.length>0)return W.startMs=g.z(T[0],g.X1a)?.timeRangeStartMillis||0,M.O=null,!0}return!1},rWA=function(M,W){switch(W.type){case "simple":M=M.sY;
var b=W.displayDomain?{K:"div",N:"iv-card-image-text",R0:W.displayDomain}:void 0;var T=I3V(W);b={K:"div",rK:["iv-card"],U:[{K:"a",N:"iv-click-target",Y:{href:W.url?W.url.Z()||"":""},U:[ud(W.imageUrl,b),{K:"div",N:"iv-card-content",U:[Sd("h2",void 0,W.title),T]}]}]};b=new g.w(b);ed(M,g.gP("iv-click-target",b.element),W,W.url);W=b;break;case "collaborator":M=M.sY;b={K:"div",rK:["iv-card","iv-card-channel"],U:[{K:"a",rK:["iv-click-target"],Y:{href:W.url.Z()||"","data-ytid":W.channelId},U:[ud(W.profileImageUrl),
{K:"div",N:"iv-card-content",U:[OQ(W),{K:"h2",N:"iv-card-primary-link",R0:W.title},PU(W)]}]}]};b=new g.w(b);ed(M,g.gP("iv-click-target",b.element),W,W.url);W=b;break;case "playlist":M=M.sY;b={K:"div",rK:["iv-card","iv-card-playlist"],U:[{K:"a",N:"iv-click-target",Y:{href:W.url.Z()||""},U:[ud(W.G0,{K:"div",N:"iv-card-image-overlay",U:[{K:"span",N:"iv-card-playlist-video-count",R0:W.playlistVideoCount}]}),{K:"div",N:"iv-card-content",U:[OQ(W),Sd("h2","iv-card-primary-link",W.title),PU(W)]}]}]};b=new g.w(b);
ed(M,g.gP("iv-click-target",b.element),W,W.url);W=b;break;case "productListing":M=M.sY;var q=W.offers.length!=0;b=["iv-card"];T="";var X=I3V(W);q&&(b.push("iv-card-product-listing"),T="iv-card-primary-link",X=W.offers[0],q=[],X.price&&q.push({K:"div",N:"iv-card-offer-price",R0:X.price}),X.merchant&&q.push({K:"div",N:"iv-card-offer-merchant",R0:X.merchant}),X={K:"div",U:q});q=W.url?W.url.Z()||"":"";b={K:"div",rK:b,Y:{tabindex:"0"},U:[{K:"a",rK:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
W.imageUrl+");",href:q,"aria-hidden":"true",tabindex:"-1"}},{K:"div",N:"iv-card-content",U:[W.sponsored?{K:"div",N:"iv-card-sponsored",U:["Sponsored",{K:"div",N:"iv-ad-info-container",U:[{K:"div",N:"iv-ad-info",R0:"{{adInfo}}"},{K:"div",N:"iv-ad-info-icon-container",U:[{K:"div",N:"iv-ad-info-icon"},{K:"div",N:"iv-ad-info-callout"}]}]}]}:"",{K:"a",N:"iv-click-target",Y:{href:q},U:[Sd("h2",T,W.title),X]}]}]};b=new g.w(b);T=g.Gr("span");g.nr(T,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
b.setContent(T,"adInfo");ed(M,g.gP("iv-click-target",b.element),W,W.url);W=b;break;case "video":M=M.sY;b=W.isLiveNow?{K:"span",rK:["yt-badge","yt-badge-live"],R0:"LIVE NOW"}:null;b={K:"div",rK:["iv-card","iv-card-video"],U:[{K:"a",N:"iv-click-target",Y:{href:W.url?.Z()||""},U:[ud(W.G0,W.videoDuration?{K:"span",N:"iv-card-video-duration",R0:W.videoDuration}:void 0),{K:"div",N:"iv-card-content",U:[OQ(W),Sd("h2","iv-card-primary-link",W.title),PU(W),b]}]}]};b=new g.w(b);ed(M,g.gP("iv-click-target",b.element),
W,W.url);W=b;break;default:return null}return W},hBA=function(M,W){if(!g.w9(M.L.getRootNode(),"ytp-cards-teaser-shown")){if(M.Z!==W){var b=g.nT(),T=M.Z?M.Z.Ma.J_:M.J_;
b&&T&&g.Yn(b,[T]);M.Z=W;Qu(M)}(b=M.isInitialized&&M.BP().style.display=="none")||(b=M.context.L.getPlayerState(),T=b===0&&M.context.L.getCurrentTime()===0,b=!(b===1||b===3||T));b||W.Ma.teaserDurationMs&&M.L.CI(!0,{teaserText:W.Ma.teaserText,durationMs:W.Ma.teaserDurationMs,onClickCommand:W.Ma.onClickCommand,Dj:W.Ma.Dj??null});M.bV.isActive()||((!M.B||!M.yz.isActive()&&M.xk)&&irp(M,W),M.bV.start(910+W.Ma.teaserDurationMs))}},SS9=function(M){return M.Z?M.Z.Ma.type==="productListing":M.L.j("enable_wn_infocards")?
!!M.cards?.length&&g.sq(M.cards,W=>W.Ma.type==="productListing"):g.sq(M.cards,W=>W.Ma.type==="productListing")},irp=function(M,W){M.X.Ta?(W=new mN([0,
M.V.scrollTop],[0,W.cA.offsetTop],600,GrB),M.context.B.listen(W,"animate",b=>{M.V.scrollTop=b.y}),M.context.B.listen(W,"finish",b=>{M.V.scrollTop=b.y}),W.play()):(M.X.eW(!0),M.V.scrollTop=W.cA.offsetTop,M.X.eW(!1))},$8=function(M){return M.Z&&M.Z.Ma?M.Z.Ma:M.cards[0]&&M.cards[0].Ma?M.cards[0].Ma:null},Pq9=function(M){const W=M.annotation.data;
"start_ms"in W&&"end_ms"in W&&M.addCueRange(Number(W.start_ms),Number(W.end_ms),M.annotation.id,()=>{M.show()},()=>{M.hide()})},eBJ=function(M,W){var b=$PV(W).width;
g.P5(W,b);b=new ld(W,[b,W.offsetTop],[b-b,W.offsetTop],200,j5E);g.t(M,b);M.context.B.listen(b,"begin",()=>{g.pr(W,!0)});
b.play()},M0=function(M,W,b){b.stopPropagation();
dPI(M);otJ(M,W);M.Z.focus()},cWh=function(M){const W=M.annotation.data;
if(M.annotation.style==="cta")var b=6;else if(M.annotation.style==="video"||M.annotation.style==="playlist")b=7;M.C=W.collapsedelay_ms||M.C;const T=["iv-promo","iv-promo-inactive"];M.BP().setAttribute("aria-hidden","true");M.BP().setAttribute("aria-label","Promotion");M.BP().tabIndex=0;const q=M.annotation.WF();let X;var G=W.image_url;G&&(X=M.createElement({K:"div",rK:["iv-promo-img","iv-click-target"]}),G=M.createElement({K:"img",Y:{src:G,"aria-hidden":"true"}}),X.appendChild(G),W.video_duration&&
!W.is_live?(G=M.createElement({K:"span",N:"iv-promo-video-duration",R0:W.video_duration}),X.appendChild(G)):W.playlist_length&&(G=M.createElement({K:"span",N:"iv-promo-playlist-length",R0:W.playlist_length.toString()}),X.appendChild(G)),q&&dT(M,X,q,M.annotation.id,W.session_data,void 0,b));q?(G=M.createElement({K:"a",N:"iv-promo-txt"}),g.OY(G,q.Z()),M.Z=G):M.Z=M.createElement({K:"div",N:"iv-promo-txt"});let V,J,B,D;switch(M.annotation.style){case "cta":case "website":V=M.createElement({K:"p",U:[{K:"strong",
R0:W.text_line_1}]});J=M.createElement({K:"p",U:[{K:"span",N:"iv-promo-link",R0:W.text_line_2}]});if(G=W.text_line_3)T.push("iv-promo-website-card-cta-redesign"),B=M.createElement({K:"button",rK:["iv-promo-round-expand-icon","ytp-button"]}),G=M.createElement({K:"button",rK:["iv-button","iv-promo-button"],U:[{K:"span",N:"iv-button-content",R0:G}]}),D=M.createElement({K:"div",N:"iv-promo-button-container"}),D.appendChild(G),q&&dT(M,M.BP(),q,M.annotation.id,W.session_data,void 0,b);g.pY(M.Z,"iv-click-target");
q&&dT(M,M.Z,q,M.annotation.id,W.session_data,void 0,b);break;case "playlist":case "video":V=M.createElement({K:"p",U:[{K:"span",R0:W.text_line_1}]}),J=M.createElement({K:"p",U:[{K:"strong",R0:W.text_line_2}]}),W.is_live&&(V=J,J=M.createElement({K:"span",rK:["yt-badge","iv-promo-badge-live"],R0:"LIVE NOW"})),g.pY(M.Z,"iv-click-target"),q&&dT(M,M.Z,q,M.annotation.id,W.session_data,void 0,b),T.push("iv-promo-video")}V&&M.Z.appendChild(V);J&&M.Z.appendChild(J);M.W.appendChild(M.Z);D&&M.W.appendChild(D);
b=M.createElement({K:"div",N:"iv-promo-actions"});M.V=M.createElement({K:"button",rK:["iv-promo-expand","ytp-button"]});M.V.title="Expand";M.context.Z.listen(M.V,"click",a=>{M0(M,5E3,a)});
b.appendChild(M.V);g.pr(M.V,!1);M.context.Z.listen(M.BP(),"mouseover",M.yz,M);M.context.Z.listen(M.BP(),"mouseout",M.sY,M);M.context.Z.listen(M.BP(),"touchend",a=>{M0(M,5E3,a)});
M.B=M.createElement({K:"button",rK:["iv-promo-close","ytp-button"]});M.B.title="Close";M.context.Z.listen(M.B,"click",M.annotation.style==="cta"&&W.text_line_3?M.O:M.gK,M);b.appendChild(M.B);g.Yc(M.BP(),T);X&&(g.JW(M.BP(),X),B&&X.appendChild(B));g.JW(M.BP(),M.W);g.JW(M.BP(),b)},Wq=function(M){M.A&&(g.yp.clearTimeout(M.A),M.A=null)},dPI=function(M){M.S.stop();
M.isCollapsed&&(g.WN(M.BP(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),M.isCollapsed=!1,M.Z&&M.Z.removeAttribute("aria-hidden"),g.pr(M.V,!1),g.pr(M.B,!0))},otJ=function(M,W){M.A||(M.A=g.MO(function(){Wq(this);
Q5V(this)},W,M))},Q5V=function(M){M.isCollapsed||M.D||M.A||(g.pY(M.BP(),"iv-promo-collapsed"),M.isCollapsed=!0,M.S.start())},OrI=function(M,W,b){W&&(b?b$(M,W.map(T=>g.tf(T,b))):b$(M,W))},b$=function(M,W,b,T){let q=1,X=void 0,G=-1;
if(b){let V=!1;X=()=>{q--;q||V||(clearTimeout(G),V=!0,b())};
G=setTimeout(()=>{V=!0;b()},1E3)}for(const V of W||[])q++,g.zu(V,X);
T&&(q++,T!==0&&M.L.sendVideoStatsEngageEvent(T,X))},gth=function(M){return M==="annotation-editor"||M==="live-dashboard"},s5p=function(M){M.A&&(M.player.removeEventListener("videodatachange",M.A),M.A=null)},w5A=function(M){M=M.createElement({K:"div",
rK:["annotation","annotation-type-custom"]});g.pr(M,!1);return M},q0=function(M,W){var b=!1,T=W.getElementsByTagName("annotations");
if(T&&!(T.length<1)&&(T=T[0].getAttribute("itct"))){var q=g.nT();if(q){var X=g.EB();X&&g.Je(g.OB)(void 0,q,X,[g.BW(T)])}}W=W.getElementsByTagName("annotation");for(T=0;T<W.length;T++){var G=p5r(M,W[T]);q=null;try{a:{if(!G){q=null;break a}var V=G.id;X=/.+/;const n=typeof V==="string"&&X!=null&&V!=null&&V.match(X)?V:"",C=An(G.type,YS4),l=An(G.style,$Ic),N=kr$(G.data),R=N.length!==0?JSON.parse(N):{};b:{var J=G.action;X=tU9;if(J==null){var B=null;break b}if(g.mL(J)){G=[];for(const x of J){const A=X(x);
A&&G.push(A)}B=G;break b}const f=X(J);B=f?[f]:[]}X=B;q=n&&C?new M5E(n,C,l,X,R):null}}catch(n){}if(q)if(q.type==="branding"||q.type==="promotion"){X=M;G=q;var D=w5A(X),a=null;switch(G.type){case "branding":if(X.player.G().Y9)break;X.player.j("web_player_overlay_positioned_layout")?(D.setAttribute("data-overlay-order","11"),X.player.pT(D,4,!0)):X.V.element.appendChild(D);a=new Wx9(D,Te(X),G);break;case "promotion":g.Im(X.player,D,4),a=new bn5(D,Te(X),G)}a&&a.Zs();if(X=a)g.t(M,X),M.C[q.id]=X}else if(q.type===
"card"||q.type==="drawer"){M.Z||(M.Z=T5h(M),g.t(M,M.Z));if(q.type==="card"){D=M.Z;var E=(b=q)&&b.data&&b.data.card_type;q=b.data;if(E)switch(X=q.tracking||{},X={c9:X.impression,click:X.click,close:X.close,Mb:X.teaser_impression,au:X.teaser_click},G=q.tracking_params||{},a=null,E){case "collaborator":b={id:b.id,timestamp:q.timestamp||0,type:q.card_type,teaserText:q.teaser_text,teaserDurationMs:q.teaser_duration_ms,startMs:q.start_ms,autoOpen:q.auto_open||!1,sessionData:q.session_data||{},sponsored:q.sponsored||
!1,RZ:X,XH:G.card?g.BW(G.card):null,eG:G.teaser?g.BW(G.teaser):null,J_:G.icon?g.BW(G.icon):null,channelId:q.channel_id,customMessage:q.custom_message?q.custom_message:null,profileImageUrl:q.image_url,title:q.title,metaInfo:q.meta_info,url:zf({pause_on_navigation:q.pause_on_navigation,target:q.target||"new",value:q.url}),onClickCommand:null};sQ(D,b);break;case "playlist":b={id:b.id,timestamp:q.timestamp||0,type:q.card_type,teaserText:q.teaser_text,teaserDurationMs:q.teaser_duration_ms,startMs:q.start_ms,
autoOpen:q.auto_open||!1,sessionData:q.session_data||{},sponsored:q.sponsored||!1,RZ:X,XH:G.card?g.BW(G.card):null,eG:G.teaser?g.BW(G.teaser):null,J_:G.icon?g.BW(G.icon):null,G0:q.image_url,playlistVideoCount:q.playlist_video_count,customMessage:q.custom_message?q.custom_message:null,title:q.title,metaInfo:q.meta_info,url:zf({pause_on_navigation:q.pause_on_navigation,target:q.target||"new",value:q.url}),onClickCommand:null};sQ(D,b);break;case "productListing":q.signin_url&&(a=zf({target:"current",
value:q.signin_url}));E=[];const n=q.offers||[];for(let C=0;C<n.length;C++)E.push(new qyh(g.JY(n[C].merchant),g.JY(n[C].price)));b={id:b.id,timestamp:q.timestamp||0,type:q.card_type,teaserText:q.teaser_text,teaserDurationMs:q.teaser_duration_ms,startMs:q.start_ms,autoOpen:q.auto_open||!1,sessionData:q.session_data||{},sponsored:q.sponsored||!1,RZ:X,XH:G.card?g.BW(G.card):null,eG:G.teaser?g.BW(G.teaser):null,J_:G.icon?g.BW(G.icon):null,imageUrl:q.image_url,displayDomain:q.display_domain?q.display_domain:
null,showLinkIcon:!!q.show_link_icon,Qg:q.button_icon_url?q.button_icon_url:null,title:q.title,customMessage:q.custom_message?q.custom_message:null,url:zf({pause_on_navigation:q.pause_on_navigation,target:q.target||"new",value:q.url}),paK:a,Pns:q.signin_title?q.signin_title:void 0,AjK:q.signin_message?q.signin_message:void 0,offers:E,onClickCommand:null};sQ(D,b);break;case "simple":b={id:b.id,timestamp:q.timestamp||0,type:q.card_type,teaserText:q.teaser_text,teaserDurationMs:q.teaser_duration_ms,
startMs:q.start_ms,autoOpen:q.auto_open||!1,sessionData:q.session_data||{},sponsored:q.sponsored||!1,RZ:X,XH:G.card?g.BW(G.card):null,eG:G.teaser?g.BW(G.teaser):null,J_:G.icon?g.BW(G.icon):null,imageUrl:q.image_url,displayDomain:q.display_domain?q.display_domain:null,showLinkIcon:!!q.show_link_icon,Qg:q.button_icon_url?q.button_icon_url:null,title:q.title,customMessage:q.custom_message?q.custom_message:null,url:zf({pause_on_navigation:q.pause_on_navigation,target:q.target||"new",value:q.url}),onClickCommand:null};
sQ(D,b);break;case "video":b={id:b.id,timestamp:q.timestamp||0,type:q.card_type,teaserText:q.teaser_text,teaserDurationMs:q.teaser_duration_ms,startMs:q.start_ms,autoOpen:q.auto_open||!1,sessionData:q.session_data||{},sponsored:q.sponsored||!1,RZ:X,XH:G.card?g.BW(G.card):null,eG:G.teaser?g.BW(G.teaser):null,J_:G.icon?g.BW(G.icon):null,G0:q.image_url,videoDuration:q.video_duration||null,customMessage:q.custom_message?q.custom_message:null,title:q.title,metaInfo:q.meta_info,isLiveNow:!!q.is_live_now,
url:zf({pause_on_navigation:q.pause_on_navigation,target:q.target||"new",value:q.url}),onClickCommand:null},sQ(D,b)}}else AW9(M.Z,q);b=!0}}b&&(UQ(M.player),M.X())},X6c=function(M){const W=M.player.G();
M=M.player.getVideoData();return(W.annotationsLoadPolicy||M.annotationsLoadPolicy)===1&&!M.MP||W.lV.get(M.videoId)||M.q1()||g.QL(M)?!0:!1},jdI=function(M,W){W=!W.isCued()&&!W.Z(1024);
M.V.eW(W);M.B.eW(W)},B5A=function(M,W){const b=W.videoId;
var T=X=>{var G=M.loadNumber;M.W=null;M.loaded&&M.loadNumber===G&&M.player.getVideoData().videoId===b&&(X=g.fg(X)&&X.responseXML?X.responseXML:null)&&(q0(M,X),g.pY(M.player.getRootNode(),"iv-module-loaded"))};
g.ku()&&(T=GN9(M,T));const q={format:"XML",onFinish:T,onError:()=>{M.W=null},
urlParams:{}};W.isPharma&&(q.urlParams.pharma="1");q.method="POST";q.withCredentials=!0;(T=M.player.G().lV.get(b))&&V59(q,T);T=T&&T.Wl;if(!W.Bl||T)M.A=()=>{if(!M.O)M.onVideoDataChange(q);const X=M.player.getVideoData();X?.Ic()&&!M.gK&&JhV(M,X)},M.player.addEventListener("videodatachange",M.A)},X_=function(M,W){var b=!1;
M.Z||(M.Z=T5h(M),g.t(M,M.Z));for(var T of W.cards||[])T.cardRenderer&&(zBJ(M.Z,T.cardRenderer),b=!0);b&&(M.player.getVideoData()?.Ic()||(b=M.Z,T=W.headerText?g.Ga(W.headerText):"",g.nr(b.d9,T),b.S&&(b.L.j("player_tooltip_data_title_killswitch")?b.S.setAttribute("title",T):b.S.setAttribute("data-tooltip-title",T)),b.context.videoData.eventId&&(b.eventId=b.context.videoData.eventId),b.lV=W.trackingParams?g.BW(W.trackingParams):null,b.D=W.closeButton.infoCardIconRenderer.trackingParams?g.BW(W.closeButton.infoCardIconRenderer.trackingParams):
null,b.J_=W.icon.infoCardIconRenderer.trackingParams?g.BW(W.icon.infoCardIconRenderer.trackingParams):null,M.X()),UQ(M.player))},JhV=function(M,W){if(W=W.getWatchNextResponse()?.cards?.cardCollectionRenderer)M.gK=!0,X_(M,W),W.headerText&&M.Lz&&(W=g.Ga(W.headerText),M.player.j("player_tooltip_data_title_killswitch")?M.Lz.setAttribute("title",W):M.Lz.setAttribute("data-tooltip-title",W))},GN9=function(M,W){return(...b)=>{M.ST()||M.Zs.push(g.FO.N1(()=>{W(...b)}))}},V59=function(M,W){M.method="POST";
M.postParams=M.postParams||{};W.Wl&&(M.postParams.ic_coll=W.Wl);W.Nb&&(M.postParams.ic_track=W.Nb)},p5r=function(M,W){const b={};
for(var T of W.attributes)b[T.name]=T.nodeValue;for(T=0;T<W.childNodes.length;T++){var q=W.childNodes[T];if(!g.lQ(q)||q.nodeType!=1)continue;var X=void 0;if(b[q.tagName])X=b[q.tagName];else if(q.tagName==="data"){q.childNodes.length>0&&(X=q.childNodes[0].nodeValue,b[q.tagName]=typeof X==="string"?X.trim():X);continue}else X=[],b[q.tagName]=X;q&&q.tagName==="TEXT"?q.childNodes.length===1&&q.childNodes[0].nodeType===3?X.push(q.childNodes[0].nodeValue):X.push(""):q&&X.push(p5r(M,q))}return b},Te=function(M){if(!M.D){const W=
new DIB(M);
g.t(M,W);const b=new g.Tw(M);g.t(M,b);M.D=new acQ(W,b,M.player.G(),M.player.getVideoData(),M.logger,M.player,M.m$)}return M.D},E44=function(M){const W=M.player.getVideoData();
if(W.B$){var b=M.player.G().lV.get(W.videoId);if(b){var T={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(q,X,G)=>{q=M.loadNumber;X=W.videoId;M.loaded&&M.loadNumber===q&&M.player.getVideoData().videoId===X&&(G=g.fg(G)&&G.responseXML?G.responseXML:null)&&q0(M,G)}};
g.ku()&&(T.onFinish=GN9(M,T.onFinish));T.postParams={ic_only:"1"};V59(T,b);M.O=!0;g.Pe(W.B$,T)}}},T5h=function(M){const W=new g.w({K:"div"});
g.pr(W.element,!1);const b=new n4J(M.player,W.element,Te(M));g.t(b,W);W.cY(M.V.element);b.Zs();return b},yh7=function(M,W,b,T,q){if(!M.player.G().Y9){var X=[];
W.navigationEndpoint&&g.z(W.navigationEndpoint,g.VL)&&g.z(W.navigationEndpoint,g.VL).browseId&&X.push(new l35("openUrl","click",new vtQ(`/channel/${g.z(W.navigationEndpoint,g.VL).browseId}`,"new",!0,!0)));var G=W.watermark.thumbnails[0];T={channel_name:W.channelName,end_ms:W.endTimeMs,image_height:G.height,image_type:1,image_url:G.url,image_width:G.width,is_mobile:!1,session_data:{annotation_id:b,ei:q,feature:"iv",itct:W.trackingParams,src_vid:T},start_ms:W.startTimeMs};if(W.subscribeButton&&g.z(W.subscribeButton,
g.vM)){T.channel_id=g.z(W.subscribeButton,g.vM).channelId;W=g.z(W.subscribeButton,g.vM);G=q=null;W.subscribed?(W.subscriberCountWithUnsubscribeText&&(q=g.Ga(W.subscriberCountWithUnsubscribeText)),W.subscriberCountText&&(G=g.Ga(W.subscriberCountText))):(W.subscriberCountText&&(q=g.Ga(W.subscriberCountText)),W.subscriberCountWithSubscribeText&&(G=g.Ga(W.subscriberCountWithSubscribeText)));const V=g.z(W.signInEndpoint?.commandMetadata,g.vL)?.url||"";W={subscribeText:g.Ga(W.unsubscribedButtonText),subscribeCount:q||
"",unsubscribeText:g.Ga(W.subscribedButtonText),unsubscribeCount:G||"",enabled:W.enabled||!1,classic:!1,subscribed:W.subscribed||!1,feature:"iv",signInUrl:V};T.standalone_subscribe_button_data=W}X=new M5E(b,"branding","branding",X,T);T=w5A(M);M.player.j("web_player_overlay_positioned_layout")?(T.setAttribute("data-overlay-order","11"),M.player.pT(T,4,!0)):M.V.element.appendChild(T);X=new Wx9(T,Te(M),X);X.Zs();g.t(X,X);M.C[b]=X}};
g.J0.prototype.CI=g.Wy(36,function(M,W){const b=g.Sc(this.lk());b&&b.CI(M,W)});
var k6={},KC=null;g.rG(mN,g.TH);g.L=mN.prototype;g.L.getDuration=function(){return this.duration};
g.L.play=function(M){if(M||this.Z==0)this.progress=0,this.coords=this.V;else if(this.isPlaying())return!1;vU(this);this.startTime=M=g.Hy();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.BU();this.EJ("play");this.isPaused()&&this.EJ("resume");this.Z=1;const W=g.Zl(this);W in k6||(k6[W]=this);brc();Te4(this,M);return!0};
g.L.stop=function(M){vU(this);this.Z=0;M&&(this.progress=1);qSr(this,this.progress);this.onStop();this.pD()};
g.L.pause=function(){this.isPlaying()&&(vU(this),this.Z=-1,this.EJ("pause"))};
g.L.vY=function(){this.Z==0||this.stop(!1);this.EJ("destroy");mN.EO.vY.call(this)};
g.L.destroy=function(){this.dispose()};
g.L.W5=function(){this.EJ("animate")};
g.L.EJ=function(M){this.dispatchEvent(new X59(M,this))};
g.rG(X59,g.wi);g.rG(LC,mN);LC.prototype.B=function(){};
LC.prototype.W5=function(){this.B();LC.EO.W5.call(this)};
LC.prototype.pD=function(){this.B();LC.EO.pD.call(this)};
LC.prototype.BU=function(){this.B();LC.EO.BU.call(this)};
g.rG(ld,LC);ld.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var DIB=class extends g.gz{constructor(M){super();this.V=M||window;this.Z=[]}listen(M,W,b,T){b=(0,g.IJ)(b,T||this.V);M=g.o$(M,W,b);this.Z.push(M);return M}Gz(M,W,b,T){b=(0,g.IJ)(b,T||this.V);M=MUE(M,W,b);this.Z.push(M);return M}fN(M){g.cV(M);g.X9(this.Z,M)}removeAll(){g.cV(this.Z);this.Z.length=0}vY(){this.removeAll();super.vY()}};var v4I=class extends g.F2{constructor(M){super(M);this.A=this.endscreen=null;this.V={};this.C={};this.S=this.B=null;this.D=[];this.Z=null;this.gK=!0;this.W=0;M=M.G();this.X=g.Th(M)||g.jz(M);this.events=new g.Cq(this);g.t(this,this.events);this.events.J(this.player,g.kJ("creatorendscreen"),this.onCueRangeEnter);this.events.J(this.player,g.KX("creatorendscreen"),this.onCueRangeExit);this.events.J(this.player,"resize",this.XT);this.events.J(window,"focus",this.O);this.load();const W=g.Gr("STYLE");(g.QT("HEAD")[0]||
document.body).appendChild(W);this.addOnDisposeCallback(()=>{g.a5(W)});
W.sheet&&(W.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),W.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!N7(this)){var M=g.XES(this.player.getVideoData());M?(M=IM(M,JWE(this)),HU(this,M,!1)):Eth(this)}}unload(){HU(this,null);this.A&&(this.A.abort(),this.A=null);super.unload()}nK(M,W){return N7(this)?M==="loadCustomEndscreenRenderer"?(M=IM(W,"new"),HU(this,M),!0):null:null}getOptions(){return N7(this)?["loadCustomEndscreenRenderer"]:[]}XT(){if(this.endscreen&&this.endscreen.elements){var M=this.player.getVideoContentRect();if(M&&M.width!==0&&M.height!==0){var W=this.player.getPlayerSize();
if(W&&W.width!==0&&W.height!==0){var b=M.width/M.height;var T=0;var q=-1;for(var X=0;X<UI$.length;X++){var G=Math.abs(W.width-UI$[X]);if(q===-1||T>=G)q=X,T=G}T=C2B[q];this.B&&g.iq(this.B.element,"outline-width",Math.max(W.width,W.height)+"px");for(W=0;W<this.endscreen.elements.length;++W){X=this.endscreen.elements[W].id;q=this.V[X];G=this.C[X];if(!q||!G)continue;const J=G.width*b/G.aspectRatio;var V=Math.round(G.width*M.width);X=Math.round(J*M.height);const B=M.left+Math.round(G.left*M.width),D=M.top+
Math.round(G.top*M.height);g.sS(q.element,V,X);g.P5(q.element,B,D);g.WN(q.element,kNh);V>256||X>256?g.pY(q.element,"ytp-ce-large-round"):V>96||X>96?g.pY(q.element,"ytp-ce-medium-round"):g.pY(q.element,"ytp-ce-small-round");g.WN(q.element,Kxp);V=G.left+G.width/2;G=G.top+J/2;g.pY(q.element,V<=.5&&G<=.5?"ytp-ce-top-left-quad":V>.5&&G<=.5?"ytp-ce-top-right-quad":V<=.5&&G>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.WN(q.element,C2B);g.pY(q.element,T);(q=g.sa(document,"div","ytp-ce-expanding-overlay-body",
q.element)[0])&&g.iq(q,"height",`${X}px`)}}}}}onCueRangeEnter(M){if(this.endscreen)if(M.getId()==="ytp-ce-in-endscreen")id(this,this.endscreen.impressionUrls),(M=g.nT())&&this.endscreen.visualElement&&g.w4(M,this.endscreen.visualElement),this.Z&&(g.pY(this.Z,"ytp-ce-element-show"),this.Z.removeAttribute("aria-hidden"),this.player.Xp()?g.pY(this.Z,"ytp-ce-hide-button-lower"):g.Mw(this.Z,"ytp-ce-hide-button-lower"));else{M=M.getId().substring(15);var W=this.V[M],b=this.C[M];g.pY(W.element,"ytp-ce-element-show");
W.element.removeAttribute("aria-hidden");W=this.player.getRootNode();g.pY(W,"ytp-ce-shown");id(this,b.impressionUrls);(W=g.nT())&&g.w4(W,b.visualElement);this.player.G().D&&g.q8(this.player,"endscreenelementshown",M)}}onCueRangeExit(M){if(M.getId()==="ytp-ce-in-endscreen")this.Z&&(g.Mw(this.Z,"ytp-ce-element-show"),this.Z.setAttribute("aria-hidden","true"));else{M=M.getId().substring(15);var W=this.V[M];g.Mw(W.element,"ytp-ce-element-show");W.element.setAttribute("aria-hidden","true");W=this.player.getRootNode();
g.Mw(W,"ytp-ce-shown");this.player.G().D&&g.q8(this.player,"endscreenelementhidden",M)}}O(M){M.target===window&&(new g.d9(()=>{for(const W of Object.values(this.V))g.WN(W.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}eW(M){for(const W of Object.values(this.V))M?W.element.setAttribute("hidden",""):W.element.removeAttribute("hidden")}Xf(M){this.Z&&this.player.getRootNode().removeChild(this.Z);
M&&(g.pY(M,"ytp-ce-hide-button-container"),this.Z=M,g.Im(this.player,this.Z,4))}},UI$=[346,426,470,506,570,640,853,1280,1920],C2B="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Kxp=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],kNh=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var vtQ=class{constructor(M,W,b,T){this.value=M;this.target=W;this.showLinkIcon=b;this.V=T}Z(){return this.value?this.value:null}},KRQ={RH:"current",hZ:"new"};var l35=class{constructor(M,W,b){this.type=M;this.trigger=W;this.url=b}},mP5={CLOSE:"close",MJ:"openUrl",SUBSCRIBE:"subscribe"},LR5={D3:"click",CLOSE:"close",I1:"hidden",mKK:"rollOut",wYY:"rollOver",nkK:"shown"};var M5E=class{constructor(M,W,b,T,q){this.id=M;this.type=W;this.style=b;this.data=q;this.action=T||[]}WF(){const M=ZrA(this,W=>W.type==="openUrl"&&W.url!=null);
return M?M.url:null}},$Ic={N2:"anchored",Sr:"branding",CHANNEL:"channel",sI:"cta",fh:"highlightText",lF:"label",PLAYLIST:"playlist",POPUP:"popup",uTn:"speech",SUBSCRIBE:"subscribe",B9v:"title",VIDEO:"video",Uez:"website"},YS4={Sr:"branding",f$:"card",c7:"drawer",My:"highlight",GD:"marker",nX:"promotion",TEXT:"text",K$z:"widget"};var mI4=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
LxE=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var lcV=class{constructor(M,W){this.context=M;this.Z=W}};var qyh=class{constructor(M,W){this.merchant=M;this.price=W}};var t5E=class extends g.gz{constructor(M,W){super();this.element=M;this.context=W;this.XX=!1;this.wK=new Map;this.Ds=new Map;this.context.L.addEventListener(g.kJ("annotations_module"),b=>{(b=this.wK.get(b))&&b.apply(this)});
this.context.L.addEventListener(g.KX("annotations_module"),b=>{(b=this.Ds.get(b))&&b.apply(this)})}addCueRange(M,W,b,T,q){M=new g.Ap(M,W,{id:b,
namespace:"annotations_module"});T&&this.wK.set(M,T);q&&this.Ds.set(M,q);this.context.L.QV([M],1)}Zs(){this.context.V.subscribe("resize",this.BY,this)}BP(){return this.element}jT(M,W,b,T,q,X){if(this.XX)return!1;X&&(X.stopPropagation(),X.preventDefault());this.navigate(M,b,T,q);return!1}show(){}hide(){}destroy(){g.a5(this.BP())}BY(){}navigate(M,W,b,T){const q=M.Z();if(q){var X=Hrh(q,M.target),G=()=>{M.V&&this.context.L.pauseVideo();const V=this.context.videoData.uN||!1,J=g.UX(q||"");V&&J&&(J.v||J.list)?
this.context.L.jA(J.v,W,J.list,!1):g.pu(q||"",X==="current"?"_top":void 0,W)};
X==="new"&&(G(),G=null);b$(this.context.logger,b,G,T);Ne5(q)||(b=g.nT(),T=W.itct,b&&T&&g.$X(b,g.BW(T)))}}vY(){this.wK.clear();this.Ds.clear();super.vY()}createElement(M){M=new g.w(M);g.t(this,M);return M.element}};var n4J=class extends t5E{constructor(M,W,b){super(W,b);this.L=M;this.eventId=null;this.vP=this.xk=this.oT=this.B=this.isInitialized=!1;this.cards=[];this.OY=this.S=this.An=this.C=this.Lp=this.Z=null;this.gK=[];this.O=this.D=this.J_=this.lV=null;this.W=0;this.yz=new g.d9(()=>{},b.uV.U1?4E3:3E3);
g.t(this,this.yz);this.bV=new g.d9(()=>{});
g.t(this,this.bV);this.sY=new lcV(b,(T,q,X,G,V,J)=>{dT(this,T,q,X,G,V,J)});
this.X=new g.w({K:"div",N:"iv-drawer",Y:{id:"iv-drawer"},U:[{K:"div",N:"iv-drawer-header",Y:{"aria-role":"heading"},U:[{K:"span",N:"iv-drawer-header-text"},{K:"button",rK:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Hide cards",tabindex:"0"}}]},{K:"div",N:"iv-drawer-content"}]});g.t(this,this.X);this.A=this.X.element;this.EY=new g.Ol(this.X,330);g.t(this,this.EY);this.d9=g.wP("iv-drawer-header-text",this.A);this.V=g.wP("iv-drawer-content",this.A);this.addCueRange(0,b.videoData.lengthSeconds*
1E3,"",()=>{this.oT&&gT(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.oT=this.B)&&wT(this)});
this.MK=new g.Cq(this);g.t(this,this.MK);this.L.addEventListener("videodatachange",this.hm.bind(this))}hm(){this.O&&sQ(this,this.O)}isAvailable(){var M;if(M=!!this.cards.length)(M=this.L.getRootNode())?(M=g.we(M),M=173<M.width&&173<M.height):M=!1;return M}BY(){const M=this.isAvailable();g.pr(this.BP(),M);g.H(this.context.L.getRootNode(),g.Vg.IV_DRAWER_ENABLED,M);UQ(this.L)}destroy(){this.L.CI(!1);try{this.L.getRootNode().removeChild(this.A)}catch(M){}g.$2(this.gK);this.MK.V();this.Lp&&this.Lp.dispose();
this.C&&this.C.dispose();super.destroy()}qG(){this.context.Z.listen(g.wP("iv-drawer-close-button",this.A),"click",this.FT,this);this.context.Z.listen(this.V,"touchend",()=>{this.yz.start()});
this.context.Z.listen(this.V,"scroll",this.WP,this);this.context.V.subscribe("onHideControls",()=>{this.xk=!0});
this.context.V.subscribe("onShowControls",()=>{this.xk=!1});
this.context.V.subscribe("onVideoAreaChange",()=>{this.xk=g.w9(this.L.getRootNode(),"ytp-autohide")});
this.gK.push(g.Yw("iv-button-shown",this.aT,this));this.gK.push(g.Yw("iv-button-hidden",this.Y9,this));FRE(this)}findLastIndex(M){if(this.cards.length===0)return 0;const W=g.YP(this.cards,b=>M.Ma.startMs>b.Ma.startMs||M.Ma.startMs===b.Ma.startMs&&M.Ma.timestamp>=b.Ma.timestamp?!0:!1);
return W===-1?0:W+1}FT(){if(this.B){b$(this.context.logger,$8(this).RZ.close);var M=g.nT();M&&this.D&&g.$X(M,this.D);wT(this)}}WP(){g.H(this.A,"iv-drawer-scrolled",this.V.scrollTop>0)}aT(){const M=g.nT();var W=$8(this);W=W?W.J_:this.J_;M&&W&&g.pT(M,[W])}Y9(){const M=g.nT();var W=$8(this);W=W?W.J_:this.J_;M&&W&&g.Yn(M,[W])}fv(){const M=$8(this);b$(this.context.logger,M.RZ.Mb);const W=g.nT();if(W&&M)if(this.L.j("web_infocards_teaser_show_logging_fix")){const b=[];M.eG&&b.push(M.eG);M.J_&&b.push(M.J_);
b.length>0&&g.pT(W,b)}else g.pT(W,[M.eG,M.J_])}s2(){const M=g.nT(),W=$8(this);M&&W&&g.Yn(M,[W.eG])}cP(M){const W=$8(this),b=g.nT();this.Z?M?(M=this.context.logger,b$(M,W.RZ.au),M.L.sendVideoStatsEngageEvent(4,void 0),b&&W.eG&&g.$X(b,W.eG)):(M=this.context.logger,b$(M,W.RZ.au),M.L.sendVideoStatsEngageEvent(4,void 0),b&&W.J_&&g.$X(b,W.J_)):(M=this.context.logger,b$(M,W.RZ.au),M.L.sendVideoStatsEngageEvent(4,void 0),b&&this.J_&&g.$X(b,this.J_))}};var ZnE=class extends t5E{constructor(M,W,b){super(M,W);this.annotation=b;this.isActive=!1}Zs(){super.Zs();Pq9(this)}show(){super.show();const M=g.nT();var W=this.annotation.data;M&&W&&(W=W.session_data)&&g.pT(M,[g.BW(W.itct)])}hide(){super.hide();const M=g.nT();var W=this.annotation.data;M&&W&&(W=W.session_data)&&g.Yn(M,[g.BW(W.itct)])}};var Wx9=class extends ZnE{constructor(M,W,b){super(M,W,b);this.Z=null;this.B=!1;this.V=null}show(){if(!this.isActive){super.show();if(!this.B){g.pY(this.BP(),"iv-branding");const M=this.annotation.data;this.Z=this.createElement({K:"img",rK:["branding-img","iv-click-target"],Y:{"aria-label":"Channel watermark",src:M.image_url,width:M.image_width,height:M.image_height}});g.pr(this.Z,!1);const W=this.createElement({K:"button",rK:["branding-img-container","ytp-button"]});W.appendChild(this.Z);this.BP().appendChild(W);
const b=this.annotation.WF();b&&dT(this,W,b,this.annotation.id,M.session_data);this.B=!0}g.pr(this.BP(),!0);this.isActive=!0;if(this.Z){try{eBJ(this,this.Z)}catch{}g.pY(this.context.L.getRootNode(),"ytp-branding-shown");this.context.L.getRootNode().style.setProperty("--branding-image-width",`${this.Z.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.pr(this.BP(),!1),this.isActive=!1,g.Mw(this.context.L.getRootNode(),"ytp-branding-shown"))}destroy(){this.V&&(this.V.dispose(),this.V=
null);g.Mw(this.context.L.getRootNode(),"ytp-branding-shown");super.destroy()}};var acQ=class{constructor(M,W,b,T,q,X,G){this.Z=M;this.B=W;this.uV=b;this.videoData=T;this.logger=q;this.L=X;this.V=G}};var bn5=class extends ZnE{constructor(M,W,b){super(M,W,b);this.D=this.isCollapsed=this.X=!1;this.C=5E3;this.V=this.B=this.Z=this.A=null;this.W=this.createElement({K:"div",rK:["iv-promo-contents"]});this.S=new g.d9(()=>{this.Z.setAttribute("aria-hidden","true");g.pr(this.B,!1);g.pr(this.V,!0)},700,this);
g.t(this,this.S)}show(){this.isActive||(super.show(),this.X||(cWh(this),this.X=!0),g.pr(this.BP(),!0),g.MO(function(){g.Mw(this.BP(),"iv-promo-inactive")},100,this),this.BP().removeAttribute("aria-hidden"),this.isActive=!0,Wq(this),dPI(this),otJ(this,this.C))}hide(){this.isActive&&(g.pY(this.BP(),"iv-promo-inactive"),this.isActive=!1,this.BP().setAttribute("aria-hidden","true"))}jT(M,W,b,T,q,X){return this.isCollapsed?!1:super.jT(M,W,b,T,q,X)}yz(M){this.D=!0;
M0(this,500,M)}sY(){this.D=!1;Q5V(this)}gK(M){M.stopPropagation();this.hide()}O(M){M.stopPropagation();Wq(this);this.isCollapsed=!0;g.pY(this.BP(),"iv-promo-collapsed-no-delay");this.S.start()}destroy(){this.S.dispose();super.destroy()}};var Ic7=class{constructor(M){this.L=M}};g.FQ("annotations_module",class extends g.F2{constructor(M){super(M);this.gK=this.O=!1;this.loadNumber=0;this.C={};this.logger=new Ic7(this.player);this.S=new g.Cq(this);this.W=this.A=null;this.events=new g.Cq(this);this.Lz=this.D=this.Z=null;this.Zs=[];g.t(this,this.S);this.S.J(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.S.J(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.S.J(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.S.J(this.player,"resize",b=>{this.publish("resize",b)});
this.S.J(this.player,"presentingplayerstatechange",b=>{this.publish("presentingplayerstatechange",b)});
this.subscribe("presentingplayerstatechange",this.yz,this);this.subscribe("resize",this.X,this);this.player.G().lV.subscribe("vast_info_card_add",this.sY,this);g.t(this,this.events);this.BY=this.createElement({K:"div",N:"video-custom-annotations"});this.V=new g.w({K:"div",rK:["ytp-player-content","ytp-iv-player-content"]});g.t(this,this.V);g.Im(this.player,this.V.element,4);this.V.hide();this.B=new g.w({K:"div",rK:["ytp-iv-video-content"]});g.t(this,this.B);M=this.createElement({K:"div",N:"video-annotations"});
M.appendChild(this.BY);this.B.element.appendChild(M);this.Wi()?this.load():this.player.j("web_fix_annotations")&&(this.A=()=>{this.loaded||this.ST()||!this.Wi()||(s5p(this),this.load())},this.player.addEventListener("videodatachange",this.A));
const W=this.createElement({K:"style"});(g.QT("HEAD")[0]||document.body).appendChild(W);this.addOnDisposeCallback(()=>{g.a5(W)});
if(M=W.sheet){for(const b of mI4)M.insertRule(b,0);for(const b of LxE)M.insertRule(b,0)}}nK(M,W){if(!gth(this.player.G().playerStyle))return null;switch(M){case "loadCustomAnnotationsXml":return(M=g.UD(W))&&q0(this,M),!0;case "removeCustomAnnotationById":return W&&this.Z&&(cU(this.Z,W),UQ(this.player)),!0}return null}getOptions(){return gth(this.player.G().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}Wi(){const M=this.player.getVideoData(),W=M.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return M.uN||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.j("web_fix_annotations")?X6c(this)?W?.isWatermarkEnforced===!0?!0:W?.isAnnotationsEnabled??!1:!1:X6c(this)}X(){if(this.B){var M=this.player.qe().getVideoContentRect(!0);g.sS(this.B.element,M.width,M.height);g.P5(this.B.element,M.left,M.top)}if(this.Z){var W=this.player.RE();M=this.Z;W=W.width;g.H(M.A,"iv-drawer-small",W<=426);g.H(M.A,"iv-drawer-big",W>=1280)}}yz(M){jdI(this,M.state);M.state.Z(2)&&(this.Xp()&&this.Uk()&&this.player.getPresentingPlayerType()!==
2&&this.jJ(!1),this.CI(!1))}load(){super.load();jdI(this,this.player.getPlayerStateObject());this.loadNumber++;const M=this.player.getVideoData();B5A(this,M);g.Im(this.player,this.B.element,4);this.X();var W=g.QL(M);const b=M.q1();if(this.player.j("web_fix_annotations")){if(W&&(W.featuredChannel&&yh7(this,W.featuredChannel,W.annotationId||"branding",M.videoId||null,M.eventId||null),W=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,W?.isWatermarkEnforced&&!W?.isAnnotationsEnabled))return;
b&&X_(this,b)}else b&&X_(this,b),W&&W.featuredChannel&&yh7(this,W.featuredChannel,W.annotationId||"branding",M.videoId||null,M.eventId||null);this.Lz=g.wP("ytp-cards-button",this.player.getRootNode());M.Ic()&&JhV(this,M)}onVideoDataChange(){}unload(){this.player.lN("annotations_module");for(const M of Object.keys(this.C))this.C[M].destroy();this.D=null;this.Z&&(this.Z.destroy(),this.Z=null,UQ(this.player));this.O=!1;this.W&&(this.W.abort(),this.W=null);this.gK=!1;this.C={};this.V.hide();super.unload();
this.B.detach();s5p(this)}sY(M){M===this.player.getVideoData().videoId&&(this.loaded?E44(this):this.load())}Xp(){return this.Z?.isAvailable()||this.gK}Uk(){return!!this.Z&&this.Z.B}jJ(M,W=!1,b){this.Xp();this.Z&&(M?b?gT(this.Z,b,W):gT(this.Z,"YOUTUBE_DRAWER_AUTO_OPEN",W):wT(this.Z))}CI(M,W){this.player.publish(M?"cardsteasershow":"cardsteaserhide",W)}vY(){this.player.G().lV.unsubscribe("vast_info_card_add",this.sY,this);g.Mw(this.player.getRootNode(),g.Vg.IV_DRAWER_OPEN);var M=this.Zs,W=g.FO;for(let b=
0,T=M.length;b<T;b++)W.Oh(M[b]);this.Zs.length=0;super.vY()}createElement(M){M=new g.w(M);g.t(this,M);return M.element}});g.FQ("creatorendscreen",v4I);})(_yt_player);
