(function(g){var window=this;'use strict';var HnV=async function(M,W,b){M.V=g.Pe(W,b)},jb=function(M){M.isActive()||M.start()},Ge=function(M,W){return W?M.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},fcJ=function(M){return g.Zk(M)||M.j("web_enable_caption_language_preference_stickiness")},Rmh=function(M,W){const b=new g.zh;
b.languageCode=M.languageCode;b.languageName=M.languageName;b.name=M.name;b.displayName=M.displayName;b.kind=M.kind;b.isDefault=!1;b.Z=M.Z;b.isTranslateable=M.isTranslateable;b.vssId=M.vssId;b.url=M.url;b.translationLanguage=W;M.xtags&&(b.xtags=M.xtags);M.captionId&&(b.captionId=M.captionId);return b},rhc=async function(M,W){M=M+"|"+W;
W=await g.qo();if(!W)throw g.FZ("gct");return(await g.pL(W)).get("captions",M)},xI$=function(M,W,b){rhc(M,W).then(T=>{T&&b(T.trackData,new g.zh(T.metadata))})},Vy=function(M){if(!FxB.test(M))throw Error("'"+M+"' is not a valid hex color");
M.length==4&&(M=M.replace(inr,"#$1$1$2$2$3$3"));M=M.toLowerCase();M=parseInt(M.slice(1),16);return[M>>16,M>>8&255,M&255]},hmA=function(){var M={};
let W="suggest_correction"in g.Iu?g.Iu.suggest_correction:"Edit caption";W=W||"";for(let b in M){const T=()=>String(M[b]);
W=W.replace(new RegExp("\\$\\{"+b+"\\}","gi"),T);W=W.replace(new RegExp("\\$"+b,"gi"),T)}return W},J_=function(){return g.MZ("yt-player-caption-display-settings")},Ahh=function(M,W){let b=g.k5(M.segments,W);
b>=0||b<0&&(-b-1)%2===1||(b=-b-1,b>0&&W-M.segments[b-1]===1&&b<M.segments.length&&M.segments[b]-W===1?(g.qE(M.segments,b),g.qE(M.segments,b-1)):b>0&&W-M.segments[b-1]===1?M.segments[b-1]=W:b<M.segments.length&&M.segments[b]-W===1?M.segments[b]=W:(g.nJ(M.segments,b,0,W),g.nJ(M.segments,b+1,0,W)))},zmV=function(M){return M.Z&&M.Z.S?M.Z.S+M.player.Ga()<M.player.getCurrentTime():!1},uYI=function(M,W){if(M.policy.xL&&M.player.Q4()){var b=g.rx(W,M.policy,{});
b.set("pot",M.player.Q4());b=b.WF()}else b=g.rx(W,M.policy,{}).WF();const T={format:"RAW",withCredentials:!0};if(M.policy.lV){T.method="POST";const G=W.A;G&&Object.keys(G).length>0?T.postBody=g.Sr(G,g.CW):T.postBody=(0,g.Ba)([120,0])}M.S&&(T.responseType="arraybuffer");let q=++M.Zs;const X=(0,g.u)();M.V=g.pg(b,T,3,100,-1,G=>{G.errorCode==="net.timeout"&&M.player.dK("capnt",{rn:q++})}).then(G=>{if(M.policy.PQ&&q%100===1){var V=(0,g.u)();
M.player.dK("caprsp",{rn:q,ms:V-X,kb:(G.xhr.responseText.length/1024).toFixed()})}a:{G=G.xhr;M.ST();if(M.B){var J=!(M.S?G.response:G.responseText)||G.status>=400;if(V=g.$Vg(G)){G=g.rx(M.B,M.policy,{});M.B.h2(G,V);uYI(M,M.B);break a}J?M.player.dK("capfail",{status:G.status}):(g.Cd("fcb_r",(0,g.u)(),M.player.getVideoData()?.gK||""),V=M.B.g9[0],J=V.Kp,M.D!=null&&M.C!==J&&(M.S?M.D(G.response,(V.startTime+M.player.Ga())*1E3):M.D(G.responseText,(V.startTime+M.player.Ga())*1E3),M.C=J))}M.B=null;M.V=null}}).JD(G=>
{M.B=null;
M.V=null;M.player.dK("capfail",{rn:q,status:G.xhr?.status})});
M.B=W;Ahh(M.A,M.B.g9[0].Kp)},SyV=function(M,W){return W!=null&&W in M.V.Z?M.V.Z[W]:null},OnJ=function(M,W,b){const T=[];
for(const q in M.V.Z){if(!M.V.Z.hasOwnProperty(q))continue;const X=M.V.Z[q];if(g.AQ(X,b||null)){const G=X.info.captionTrack;G&&G.languageCode===W&&T.push(X)}}return T.length?T[0]:null},emA=function(M,W){const b=[];
for(const q in M.V.Z){if(!M.V.Z.hasOwnProperty(q))continue;var T=M.V.Z[q];if(g.AQ(T,W||null)){let X=T.info.id,G=X,V=`.${X}`,J="",B="";if(T=T.info.captionTrack)X=T.languageCode,G=T.displayName,V=T.vssId,J=T.kind,B=T.id;else{{T=X;let D=g.lBV.get(T);D==null&&(D=P2J[T]||P2J[T.replace(/-/g,"_")],g.lBV.set(T,D));T=D}G=T||G}b.push(new g.zh({id:q,languageCode:X,languageName:G,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:V,kind:J,captionId:B}))}}return b},dII=function(M,W,b,T){let q=W/360*16;
W>=M&&(M=640,T>b*1.3&&(M=480),q=b/M*16);return q},o4A=function(M){let W=1+.25*(M.fontSizeIncrement||0);
if(M.offset===0||M.offset===2)W*=.8;return W},ch7=function(M,W){let b="vertical-rl";
M.Z.G1===1&&(b="vertical-lr");g.V8&&(b=b==="vertical-lr"?"tb-lr":"tb-rl");g.iq(W,"-o-writing-mode",b);g.iq(W,"-webkit-writing-mode",b);g.iq(W,"writing-mode",b);g.iq(W,"text-orientation","upright");g.pY(W,"ytp-vertical-caption");M.V.params.mq===3&&(g.iq(W,"text-orientation",""),g.iq(W,"transform","rotate(180deg)"))},QdA=function(M,W){const b={};
var T=W.background?W.background:M.Z.qa.background;if(W.backgroundOpacity!=null||W.background){var q=W.backgroundOpacity!=null?W.backgroundOpacity:M.Z.qa.backgroundOpacity;T=Vy(T);b.background="rgba("+T[0]+","+T[1]+","+T[2]+","+q+")";M.aT&&(b["box-decoration-break"]="clone",b["border-radius"]=`${M.jT/8}px`)}if(W.fontSizeIncrement!=null||W.offset!=null)b["font-size"]=`${M.wK*o4A(W)}px`;T=1;q=W.color||M.Z.qa.color;if(W.color||W.textOpacity!=null)q=Vy(q),T=W.textOpacity==null?M.Z.qa.textOpacity:W.textOpacity,
q="rgba("+q[0]+","+q[1]+","+q[2]+","+T+")",b.color=q,b.fill=q;var X=W.charEdgeStyle;X===0&&(X=void 0);if(X){q=`rgba(34, 34, 34, ${T})`;let J=`rgba(204, 204, 204, ${T})`;W.rj&&(J=q=W.rj);const B=M.wK/16/2,D=Math.max(B,1);var G=Math.max(2*B,1),V=Math.max(3*B,1);const a=Math.max(5*B,1);T=[];switch(X){case 4:for(;V<=a;V+=B)T.push(`${G}px ${G}px ${V}px ${q}`);break;case 1:G=window.devicePixelRatio>=2?.5:1;for(X=D;X<=V;X+=G)T.push(`${X}px ${X}px ${q}`);break;case 2:T.push(`${D}px ${D}px ${J}`);T.push(`-${D}px -${D}px ${q}`);
break;case 3:for(V=0;V<5;V++)T.push(`0 0 ${G}px ${q}`)}b["text-shadow"]=T.join(", ")}q="";switch(W.fontFamily){case 1:q='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:q='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:q='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:q='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:q='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:q=g.EL()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:q='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}q&&(b["font-family"]=q);q=W.offset;q==null&&(q=M.Z.qa.offset);switch(q){case 0:b["vertical-align"]="sub";break;case 2:b["vertical-align"]="super"}W.fontFamily===7&&(b["font-variant"]="small-caps");W.bold&&(b["font-weight"]="bold");W.italic&&(b["font-style"]="italic");W.underline&&
(b["text-decoration"]="underline");W.VR&&(b.visibility="hidden");W.IS===1&&M.A&&(b["text-combine-upright"]="all",b["text-orientation"]="mixed",q=g.vQ||g.R_,M.V.params.mq===3?b.transform=q?"rotate(90deg)":"rotate(180deg)":q&&(b.transform="rotate(-90deg)"));if(W.textEmphasis===1||W.textEmphasis===2||W.textEmphasis===3||W.textEmphasis===4||W.textEmphasis===5)if(g.vQ)b["font-weight"]="bold";else switch(b["text-emphasis-style"]="filled circle",b["text-emphasis-color"]="currentcolor",b["webkit-text-emphasis"]=
"filled circle",W.textEmphasis){case 4:case 3:b["text-emphasis-position"]="under left";b["webkit-text-emphasis-position"]="under left";break;case 5:case 2:b["text-emphasis-position"]="over right",b["webkit-text-emphasis-position"]="over right"}return b},Bq=function(M){M=M.split("px");
return M.length>0?(M=Number(M[0]))?M:0:0},w6J=function(M,W,b){M.lV=M.lV||!!b;
const T={};Object.assign(T,M.Z.qa);Object.assign(T,b||W.Z);Object.assign(T,M.x_.qa);(b=!M.W)&&g4h(M);let q=M.An&&M.xk&&g.oQ(T,M.xk)?M.An:sd7(M,T);const X=typeof W.text==="string",G=X?W.text.split("\n"):[W.text];for(let J=0;J<G.length;J++){var V=J>0||!W.append;const B=G[J];V&&!b?(g4h(M),q=sd7(M,T)):V&&b&&(b=!1);B&&(q.appendChild(X?g.V4(B):B),X||B.tagName!=="RUBY"||B.childElementCount!==4||g.vQ||!g.zr(B.children[2],"text-emphasis")||(V=M.A?"padding-right":"padding-top",g.zr(B.children[2],"text-emphasis-position")&&
(V=M.A?"padding-left":"padding-bottom"),g.bq?g.iq(q,V,"1em"):g.iq(q,V,"0.5em")))}M.xk=T;M.An=q;M.C.push(W)},g4h=function(M){M.W=g.Gr("SPAN");
g.iq(M.W,{display:"block"});g.pY(M.W,"caption-visual-line");M.B.appendChild(M.W)},sd7=function(M,W){const b=g.Gr("SPAN");
g.iq(b,{display:"inline-block","white-space":"pre-wrap"});g.iq(b,QdA(M,W));b.classList.add("ytp-caption-segment");M.W.appendChild(b);b.previousElementSibling&&(g.iq(b.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.iq(b,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return b},YyE=function(M,W,b){if(M===255&&W===255||!M&&!W)return{wp:M,
P$:W,result:0};M=p6c[M];W=p6c[W];if(M&128){var T;if(T=!(W&128))T=W,T=b.S2()&&b.P$===T;if(T)return{wp:M,P$:W,result:1}}else if(W&128&&1<=M&&M<=31)return{wp:M,P$:W,result:2};return{wp:M,P$:W,result:3}},MvA=function(M,W,b,T){W===255&&b===255||!W&&!b?(++M.B===45&&M.reset(),M.A.V.clear(),M.S.V.clear()):(M.B=0,$_c(M.A,W,b,T))},W17=function(M,W){M.Z.sort((b,T)=>{const q=b.time-T.time;
return q===0?b.order-T.order:q});
for(const b of M.Z)M.time=b.time,b.type===0?MvA(M,b.mI,b.w3,W):b.type===1&&M.V&496&&$_c(M.S,b.mI,b.w3,W);M.Z.length=0},jFc=function(M,W){switch(M){case 0:return b3c[(W&127)-32];
case 1:return TvI[W&15];case 2:return qUI[W&31];case 3:return Xb9[W&31]}return 0},DK=function(M,W){if(M.style.type===3){var b=0,T=0,q=M.S.time+0,X="",G="",V=q;
for(var J=1;J<=15;++J){var B=!1;for(var D=T?T:1;D<=32;++D){var a=M.B[J][D];if(a.Z!==0){b===0&&(b=J,T=D);B=String.fromCharCode(a.Z);var E=a.timestamp;E<q&&(q=E);a.timestamp=V;G&&(X+=G,G="");X+=B;B=!0}if((a.Z===0||D===32)&&B){G="\n";break}else if(T&&!B)break}if(b&&!B)break}X&&W.A(b,T,q,V,X)}else for(T=b=0,X=q=M.S.time+0,G=1;G<=15;++G)for(V="",J=1;J<=32;++J)if(D=M.B[G][J],a=D.Z,a!==0&&(b===0&&(b=G,T=J),B=String.fromCharCode(a),E=D.timestamp,E<=q&&(q=E),V+=B,D.reset()),J===32||a===0)V&&W.A(b,T,q,X,V),
q=X,V="",T=b=0},aa=function(M){return M.B[M.row][M.V]},EC=function(M,W,b){W>=2&&M.V>1&&(--M.V,aa(M).Z=0);
const T=aa(M);T.timestamp=M.S.time+0;T.Z=jFc(W,b);M.V<32&&M.V++},Gsp=function(M,W,b,T){for(let G=0;G<T;G++)for(let V=0;V<=32;V++){var q=M.B[W+G][V],X=M.B[b+G][V];
q.Z=X.Z;q.timestamp=X.timestamp}},nh=function(M,W,b){for(let T=0;T<b;T++)for(let q=0;q<=32;q++)M.B[W+T][q].reset()},yy=function(M){M.row=M.Z>0?M.Z:1;
M.V=1;nh(M,0,15)},VvJ=function(M){M.style.set(1);
M.Z=M.A;M.Z.Z=0;M.Z.style=M.style;M.B.mode=1<<M.Z.A},UC=function(M,W,b){const T=M.V;
let q=!1;switch(M.style.get()){case 4:case 1:case 2:M.style.get()===4&&T.Z>0||(DK(T,b),yy(M.V),yy(M.A),T.row=15,T.Z=W,q=!0)}M.style.set(3);M.Z=T;M.Z.style=M.style;M.B.mode=1<<T.A;q?T.V=1:T.Z!==W&&(T.Z>W?(DK(T,b),nh(T,T.row-T.Z,W)):T.row<W&&(W=T.Z),T.Z=W)},J6V=function(M){M.style.set(4);
M.Z=M.text;M.Z.style=M.style;M.B.mode=1<<M.Z.A},$_c=function(M,W,b,T){M.V.update();
W=YyE(W,b,M.V);switch(W.result){case 0:return;case 1:case 2:return}var q=W.wp;W=W.P$;if(32<=q||!q)M.Z.mode&M.Z.V&&(b=q,b&128&&(b=127),W&128&&(W=127),M=M.A.Z,b&96&&EC(M,0,b),W&96&&EC(M,0,W),b!==0&&W!==0&&M.style.type===3&&DK(M,T));else if(q&16)a:if(!M.V.matches(q,W)&&(b=M.V,b.wp=q,b.P$=W,b.state=2,b=q&8?M.C:M.B,M.A=b,M.Z.mode=1<<(M.S<<2)+(b.S<<1)+(b.style.type===4?1:0),(M.Z.mode|1<<(M.S<<2)+(b.S<<1)+(b.style.type!==4?1:0))&M.Z.V))if(W&64){T=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(q&7)<<1|W>>5&1];
M=W&16?((W&14)>>1)*4:0;W=b.Z;switch(b.style.get()){case 4:T=W.row;break;case 3:if(T!==W.row){if(T<W.Z&&(T=W.Z,T===W.row))break;var X=1+W.row-W.Z;const G=1+T-W.Z;Gsp(W,G,X,W.Z);b=X;q=W.Z;G<X?(X=G+q-X,X>0&&(b+=X,q-=X)):(X=X+q-G,X>0&&(q-=X));nh(W,b,q)}}W.row=T;W.V=M+1}else switch(q&7){case 1:switch(W&112){case 32:EC(b.Z,0,32);break a;case 48:W===57?(T=b.Z,aa(T).Z=0,T.V<32&&T.V++):EC(b.Z,1,W&15)}break;case 2:W&32&&EC(b.Z,2,W&31);break;case 3:W&32&&EC(b.Z,3,W&31);break;case 4:case 5:if(32<=W&&W<=47)switch(W){case 32:VvJ(b);
break;case 33:T=b.Z;T.V>1&&(--T.V,aa(T).Z=0);break;case 36:T=b.Z;M=aa(T);for(W=0;W<=15;W++)for(b=0;b<=32;b++)if(T.B[W][b]===M){for(;b<=32;b++)T.B[W][b].reset();break}break;case 37:UC(b,2,T);break;case 38:UC(b,3,T);break;case 39:UC(b,4,T);break;case 40:EC(b.Z,0,32);break;case 41:T=b;T.style.set(2);T.Z=T.V;T.Z.Z=0;T.Z.style=T.style;T.B.mode=1<<T.Z.A;break;case 42:T=b;M=T.text;M.Z=15;M.style.set(4);yy(M);J6V(T);break;case 43:J6V(b);break;case 44:M=b;W=M.V;switch(M.style.get()){case 1:case 2:case 3:DK(W,
T)}nh(W,0,15);break;case 45:b:{W=b;M=W.Z;switch(W.style.get()){default:case 2:case 1:break b;case 4:if(M.row<15){++M.row;M.V=1;break b}break;case 3:}M.Z<2&&(M.Z=2,M.row<M.Z&&(M.row=M.Z));W=M.row-M.Z+1;DK(M,T);Gsp(M,W,W+1,M.Z-1);nh(M,M.row,1)}break;case 46:nh(b.A,0,15);break;case 47:M=b,DK(M.V,T),M.A.updateTime(M.B.time+0),T=M.A,M.A=M.V,M.V=T,VvJ(M)}break;case 7:switch(W){case 33:case 34:case 35:T=b.Z,(T.V+=W&3)>32&&(T.V=32)}}},D_r=function(M,W,b,T,q,X,G){var V=X[0];
let J=G[V.getAttribute("p")];if(J.gW===1){var B=X[1],D=X[2];X=X[3];V.getAttribute("t");B.getAttribute("t");D.getAttribute("t");X.getAttribute("t");V.getAttribute("p");B.getAttribute("p");X.getAttribute("p");G=G[D.getAttribute("p")];V=BvJ(V.textContent,B.textContent,D.textContent,X.textContent,G);return new Ch(M,W,q,b,V,T,J)}switch(J.gW){case 9:case 10:J.textEmphasis=1;break;case 11:J.textEmphasis=2;break;case 12:J.textEmphasis=3;break;case 13:J.textEmphasis=4;break;case 14:J.textEmphasis=5}return new Ch(M,
W,q,b,V.textContent||"",T,J)},BvJ=function(M,W,b,T,q){var X=g.EL();
const G=X?g.Gr("DIV"):g.Gr("RUBY"),V=g.Gr("SPAN");V.textContent=M;G.appendChild(V);M=X?g.Gr("DIV"):g.Gr("RP");M.textContent=W;G.appendChild(M);W=X?g.Gr("DIV"):g.Gr("RT");W.textContent=b;G.appendChild(W);b=q.gW;if(b===10||b===11||b===12||b===13||b===14)if(g.iq(W,"text-emphasis-style","filled circle"),g.iq(W,"text-emphasis-color","currentcolor"),g.iq(W,"webkit-text-emphasis","filled circle"),q.gW===11||q.gW===13)g.iq(W,"webkit-text-emphasis-position","under left"),g.iq(W,"text-emphasis-position","under left");
b=!0;if(q.gW===4||q.gW===7||q.gW===12||q.gW===14)g.iq(G,"ruby-position","over"),g.iq(G,"-webkit-ruby-position","before");else if(q.gW===5||q.gW===6||q.gW===11||q.gW===13)g.iq(G,"ruby-position","under"),g.iq(G,"-webkit-ruby-position","after"),b=!1;q=X?g.Gr("DIV"):g.Gr("RP");q.textContent=T;G.appendChild(q);X&&(T=b,g.iq(G,{display:"inline-block",position:"relative"}),X=G.firstElementChild.nextElementSibling,g.iq(X,"display","none"),X=X.nextElementSibling,g.iq(X,{"font-size":"0.5em","line-height":"1.2em",
"text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.iq(G.lastElementChild,"display","none"),T?(g.iq(G,"padding-top","0.6em"),g.iq(X,"top","0")):(g.iq(G,"padding-bottom","0.6em"),g.iq(X,"bottom","0")));return G},a$E=function(M){const W="_"+k8++;
return new Kh(0,0x8000000000000,0,W,M)},vq=function(M,W){M=M.getAttribute(W);
if(M!=null)return Number(M)},mY=function(M,W){M=M.getAttribute(W);
if(M!=null)return M==="1"},Lh=function(M,W){M=vq(M,W);
return M!==void 0?M:null},t_=function(M,W){M=M.getAttribute(W);
if(M!=null)return l$.test(M),M},Ex7=function(M,W){const b={},T=W.getAttribute("ws");
Object.assign(b,T?M.X[T]:M.A);M=Lh(W,"mh");M!=null&&(b.Ou=M);M=Lh(W,"ju");M!=null&&(b.textAlign=M);M=Lh(W,"pd");M!=null&&(b.mq=M);M=Lh(W,"sd");M!=null&&(b.G1=M);M=t_(W,"wfc");M!=null&&(b.windowColor=M);W=vq(W,"wfo");W!==void 0&&(b.windowOpacity=W/255);return b},nxE=function(M,W){const b={},T=W.getAttribute("wp");
T&&Object.assign(b,M.D[T]);M=Lh(W,"ap");M!=null&&(b.Um=M);M=vq(W,"cc");M!=null&&(b.IN=M);M=vq(W,"ah");M!=null&&(b.BO=M);M=vq(W,"rc");M!=null&&(b.mM=M);W=vq(W,"av");W!=null&&(b.WM=W);return b},y6$=function(M,W,b,T){let q={};
Object.assign(q,nxE(M,W));Object.assign(q,Ex7(M,W));T?g.oQ(q,M.A)?(T=M.S,q=M.A):T="_"+k8++:T=W.getAttribute("id")||"_"+k8++;M=vq(W,"t")+b;W=vq(W,"d")||0x8000000000000;if(q.mq===2||q.mq===3)b=q.mM,q.mM=q.IN,q.IN=b;return new Kh(M,W,0,T,q)},ZK=function(M){M=g.fy(Math.round(M),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-M.length)+M},U_I=function(M,W,b,T,q){T===0&&(T=0x8000000000000);
const X={};W.wpWinPosId&&Object.assign(X,M.A.get(W.wpWinPosId));W.wsWinStyleId&&Object.assign(X,M.S.get(W.wsWinStyleId));M=W.rcRowCount;M!==void 0&&(X.mM=M);W=W.ccColCount;W!==void 0&&(X.IN=W);if(X.mq===2||X.mq===3)W=X.mM,X.mM=X.IN,X.IN=W;return new Kh(b,T,0,q,X)},Ia=function(M){const W=M.byteOffset;
M.byteOffset+=1;return M.Z.getUint8(W)},N0=function(M){const W=M.byteOffset;
M.byteOffset+=4;return M.Z.getUint32(W)},K1p=function(M){if(typeof M==="string")return!1;
M=new C84(M,0);return ksE(M)},ksE=function(M){if(!(M.byteOffset<M.Z.byteLength)||N0(M)!==1380139777)return!1;
M.version=Ia(M);if(M.version>1)return!1;Ia(M);Ia(M);Ia(M);return!0},vxI=function(M,W){if(!W)return"";
M.A&&M.V.params.G1!==1&&(W*=-1);return`translate${M.A?"X":"Y"}(${W}px)`},m_7=function(M){M.yz=Array.from(M.element.getElementsByClassName("caption-visual-line"));
for(var W=M.V.params.mM,b=0,T=0,q=M.yz.length-1;b<W&&q>-1;){var X=M.yz[q];T+=M.A?X.offsetWidth:X.offsetHeight;b++;q--}M.O=T;W=Math;b=W.max;isNaN(M.BY)&&((T=M.Z.IN)?(q=g.Gr("SPAN"),g.nr(q,"\u2013".repeat(T)),g.iq(q,QdA(M,M.Z.qa)),M.B.appendChild(q),M.BY=q.offsetWidth,M.B.removeChild(q)):M.BY=0);T=M.B;M.Zs=b.call(W,M.BY,M.FT,(M.A?T.offsetHeight:T.offsetWidth)+1)},L14=function(M,W){m_7(M);
var b=M.yz.reduce((T,q)=>(M.A?q.offsetWidth:q.offsetHeight)+T,0);
b=M.O-b;if(b!==M.MK){const T=b>0&&M.MK===0,q=b<M.MK;W||isNaN(b)||T||!q||(g.pY(M.element,"ytp-rollup-mode"),M.J(M.element,"transitionend",M.EY));g.iq(M.B,"transform",vxI(M,b));M.MK=b}m_7(M)},tv7=function(M,W){M.Z=(b,T)=>{if(b.info.B){var q=b;
if(M.Mw.length>0){for(q=M.Mw.shift();M.Mw.length>0;)q=q.C(M.Mw.shift());q=q.C(b)}if(q){b=q;try{var X=g.dx(b)*1E3}catch(n){X=b.info.startTime*1E3}try{var G=g.oXs(b)*1E3}catch(n){G=b.info.duration*1E3}if(X<0||G<0)X<0&&(X=b.info.startTime*1E3),G<0&&(G=b.info.duration*1E3);b.info.startTime=X/1E3;b.info.A=X/1E3;b.info.duration=G/1E3;b.info.D=G/1E3;const {formatId:V,Kp:J,startTimeMs:B,durationMs:D}=M.bq(q);X={formatId:V,startTimeMs:B,durationMs:D,Zd:J,Fy:J};G=l$p(M.h5,X.startTimeMs);const a=(b=G>=0?M.h5[G]:
null)?b.startTimeMs+b.durationMs:0,E=X.startTimeMs+X.durationMs;!b||X.startTimeMs-a>M.V?M.h5.splice(G+1,0,X):(b.durationMs=Math.max(a,E)-b.startTimeMs,b.Fy=Math.max(b.Fy,X.Fy));T(M.h5);X=g.Oe(q);T=M.B;X=X.buffer.slice(X.byteOffset,X.byteLength+X.byteOffset);q=q.info.A;T.gK?T.D==null?g.SV(T.logger,350058965,"Null loaded track meta data at captions data received"):W.Lq(X,T.D,q*1E3):g.SV(T.logger,350058965,"Null Representation at captions data received")}else g.SV(M.logger,350058965,"Empty slice")}else M.Mw.push(b)};
M.L.addEventListener("sabrCaptionsDataLoaded",M.Z)},l$p=function(M,W){M=g.k5(M,{startTimeMs:W},(b,T)=>b.startTimeMs-T.startTimeMs);
return M>=0?M:-M-2},Z37=function(M,W){if(!g.VAL(M)||M.Z!=null&&g.hQ(W,M.Z)&&M.Z.Z.rawcc!=null)return!1;
W=!!M.Z&&M.Z.isManifestless&&Object.values(M.Z.Z).some(b=>g.AQ(b,"386"));
M=!!M.Z&&!M.Z.isManifestless&&g.vDl(M.Z);return W||M},I$r=function(M,W,b){const T=[];
for(const q in M.V.Z){if(!M.V.Z.hasOwnProperty(q))continue;const X=M.V.Z[q];if(g.AQ(X,b||null)){const G=X.info.captionTrack;G&&G.languageCode===W&&T.push(X)}}return T.length?T[0]:null},NvB=function(M,W){const b=[];
for(const q in M.V.Z){if(!M.V.Z.hasOwnProperty(q))continue;var T=M.V.Z[q];if(g.AQ(T,W||null)){let X=T.info.id,G=X,V=`.${X}`,J="",B="";if(T=T.info.captionTrack)X=T.languageCode,G=T.displayName,V=T.vssId,J=T.kind,B=T.id;b.push(new g.zh({id:q,languageCode:X,languageName:G,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:V,kind:J,captionId:B}))}}return b},f$V=function(M){const W=H3Q.length;
if(M.byteLength<W)return!1;M=new Uint8Array(M,0,W);for(let b=0;b<W;b++)if(H3Q[b]!==M[b])return!1;return!0},Hq=function(M){M=M.split(":");
let W=0;for(const b of M)W=W*60+Number(b);return W*1E3},RE7=function(M,W,b,T){T=Object.assign({Ou:0},T);
return new Kh(M,W,b,"_"+k8++,T)},r6r=function(M,W,b,T,q,X,G,V,J){switch(G.tagName){case "b":V.bold=!0;
break;case "i":V.italic=!0;break;case "u":V.underline=!0}for(let D=0;D<G.childNodes.length;D++){var B=G.childNodes[D];if(B.nodeType===3)B=new Ch(W,b,T,q.id,B.nodeValue,X||D>0,g.P$(V)?void 0:V),J.push(B),q.Z.push(B);else{const a={};Object.assign(a,V);r6r(M,W,b,T,q,!0,B,a,J)}}},F1r=function(M,W,b){if(typeof W==="string"||K1p(W))return[{trackData:W,
GG:b}];if(typeof W==="string"&&W.substring(0,6)==="WEBVTT"||typeof W!=="string"&&f$V(W))return[{trackData:W,GG:b}];const T=new DataView(W);if(T.byteLength<=8||T.getUint32(4)!==1718909296)return[];var q=g.APP(T);if(M.Cv&&q){var X=g.N4s(q),G=g.HTy(q);q=q.oE;X&&q&&M.Cv.UH(q,X,G)}M=g.op(T,1835295092);if(!M||!M.length||!M[0].size)return[];X=[];for(G=0;G<M.length;G++)q=M[G],q=new Uint8Array(W,q.dataOffset,q.size-(q.dataOffset-q.offset)),q=g.La(q),X.push({trackData:q,GG:b+G*1E3});x_Q(T,X,b);return X=X.filter(V=>
!!V.trackData)},hEA=function(M,W,b){M.Z||(M.Z=new i3$);
M=M.Z.B(W,b);Math.random()<.01&&g.lR(Error("Deprecated subtitles format in web player: WebVTT"));return M},x_Q=function(M,W,b){var T=g.OV(M,0,1836476516);
let q=9E4;T&&(q=g.P_(T)||9E4);T=0;const X=g.op(M,1836019558);for(let V=0;V<X.length;V++){var G=X[V];V<W.length&&(G=g.OV(M,G.dataOffset,1953653094))&&(G=g.OV(M,G.dataOffset,1952867444))&&(G=g.dW(G)/q*1E3,V===0&&(T=G),W[V].GG=G-T+b||b*V*1E3)}},A6h=function(M){const W={};
if(M=g.xj(M))W.lang=M,g.QVs.test(M)&&(W.mq=1);return W},zE4=function(M){const W=!!M.L.E2()?.sY();
return M.B==="HLS"&&W?!0:M.Lp&&W&&M.B!=="LIVE"&&M.B!=="SABR_LIVE"},Ra=function(M,W,b=!1){const T=fh.qa;
M.S={};Object.assign(M.S,fh);M.S.qa={};Object.assign(M.S.qa,T);M.C={qa:{}};var q=W.backgroundOverride?M.C:M.S,X=W.background||T.background;l$.test(X);q.qa.background=X;q=W.colorOverride?M.C:M.S;X=W.color||T.color;l$.test(X);q.qa.color=X;q=W.windowColorOverride?M.C:M.S;X=W.windowColor||fh.windowColor;l$.test(X);q.windowColor=X;q=W.backgroundOpacityOverride?M.C:M.S;X=W.backgroundOpacity;X==null&&(X=T.backgroundOpacity);q.qa.backgroundOpacity=X;q=W.fontSizeIncrementOverride?M.C:M.S;X=W.fontSizeIncrement;
X==null&&(X=T.fontSizeIncrement);q.qa.fontSizeIncrement=X;X=W.fontStyleOverride?M.C:M.S;q=W.fontStyle;q==null&&(q=T.bold&&T.italic?3:T.bold?1:T.italic?2:0);X=X.qa;switch(q){case 1:X.bold=!0;delete X.italic;break;case 2:delete X.bold;X.italic=!0;break;case 3:X.bold=!0;X.italic=!0;break;default:delete X.bold,delete X.italic}q=W.textOpacityOverride?M.C:M.S;X=W.textOpacity;X==null&&(X=T.textOpacity);q.qa.textOpacity=X;q=W.windowOpacityOverride?M.C:M.S;X=W.windowOpacity;X==null&&(X=fh.windowOpacity);q.windowOpacity=
X;q=W.charEdgeStyleOverride?M.C:M.S;X=W.charEdgeStyle;X==null&&(X=T.charEdgeStyle);q.qa.charEdgeStyle=X;q=W.fontFamilyOverride?M.C:M.S;X=W.fontFamily;X==null&&(X=T.fontFamily);q.qa.fontFamily=X;M.loaded&&M.OY();b&&g.$u("yt-player-caption-display-settings",W,2592E3)},rg=function(M,W,b){W&&!M.gK?(W=a$E({mq:0,
lang:"en-GB"}),M.gK=[W,new Ch(W.start,W.end-W.start,0,W.id,b??"Captions look like this")],M.player.QV(M.gK)):!W&&M.gK&&(uWV(M,M.gK),M.gK=null)},SUQ=function(M){if(!M.L.isInline())return g.MZ("yt-player-sticky-caption")},x8=function(M){let W=void 0;
const b=g.jQ().UY(65);if(g.Zk(M.uV)&&b!=null){if(SUQ(M)!=null)return!1;W=!b}return W},O3c=function(M){if(M.uV.Fp===1||M.videoData.lm===1||g.Ob(M.videoData,"yt:cc")==="alwayson")return!0;
let W;M.videoData.captionTracks.length&&(W=M.getAudioTrack().V);if(M.uV.Fp===2){if(g.Zk(M.uV))var b=SUQ(M);else if(M.storage)try{b=M.storage.get("module-enabled")}catch(q){M.storage.remove("module-enabled")}else b=null;if(b!=null)return!!b}b=Ge(M.player.getAudioTrack(),g.Zk(M.uV));const T=g.Ob(M.videoData,"yt:cc");if(x8(M)===void 0){if(b==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return T?T==="on":!0;if(b==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return T==="on"}else return T==="on";return W==="ON"||
g.Ob(M.videoData,"yt:cc")==="on"},F_=function(M,W=!1){if(M.Z&&!W||!M.videoData.captionTracks.length)return!1;
M=M.getAudioTrack();return!!M.Z||M.V==="FORCED_ON"},P8r=function(M,W){if(M.Z){var b=M.L.E2().BP().textTracks,T=null;
M.B==="HLS"?T=M.Z.getId():T=M.Z.toString();for(let X=0;X<b.length;X++){var q=b[X];q.id===T&&(W?q.mode!=="showing"&&(q.mode="showing",q=M.Z,M.Ts(q,!!q,i$(M)?"g":M.W?"m":"s")):q.mode==="showing"&&(q.mode="disabled"))}}},i$=function(M){const W=h_(M);
return!!W&&M.Z===W},eEE=function(M,W){if(M.B==="HLS")return!1;
g.sb(M.videoData)&&(W=!0);W||(W=M.B==="TTS"?!1:M.B==="INNERTUBE"?!1:!0);return W||M.uV.j("web_deprecate_always_includes_asr_setting")&&g.Zk(M.uV)?!0:!!g.jQ().UY(66)},h_=function(M){return M.X&&M.X.Z},A_=function(M,W){if(!M.V)return null;
if(M.X&&M.X.A)return M.X.A;W=eEE(M,W);W=g.nk(M.V.Z,W);let b=null;if(fcJ(M.uV)){var T=M.L.isInline()?void 0:g.MZ("yt-player-caption-sticky-language");var q=[T,M.videoData.captionsLanguagePreference,M.uV.captionsLanguagePreference,g.Ob(M.videoData,"yt:cc_default_lang")];let V=!1;for(let J=0;J<q.length;J++){const B=q[J];if(B){V=!0;for(var X=0;X<W.length;X++)if(g.xj(W[X])===B)return W[X];for(X=0;X<W.length;X++)if(g.xj(W[X]).split("-")[0]===B.split("-")[0])return W[X]}}if(V&&M.V&&(q=M.V.X,q.length))for(var G of q)if(G.languageCode===
T){b=G;break}}else for(G=[M.videoData.captionsLanguagePreference,M.uV.captionsLanguagePreference,g.Ob(M.videoData,"yt:cc_default_lang")],T=0;T<G.length;T++)for(q=0;q<W.length;q++)if(g.xj(W[q])===G[T])return W[q];G=null;M.X&&M.X.B&&(G=M.X.B);G||(G=W.find(V=>V.isDefault)||null);
G||(G=W[0]||h_(M));G&&b&&g.xj(G).split("-")[0]!==b.languageCode.split("-")[0]&&(G=Rmh(G,b));return G},OC=function(M,W,b){M.loaded&&M.unload();
b!=null&&(M.W=b,M.W&&(g.Zk(M.uV)?ze(M,!!W):u$(M,!!W)));W!==null||F_(M,!0)||M.Ts(W,!!W,M.W?"m":"s");M.Z=W;F_(M)&&(M.Z=h_(M));Sb(M,M.Z??void 0);M.load()},ze=function(M,W){M.L.isInline()||g.$u("yt-player-sticky-caption",W,2592E3)},u$=function(M,W){if(M.storage)try{M.storage.set("module-enabled",W)}catch(b){}},Sb=function(M,W){M.uV.j("html5_modify_caption_vss_logging")&&(M.videoData.fH=W)},ox9=function(M,W){var b=M.Zs[W.id];
b&&b.V!==W&&(b.dispose(),delete M.Zs[W.id],b=null);b||(b=d_c(M,W))&&(M.Zs[W.id]=b)},c6$=function(M,W){const b=W.windowId;
M.MK[b]||(M.MK[b]=[]);M.MK[b].push(W)},d_c=function(M,W){const b=QFr(M);
if(!b)return null;var T=M.Z?g.xj(M.Z):null;T&&g.QVs.test(T)&&(W.params.mq=1);var q=M.bV.getPlayerSize();T=q.height*M.O.height;q=q.width*M.O.width;M.uV.playerStyle!=="google-live"||M.S.isDefault||Object.assign(W.params,M.S);switch(W.params.Ou!=null?W.params.Ou:W.Z.length>1?1:0){case 1:return new gxJ(W,M.S,M.C,b.width,b.height,q,T,M.uV.experiments,M.wK.bind(M),M.L);case 2:return new sFc(W,M.S,M.C,b.width,b.height,q,T,M.uV.experiments,M.wK.bind(M),M.L);default:return new Pq(W,M.S,M.C,b.width,b.height,
q,T,M.uV.experiments,M.wK.bind(M),M.L)}},QFr=function(M){let W=M.bV.getVideoContentRect(!0).height,b=M.bV.getVideoContentRect(!0).width;
if(!W||!b)return null;W*=M.O.height;b*=M.O.width;return{width:b,height:W}},uWV=function(M,W){M.player.Ng(W);
for(const b of W)g.X9(M.BY,b);jb(M.lV)},wbA=function(M,W){if(!M.V)return{};
if(W){g.P$(W)||M.zs(W.vss_id,"m");if(M.A&&M.B!=="HLS"||!g.lQ(W))return;if(g.P$(W)){OC(M,null,!0);return}let T;var b=g.nk(M.V.Z,!0);for(let q=0;q<b.length;q++){const X=b[q];X.languageCode!==W.languageCode||T&&(X.languageName!==W.languageName||(X.captionId||"")!==(W.captionId||"")||g.RU(X)!==W.displayName)||(T=W.translationLanguage?Rmh(X,W.translationLanguage):X)}M.ZX(W.position);!T||T===M.Z&&M.loaded||(W=g.Ic(),b=g.xj(T),W.length&&b===W[W.length-1]||(W.push(b),g.$u("yt-player-caption-language-preferences",
W)),fcJ(M.uV)&&!M.L.isInline()&&g.$u("yt-player-caption-sticky-language",b,2592E3),OC(M,T,!0))}else return M.loaded&&M.Z&&!i$(M)?g.rL(M.Z):{};return""};
g.g7.prototype.UH=g.Wy(65,function(M,W,b){this.V.set(M,{Xv:W,Jb:b})});
g.s_.prototype.UH=g.Wy(64,function(M,W,b){this.gK.UH(M,W,b)});
g.iM.prototype.O=g.Wy(63,function(){return!1});
g.iM.prototype.A=g.Wy(62,function(){});
g.h0.prototype.A=g.Wy(61,function(M,W,b){this.ST();W=this.C(M,W);const T=this.o0.G().j("html5_report_captions_ctmp_qoe"),q=(0,g.u)();this.B();HnV(this,W,{format:"RAW",onSuccess:X=>{this.V=null;if(T){var G=(X.responseText.length/1024).toFixed();const V=(0,g.u)();this.videoData.dK("capresp",{ms:V-q,kb:G})}G=X.getResponseHeader&&X.getResponseHeader("Content-Length")?Number(X.getResponseHeader("Content-Length")):0;b.Lq(X.responseText,M,void 0,void 0,G)},
onError:T?X=>{this.videoData.dK("capfail",{status:X?.status??0})}:void 0,
withCredentials:!0})});
g.A0.prototype.A=g.Wy(60,function(M,W,b){this.ST();W=this.C(M,W);this.B();this.V=g.Pe(W,{format:"RAW",onSuccess:T=>{this.V=null;const q=T.getResponseHeader&&T.getResponseHeader("Content-Length")?Number(T.getResponseHeader("Content-Length")):0;b.Lq(T.responseText,M,void 0,void 0,q)},
withCredentials:!0})});
g.Qm.prototype.W=g.Wy(59,function(){const M=g.sa(document,"track",void 0,this.Z);for(let W=0;W<M.length;W++)g.a5(M[W])});
g.p0.prototype.W=g.Wy(58,function(){this.mediaElement.W()});
g.Qm.prototype.yz=g.Wy(57,function(){return!(!this.Z.textTracks||!this.Z.textTracks.addEventListener)});
g.p0.prototype.yz=g.Wy(56,function(){return this.mediaElement.yz()});
g.Qm.prototype.sY=g.Wy(55,function(){return!!this.Z.textTracks});
g.p0.prototype.sY=g.Wy(54,function(){return this.mediaElement.sY()});
g.Qm.prototype.gK=g.Wy(53,function(M){for(let W=0;W<M.length;W++)this.Z.appendChild(M[W])});
g.p0.prototype.gK=g.Wy(52,function(M){this.mediaElement.gK(M)});
g.J0.prototype.rr=g.Wy(40,function(M){return g.Qk(this.app,{playerType:void 0}).rr(M)});
g.ya.prototype.rr=g.Wy(39,function(M){return this.qK.b$.rr(M)});
g.Z9.prototype.rr=g.Wy(38,function(M){return this.xS().some(W=>W.namespace===M)});
g.d7.prototype.rr=g.Wy(37,function(){return!1});
g.J0.prototype.zs=g.Wy(35,function(M,W){this.app.Jn().zs(M,W)});
g.ya.prototype.zs=g.Wy(34,function(M,W){this.qK.zs(M,W)});
g.m9.prototype.zs=g.Wy(33,function(M,W){M=[M,W];g.hm(this,g.u3(this.provider),"cfi",M)});
g.t0.prototype.zs=g.Wy(32,function(M,W){this.qoe&&this.qoe.zs(M,W)});
g.mg.prototype.zs=g.Wy(31,function(M,W){this.Df.zs(M,W)});
g.d7.prototype.zs=g.Wy(30,function(){});
g.J0.prototype.Ts=g.Wy(29,function(M,W,b){this.app.Jn().Ts(M,W,b)});
g.ya.prototype.Ts=g.Wy(28,function(M,W,b){this.qK.Ts(M,W,b)});
g.m9.prototype.Ts=g.Wy(27,function(M,W,b){if(this.lV!==M||this.d9!==W)W=W==="rawcc"?"":W,b=[M,W,this.lV,b],g.hm(this,g.u3(this.provider),"cfs",b),this.lV=M,this.d9=W});
g.t0.prototype.Ts=g.Wy(26,function(M,W,b){this.qoe&&this.qoe.Ts(M,W,b)});
g.mg.prototype.Ts=g.Wy(25,function(M,W,b){this.Df.Ts(M,W,b)});
g.d7.prototype.Ts=g.Wy(24,function(){});
g.pq.prototype.Go=g.Wy(3,function(M){return(M=this.B(M))?M.Z:0});
g.$l.prototype.Go=g.Wy(2,function(){return 0});
var inr=/#(.)(.)(.)/,FxB=/^#(?:[0-9a-f]{3}){1,2}$/i,P2J={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Arab:"Kazakh (Arabic)",kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",ku_Latn:"Kurdish (Latin)",kum:"Kumyk",kut:"Kutenai",kv:"Komi",
kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",
maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",
mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",
nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pms:"Piedmontese",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",
pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",
sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",
sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelauan",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",
tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",
vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",
zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"},pbc={en:"English"},YUh=class extends g.iM{constructor(M){super(M);this.V=new Set}S(M){var W=this.o0.E2();if(W&&W.BP()){W=W.BP().textTracks;for(const b of W)b.kind==="subtitles"&&!this.V.has(b.language)&&b.language&&(g.ij(this.Z,new g.zh({languageCode:b.language,languageName:b.language,kind:b.kind,id:b.id,displayName:pbc[b.label]||b.label,vss_id:`.${b.language}`})),this.V.add(b.language))}g.nk(this.Z).length>
0&&M.ZJ()}},$69=class{constructor(){this.segments=[]}contains(M){M=g.k5(this.segments,M);return M>=0||M<0&&(-M-1)%2===1}length(){return this.segments.length/2}},MxA=class extends g.gz{constructor(M,W,b,T,q,X){super();this.policy=M;this.player=W;this.Tv=b;this.D=T;this.S=q;this.O=X;this.A=new $69;this.C=-1;this.V=this.B=this.Z=null;this.Zs=0;this.W=new g.d9(this.gK,1E3,this);this.events=new g.Cq(this);g.t(this,this.W);g.t(this,this.events);this.events.J(W,"SEEK_COMPLETE",this.X);this.X();this.gK()}vY(){super.vY();
this.V&&this.V.cancel()}X(){this.seekTo(this.player.getCurrentTime())}seekTo(M){M-=this.player.Ga();const W=this.Z;this.Z=g.zS(this.Tv.C(M).g9);W!==this.Z&&this.O&&this.O()}reset(){this.A=new $69;this.C=-1;this.V&&(this.V.cancel(),this.V=null)}gK(){this.ST();var M;if(M=this.Z!=null)M=this.Z,M=M.Tv.A(M);if(M&&!this.V&&!(this.Z&&this.Z.startTime-this.player.getCurrentTime()>30)){M=this.Z;M=M.Tv.lV(M);const q=M.g9[0];if(this.player.getVideoData()?.enableServerStitchedDai){var W=this.player.Tl();if(W){var b=
q.Tv.info.id;const X=q.Kp;var T=M.g9[0].A;if(this.policy.lV){if(W=g.kOa(W,T,X,b,3))M.A=W}else if(b=W.iJ(T,X,b,3))if(T=2,W.GT.has(X)?T=0:g.kv(W,X)&&(T=1),W=T,W===0)b&&(M.Z=new g.LJ(b));else if(W===2){this.W.start();zmV(this)&&this.seekTo(this.player.getCurrentTime());return}}}q.Tv.index.Z5(q.Kp)?(this.A.contains(M.g9[0].Kp)||uYI(this,M),this.Z=g.zS(M.g9)):zmV(this)&&this.seekTo(this.player.getCurrentTime())}this.W.start()}},W2r=class extends g.iM{constructor(M,W){super(W);this.V=M;this.L=W;this.D=
null;this.gK=!1;this.logger=new g.uk("caps");this.Zs=g.hQ(this.L,this.V)}A(M,W,b){this.B();W=SyV(this,M.getId());W||(W=M.languageCode,W=this.V.isManifestless?OnJ(this,W,"386"):OnJ(this,W));if(W){var T=(W.index.Go(W.index.UJ())-W.index.getStartTime(W.index.UJ()))*1E3,q=new g.aAq(this.L.G());this.D=new MxA(q,this.L,W,(X,G)=>{b.Lq(X,M,G,T)},this.Zs||g.FH(W.info),()=>{this.D&&this.D.reset();
this.gK=!0})}}O(){const M=this.gK;
this.gK=!1;return M}S(M){var W=this.L.G().j("html5_fallback_if_rawcc_missing");const b=this.V.Z.rawcc!=null;if(!this.Zs||!b&&W)W=this.V.isManifestless?emA(this,"386"):emA(this);else{if(!b){g.SV(this.logger,386248249,"rawcc used but unavailable");return}W=[new g.zh({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.zh({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(const T of W)g.ij(this.Z,
T);M.ZJ()}B(){this.D&&(this.D.dispose(),this.D=null)}C(){return""}},l$=/^#(?:[0-9a-f]{3}){1,2}$/i;var b$Q=["left","right","center","justify"];var Pq=class extends g.w{constructor(M,W,b,T,q,X,G,V,J,B){const D=B.isInline()&&!0,a={};Object.assign(a,W);Object.assign(a,M.params);Object.assign(a,b);const E={};Object.assign(E,W.qa);M.params.qa&&Object.assign(E,M.params.qa);Object.assign(E,b.qa);D&&(a.windowOpacity=.6,E.backgroundOpacity=0);a.qa=E;const n=a.mq===1,C=[{K:"span",N:"captions-text",Y:{style:"word-wrap: normal; display: block;"}}],l=V.FX("caption_edit_on_hover")&&B.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
l&&C.unshift({K:"button",N:"caption-edit",Y:{tabindex:"0","aria-label":hmA()},U:[{K:"svg",Y:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},U:[{K:"path",Y:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({K:"div",N:"caption-window",Y:{id:`${"caption-window"}-${M.id}`,dir:n?"rtl":"ltr",tabindex:"0",lang:a.lang},U:C});this.C=
[];this.lV=!1;this.V=M;this.xk=this.An=null;this.sj=X;this.k_=G;this.W=null;this.maxWidth=X*.96;this.maxHeight=G*.96;this.Z=a;this.x_=b;this.sY=W;this.B=this.hn("captions-text");this.aT=this.B.style.getPropertyValue("box-decoration-break")!==""||this.B.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.wK=dII(T,q,X,G);this.A5=J;l&&(this.S=this.hn("caption-edit"),this.J(this.S,"click",()=>{this.A5()}));
this.type=0;this.jT=this.wK*o4A(E);this.vP=D;this.Ds=V.FX("enable_centered_caption_for_tvfilm_video")&&B.getVideoData().isTvfilmVideo;this.X=B.G().hT().Z.UY(g.VsJ);M=new g.C0(this.element,!0);g.t(this,M);M.subscribe("dragstart",this.GY,this);M.subscribe("dragmove",this.m$,this);M.subscribe("dragend",this.Hr,this);this.XX=this.bV=this.d9=this.OY=0;M="";this.Z.windowOpacity&&(M=Vy(this.Z.windowColor),M="rgba("+M[0]+","+M[1]+","+M[2]+","+this.Z.windowOpacity+")");W={"background-color":M,display:this.Z.isVisible===
!1?"none":"","text-align":b$Q[this.Z.textAlign]};this.aT&&(W["border-radius"]=M?`${this.jT/8}px`:"");(this.A=this.V.params.mq===2||this.V.params.mq===3)&&ch7(this,this.element);g.iq(this.element,W);D&&this.element.parentElement?.style.setProperty("--caption-window-color",M);switch(this.Z.Um){case 0:case 1:case 2:g.pY(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.pY(this.element,"ytp-caption-window-bottom")}}GY(M,W){this.bV=M;this.XX=W;const b=g.ge(this.element,this.element.parentElement);
this.OY=M-b.x;this.d9=W-b.y}m$(M,W){if(M!==this.bV||W!==this.XX){g.w9(this.element,"ytp-dragging")||g.pY(this.element,"ytp-dragging");var b=g.we(this.element);M=M-this.OY-.02*this.sj;var T=W-this.d9-.02*this.k_,q=(M+b.width/2)/this.maxWidth*3;q=Math.floor(g.fy(q,0,2));var X=(T+b.height/2)/this.maxHeight*3;X=Math.floor(g.fy(X,0,2));W=q+X*3;M=(M+q/2*b.width)/this.maxWidth;M=g.fy(M,0,1)*100;b=(T+X/2*b.height)/this.maxHeight;b=g.fy(b,0,1)*100;this.V.params.Um=W;this.V.params.WM=b;this.V.params.BO=M;this.V.params.isDefault=
!1;this.Z.Um=W;this.Z.WM=b;this.Z.BO=M;this.Z.isDefault=!1;this.sY.Um=W;this.sY.WM=b;this.sY.BO=M;this.sY.isDefault=!1;this.WP()}}Hr(){g.Mw(this.element,"ytp-dragging")}WP(){this.D(this.C)}D(M){var W=this.vP?0:Math.min(this.fv(),this.maxWidth),b=this.cP(),T=this.vP;if(T){var q=getComputedStyle(this.B.parentNode);q=Bq(q.borderLeftWidth)+Bq(q.borderRightWidth)+Bq(q.paddingLeft)+Bq(q.paddingRight)}else q=0;const X=q;q="";this.V.params.mq===3&&(q="rotate(180deg)");var G=T?`calc(${"96%"} - ${X}px)`:"96%";
g.iq(this.element,{top:0,left:0,right:"",bottom:"",width:W?`${W}px`:"",height:b?`${b}px`:"","max-width":G,"max-height":G,margin:"",transform:""});this.Lp(M);q={transform:q,top:"",left:"",width:W?`${W}px`:"",height:b?`${b}px`:"","max-width":"","max-height":""};G=this.Z.Um;var V=this.Z.BO;const J=this.Z.WM;this.Ds&&G!=null&&(V=50,G=Math.floor(G/3)*3+1);V=V*.96+2;switch(G){case 0:case 3:case 6:(T=this.Z.qa.fontSizeIncrement)&&T>0&&this.Z.mq!==2&&this.Z.mq!==3&&(V=Math.max(V/(1+T*2),2));q.left=`${V}%`;
break;case 1:case 4:case 7:q.left=`${V}%`;V=0;this.X||(V=this.B.offsetWidth);W||V?(W=W||V+1,q.width=`${W}px`,q["margin-left"]=T?`${W/-2-X/2}px`:`${W/-2}px`):(this.X&&(q.width="max-content"),q.transform+=" translateX(-50%)");break;case 2:case 5:case 8:q.right=`${100-V}%`}T=J*.96+2;switch(G){case 0:case 1:case 2:q.top=`${T}%`;break;case 3:case 4:case 5:q.top=`${T}%`;T=0;this.X||(T=this.element.clientHeight);(b=b||T)?(q.height=`${b}px`,q["margin-top"]=`${b/-2}px`):q.transform+=" translateY(-50%)";break;
case 6:case 7:case 8:q.bottom=`${100-T}%`}g.iq(this.element,q);if(this.S){if(this.X)b=this.jT;else{if(this.Ds&&M.length===0)M=0;else{b=1;for(T=0;T<M.length;T++)q=M[T],typeof q.text==="string"&&(b+=q.text.split("\n").length-1,q.append||T===0||b++);M=b}b=this.Ds?M>0?this.B.offsetHeight/M:0:this.B.offsetHeight/M}this.S.style.height=`${b}px`;this.S.style.width=`${b}px`;this.element.style.paddingLeft=`${b+5}px`;this.element.style.paddingRight=`${b+5}px`;this.X||(M=Number(this.element.style.marginLeft.replace("px",
""))-b-5,b=Number(this.element.style.marginRight.replace("px",""))-b-5,this.element.style.marginLeft=`${M}px`,this.element.style.marginRight=`${b}px`)}}Lp(M){let W;for(W=0;W<M.length&&M[W]===this.C[W];W++);if(this.lV||this.C.length>W)W=0,this.lV=!1,this.C=[],this.W=this.xk=this.An=null,g.B5(this.B);for(;W<M.length;W++)w6J(this,M[W])}fv(){return 0}cP(){return 0}toString(){return super.toString()}};var qN$=class{constructor(){this.B=this.time=this.mode=this.V=0;this.A=new TNQ(this);this.S=new TNQ(this);this.Z=[];this.clear()}clear(){this.B=this.time=this.mode=0;this.Z=[];this.reset()}reset(){this.mode=0;this.A.reset(0);this.S.reset(1)}},p6c=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],Xlr=class{constructor(){this.type=0}set(M){this.type=M}get(){return this.type}},jEJ=class{constructor(){this.state=this.P$=this.wp=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}S2(){return this.state!==0}matches(M,W){return this.S2()&&M===this.wp&&W===this.P$}},G65=class{constructor(){this.timestamp=this.Z=0}reset(){this.timestamp=
this.Z=0}},eb=class{constructor(M){this.S=M;this.B=[];this.Z=this.V=this.row=0;this.style=new Xlr;this.A=0;for(M=0;M<=15;M++){this.B[M]=[];for(let W=0;W<=32;W++)this.B[M][W]=new G65}}updateTime(M){for(let W=1;W<=15;++W)for(let b=1;b<=32;++b)this.B[W][b].timestamp=M}debugString(){let M="\n";for(let W=1;W<=15;++W){for(let b=1;b<=32;++b){const T=this.B[W][b];M=T.Z===0?M+"_":M+String.fromCharCode(T.Z)}M+="\n"}return M}reset(M){for(let W=0;W<=15;W++)for(let b=0;b<=32;b++)this.B[W][b].reset();this.A=M;
this.Z=0;this.V=this.row=1}},b3c=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],TvI=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],qUI=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,
194,199,200,202,203,235,206,207,239,212,217,249,219,171,187],Xb9=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],Vx4=class{constructor(M){this.B=M;this.S=0;this.style=new Xlr;this.C=new eb(this.B);this.W=new eb(this.B);this.text=new eb(this.B);this.V=this.C;this.A=this.W;this.Z=this.V}reset(M,W){this.S=W;this.style.set(2);this.V=this.C;this.A=this.W;this.Z=this.V;const b=(M<<2)+(W<<1);this.C.reset(b);this.W.reset(b);
this.text.reset((M<<2)+(W<<1)+1)}},TNQ=class{constructor(M){this.Z=M;this.S=0;this.B=new Vx4(this.Z);this.C=new Vx4(this.Z);this.V=new jEJ;this.A=this.B}reset(M){this.S=M;this.V.clear();this.A=this.B;this.B.reset(M,0);this.C.reset(M,1)}};var JlQ=class{A(){}};var Ch=class extends g.Ap{constructor(M,W,b,T,q,X=!1,G=null){super(M,M+W,{priority:b,namespace:"captions"});this.windowId=T;this.text=q;this.append=X;this.Z=G}toString(){return super.toString()}};var dg=class extends g.gz{reset(){}};var Kh=class extends g.Ap{constructor(M,W,b,T,q){super(M,M+W,{priority:b,namespace:"captions"});this.id=T;this.params=q;this.Z=[]}toString(){return super.toString()}},k8=0;var BN4=class extends dg{constructor(M){super();this.A=M;this.pens={};this.D={};this.X={};this.S="_"+k8++;this.W={};this.V=this.Z=null;this.C=!0}reset(){this.W={};this.V=this.Z=null;this.C=!0}B(M,W){M=M.firstChild;M.getAttribute("format");W=W||0;Number.isFinite(W);M=Array.from(M.childNodes);for(var b of M)if(b.nodeType===1)switch(b.tagName){case "head":var T=b;break;case "body":var q=b}if(T){T=Array.from(T.childNodes);for(var X of T)if(X.nodeType===1)switch(X.tagName){case "pen":b=X.getAttribute("id");
T=this.pens;M={};var G=X.getAttribute("p");G&&Object.assign(M,this.pens[G]);G=mY(X,"b");G!=null&&(M.bold=G);G=mY(X,"i");G!=null&&(M.italic=G);G=mY(X,"u");G!=null&&(M.underline=G);G=Lh(X,"et");G!=null&&(M.charEdgeStyle=G);G=Lh(X,"of");G!=null&&(M.offset=G);G=t_(X,"bc");G!=null&&(M.background=G);G=t_(X,"ec");G!=null&&(M.rj=G);G=t_(X,"fc");G!=null&&(M.color=G);G=Lh(X,"fs");G!=null&&G!==0&&(M.fontFamily=G);G=vq(X,"sz");G!==void 0&&(M.fontSizeIncrement=G/100-1);G=vq(X,"bo");G!==void 0&&(M.backgroundOpacity=
G/255);G=vq(X,"fo");G!==void 0&&(M.textOpacity=G/255);G=Lh(X,"rb");G!=null&&G!==10&&G!==0&&(M.gW=G>10?G-1:G);G=Lh(X,"hg");G!=null&&(M.IS=G);T[b]=M;break;case "ws":T=X.getAttribute("id");this.X[T]=Ex7(this,X);break;case "wp":T=X.getAttribute("id"),this.D[T]=nxE(this,X)}}if(q){X=[];q=Array.from(q.childNodes);for(l of q)if(l.nodeType===1)switch(l.tagName){case "w":this.Z=y6$(this,l,W,!1);(q=this.W[this.Z.id])&&q.end>this.Z.start&&(q.end=this.Z.start);this.W[this.Z.id]=this.Z;X.push(this.Z);break;case "p":var V=
l;M=W;q=[];T=V.getAttribute("w")||this.S;b=!!mY(V,"a");M=(vq(V,"t")||0)+M;G=vq(V,"d")||5E3;b||(!this.C&&this.V&&this.V.windowId===T&&this.V.end>M&&(this.V.end=M),this.V&&this.V.text==="\n"&&(this.V.text=""));const N=b?6:5;var J=V.getAttribute("p");J=J?this.pens[J]:null;const R=Array.from(V.childNodes);R.length&&(this.C=V.getAttribute("d")!=null);for(V=0;V<R.length;V++){var B=R[V],D=void 0;V>0&&(b=!0);let f;B.nodeType===1&&(f=B);if(f&&f.tagName==="s"){if((B=(B=f.getAttribute("p"))?this.pens[B]:null)&&
B.gW&&(B.gW===1?(B=R.slice(V,V+4),B.length===4&&(D=D_r(M,G,T,b,N,B,this.pens),V+=3)):D=D_r(M,G,T,b,N,[f],this.pens)),!D){var a=f;D=M;B=G;var E=T,n=b;const x=a.textContent?a.textContent:"";var C=a.getAttribute("p");C=C?this.pens[C]:null;a=vq(a,"t")||0;D=new Ch(D+a,B-a,N,E,x,n,C)}}else D=new Ch(M,G,N,T,B.textContent||"",b,J);q.push(D);this.V=D}if(q.length>0){q[0].windowId===this.S&&(this.Z=y6$(this,l,W,!0),X.push(this.Z));for(const f of q)f.windowId=this.Z.id,this.Z.Z.push(f),X.push(f)}}var l=X}else l=
[];return l}};var D6I=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),aVc=class extends dg{constructor(M){super();this.C=M;this.Z=new Map;this.A=new Map;this.S=new Map;this.V=new Map}reset(){this.V.clear()}B(M,W){M=JSON.parse(M);if(!M)return[];if(M.pens){var b=M.pens,T=0;for(var q of b){b={};var X=q.pParentId;X&&Object.assign(b,this.Z.get(X));q.bAttr&&(b.bold=!0);q.iAttr&&(b.italic=!0);q.uAttr&&(b.underline=!0);X=q.ofOffset;X!=null&&(b.offset=X);q.szPenSize!==void 0&&(b.fontSizeIncrement=q.szPenSize/100-1);
X=q.etEdgeType;X!=null&&(b.charEdgeStyle=X);q.ecEdgeColor!==void 0&&(b.rj=ZK(q.ecEdgeColor));X=q.fsFontStyle;X!=null&&X!==0&&(b.fontFamily=X);q.fcForeColor!==void 0&&(b.color=ZK(q.fcForeColor));q.foForeAlpha!==void 0&&(b.textOpacity=q.foForeAlpha/255);q.bcBackColor!==void 0&&(b.background=ZK(q.bcBackColor));q.boBackAlpha!==void 0&&(b.backgroundOpacity=q.boBackAlpha/255);(X=q.rbRuby)&&X!==10&&(b.gW=X>10?X-1:X,b.textEmphasis=D6I.get(b.gW));q.hgHorizGroup&&(b.IS=q.hgHorizGroup);this.Z.set(T++,b)}}if(M.wsWinStyles){T=
M.wsWinStyles;q=0;for(var G of T)T={},(b=G.wsParentId)?Object.assign(T,this.S.get(b)):Object.assign(T,this.C),G.mhModeHint!==void 0&&(T.Ou=G.mhModeHint),G.juJustifCode!==void 0&&(T.textAlign=G.juJustifCode),G.pdPrintDir!==void 0&&(T.mq=G.pdPrintDir),G.sdScrollDir!==void 0&&(T.G1=G.sdScrollDir),G.wfcWinFillColor!==void 0&&(T.windowColor=ZK(G.wfcWinFillColor)),G.wfoWinFillAlpha!==void 0&&(T.windowOpacity=G.wfoWinFillAlpha/255),this.S.set(q++,T)}if(M.wpWinPositions){q=M.wpWinPositions;G=0;for(var V of q)q=
{},(T=V.wpParentId)&&Object.assign(q,this.A.get(T)),V.ahHorPos!==void 0&&(q.BO=V.ahHorPos),V.apPoint!==void 0&&(q.Um=V.apPoint),V.avVerPos!==void 0&&(q.WM=V.avVerPos),V.ccCols!==void 0&&(q.IN=V.ccCols),V.rcRows!==void 0&&(q.mM=V.rcRows),this.A.set(G++,q)}if(M.events){M=M.events;V=[];for(const A of M)if(G=(A.tStartMs||0)+W,q=A.dDurationMs||0,A.id)T=String(A.id),M=U_I(this,A,G,q,T),V.push(M),this.V.set(T,M);else{A.wWinId?T=A.wWinId.toString():(T="_"+k8++,M=U_I(this,A,G,q,T),V.push(M),this.V.set(T,M));
M=V;var J=A;q===0&&(q=5E3);b=this.V.get(T);const qa=(X=!!J.aAppend)?6:5,Xs=J.segs;let uQ=null;J.pPenId&&(uQ=this.Z.get(J.pPenId));for(J=0;J<Xs.length;J++){var B=Xs[J],D=B.utf8;if(D){var a=B.tOffsetMs||0;let Lt=null;B.pPenId&&(Lt=this.Z.get(B.pPenId));if((b.params.Ou!=null?b.params.Ou:b.Z.length>1?1:0)===2&&X&&D==="\n")continue;B=null;var E=[],n;if(n=Lt&&Lt.gW===1)a:{n=Xs;var C=J;if(C+3>=n.length||!n[C+1].pPenId||!n[C+2].pPenId||!n[C+3].pPenId){n=!1;break a}var l=n[C+1].pPenId;(l=this.Z.get(l))&&l.gW&&
l.gW===2?(l=n[C+2].pPenId,l=this.Z.get(l),!l||!l.gW||l.gW<3?n=!1:(l=n[C+3].pPenId,n=(l=this.Z.get(l))&&l.gW&&l.gW===2?!0:!1)):n=!1}if(n)a=Xs[J+1].utf8,B=Xs[J+3].utf8,n=Xs[J+2].utf8,C=this.Z.get(Xs[J+2].pPenId),D=BvJ(D,a,n,B,C),B=new Ch(G,q,qa,T,D,X,Lt),J+=3;else{if(D.indexOf("<")>-1){E=Lt;n=uQ;C=G;l=q;var N=a,R=qa,f=X;const St=[];var x=g.UD(`<html>${D}</html>`);if(!x.getElementsByTagName("parsererror").length&&x.firstChild?.childNodes.length)for(const oJ of x.firstChild.childNodes){x=oJ.textContent?.replace(/\n/g,
"")??"";if(oJ.nodeType===3&&(!x||x.match(/^ *$/)!=null))continue;const NR={};Object.assign(NR,E||n);switch(oJ?.tagName){case "b":NR.bold=!0;break;case "i":NR.italic=!0;break;case "u":NR.underline=!0}St.push(new Ch(C+N,l-N,R,b.id,x,f,NR))}E=St}E.length||(E=[new Ch(G+a,q-a,qa,b.id,D,X,Lt||uQ)])}if(E.length)for(const St of E)M.push(St),b.Z.push(St);else B&&(M.push(B),b.Z.push(B))}X=!0}}W=V}else W=[];return W}};var Ey5=class extends g.iM{constructor(M,W,b){super(M);this.videoData=W;this.audioTrack=b;this.X=W.j$}A(M,W,b){xI$(this.videoData.videoId,M.vssId,b.Lq)}S(M){if(this.audioTrack)for(const W of this.audioTrack.captionTracks)g.ij(this.Z,W);M.ZJ()}};var gxJ=class extends Pq{constructor(M,W,b,T,q,X,G,V,J,B){super(M,W,b,T,q,X,G,V,J,B);this.type=1}Lp(M){const W=this.V.Z;super.Lp(M);let b,T;for(M=M.length;M<W.length;M++){const q=W[M];let X;T&&q.Z===b?X=T:(X={},Object.assign(X,q.Z),Object.assign(X,nyr),b=q.Z,T=X);w6J(this,q,X)}}},nyr={VR:!0};var C84=class extends JlQ{constructor(M,W){super();this.trackData=M;this.C=W;this.version=this.S=this.B=this.byteOffset=0;this.V=[];this.Z=new DataView(this.trackData)}A(M,W,b,T,q){if(b<T){const X="_"+k8++;b=b/1E3-this.C;T=T/1E3-this.C;M=new Kh(b,T-b,5,X,{textAlign:0,Um:0,BO:W*2.5,WM:M*5.33});q=new Ch(b,T-b,5,X,q);this.V.push(M);this.V.push(q)}}},yl7=class extends dg{constructor(M,W){super();this.V=M;this.A=W;this.track=this.A.languageName==="CC3"?4:0;this.Z=new qN$;this.Z.V=1<<this.track}B(M){M=
new C84(M,this.V);if(ksE(M)){for(;M.byteOffset<M.Z.byteLength;)for(M.version===0?M.B=N0(M)*(1E3/45):M.version===1&&(M.B=N0(M)*4294967296+N0(M)),M.S=Ia(M);M.S>0;M.S--){var W=Ia(M);const b=Ia(M),T=Ia(M);W&4&&(W&3)===this.track&&(this.track===0||this.track===1)&&(W=this.Z,W.Z.push({time:M.B,type:this.track,mI:b,w3:T,order:W.Z.length}))}W17(this.Z,M);return M.V}return[]}reset(){this.Z.clear()}};var sFc=class extends Pq{constructor(M,W,b,T,q,X,G,V,J,B){super(M,W,b,T,q,X,G,V,J,B);this.type=2;this.yz=[];this.Zs=this.O=this.MK=0;this.BY=NaN;this.FT=0;this.s2=null;this.Y9=new g.d9(this.EY,433,this);this.S&&(B.createClientVe(this.S,this,167342),this.J(this.S,"click",()=>{B.logClick(this.S)}),M=new g.C0(this.element,!0),g.t(this,M),M.subscribe("hoverstart",()=>{B.logVisibility(this.S,!0)},this));
g.pY(this.element,"ytp-caption-window-rollup");g.t(this,this.Y9);g.iq(this.element,"overflow","hidden")}WP(){g.oP(this.Y9)}EY(){this.element.removeEventListener("transitionend",this.EY,!1);g.Mw(this.element,"ytp-rollup-mode");this.D(this.s2,!0)}cP(){return this.A?this.Zs:this.O}fv(){return this.A?this.O:this.Zs}D(M,W){this.s2=M;if(this.V.params.mM){var b=0;for(let T=0;T<this.C.length&&b<M.length;T++)this.C[T]===M[b]&&b++;b>0&&b<M.length&&(M=this.C.concat(M.slice(b)));this.FT=this.Zs;this.O=this.Zs=
0;super.D(M);L14(this,W)}super.D(M)}};var U6Q=class{constructor(M,W,b,T){this.L=M;this.B=W;this.logger=b;this.Me=T;this.h5=[];this.Mw=[];this.Z=null;this.k9={p3K:()=>this.Z,
O1:()=>this.h5};
M=g.TO(this.L.G().experiments,"html5_override_micro_discontinuities_threshold_ms");this.V=M>0?M:10}unload(){this.Z!=null&&(this.L.removeEventListener("sabrCaptionsDataLoaded",this.Z),this.Z=null);this.h5=[];this.L.publish("sabrCaptionsBufferedRangesUpdated",this.h5)}bq(M){return{formatId:g.hE(M.info.Tv.info,this.Me),Kp:M.info.Kp+(this.Me?0:1),startTimeMs:M.info.A*1E3,durationMs:M.info.D*1E3}}};var CW7=class extends g.iM{constructor(M,W){super(W);this.V=M;this.L=W;this.logger=new g.uk("caps");this.D=this.gK=null;this.Zs=new U6Q(this.L,this,this.logger,this.V.Me)}A(M,W,b){this.B();W=M.getId();W=W!=null&&W in this.V.Z?this.V.Z[W]:null;W||(W=M.languageCode,W=this.V.isManifestless?I$r(this,W,"386"):I$r(this,W));W&&(this.D=M,this.gK=W,tv7(this.Zs,b),this.L.publish("sabrCaptionsTrackChanged",g.hE(W.info,this.V.Me)))}S(M){var W=this.V.isManifestless?NvB(this,"386"):NvB(this);for(const b of W)g.ij(this.Z,
b);M.ZJ()}B(){this.D&&(this.D=this.gK=null,this.Zs.unload(),this.L.publish("sabrCaptionsTrackChanged",null))}C(){return""}};var H3Q="WEBVTT".split("").map(M=>M.charCodeAt(0)),i3$=class extends dg{constructor(){super()}B(M,W){M instanceof ArrayBuffer&&(M=g.La(new Uint8Array(M)));
const b=[];M=M.split(k6r);for(let C=1;C<M.length;C++){var T=M[C],q=W;if(T!==""&&!K2p.test(T)){var X=oa.exec(T);if(X&&X.length>=4){var G=Hq(X[1]),V=Hq(X[2])-G;G+=q;var J=(X=X[3])?X.split(" "):[];X={};var B=null;var D="";var a=null,E="";for(const l of J){J=l.split(":");if(J.length!==2)continue;var n=J[1];switch(J[0]){case "line":J=n.split(",");J[0].endsWith("%")&&(B=J[0],X.WM=Number.parseInt(B,10),J.length===2&&(D=J[1].trim()));break;case "position":J=n.split(",");a=J[0];X.BO=Number.parseInt(a,10);
J.length===2&&(E=J[1].trim());break;case "align":switch(n){case "start":X.textAlign=0;break;case "middle":X.textAlign=2;break;case "end":X.textAlign=1}}}B||D||(D="end");if(!a)switch(X.textAlign){case 0:X.BO=0;break;case 1:X.BO=100;break;case 2:X.BO=50}if(X.textAlign!=null){B=0;switch(D){case "center":B+=3;break;case "end":B+=6;break;default:B+=0}switch(E){case "line-left":B+=0;break;case "center":B+=1;break;case "line-right":B+=2;break;default:switch(X.textAlign){case 0:B+=0;break;case 2:B+=1;break;
case 1:B+=2}}D=B<0||B>8?7:B;X.Um=D}T=T.substring(oa.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");E=X;X=T;T={};if(X.indexOf("<")<0&&X.indexOf("&")<0)q=RE7(G,V,5,E),V=new Ch(G,V,5,q.id,X,!1,g.P$(T)?void 0:T),b.push(q),b.push(V),q.Z.push(V);else for(D=X.split(vyc),D.length===1?(X=5,E=RE7(G,V,X,E)):(B=X=6,E=Object.assign({IN:32},E),E=new Kh(G,V,B,"_"+k8++,E)),b.push(E),B=G,a=0;a<D.length;a++)if(J=D[a],a%2===0){n=g.UD(`<html>${J}</html>`);let l;n.getElementsByTagName("parsererror").length?(l=n.createElement("span"),
l.appendChild(n.createTextNode(J))):l=n.firstChild;r6r(this,B,V-(B-G),X,E,a>0,l,T,b)}else B=Hq(J)+q}oa.lastIndex=0}}return b}},K2p=/^NOTE/,k6r=/(?:\r\n|\r|\n){2,}/,oa=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),vyc=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var m6r=class extends g.gz{constructor(M,W){super();this.L=M;this.uV=W;this.Z=null;this.Cv=this.L.Tl();this.logger=new g.uk("caps")}clear(){this.Z&&this.Z.dispose();this.Z=null}reset(){this.Z&&this.Z.reset()}vY(){super.vY();this.clear()}};var fh={windowColor:"#080808",windowOpacity:0,textAlign:2,Um:7,BO:50,WM:100,isDefault:!0,qa:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.FQ("captions",class extends g.F2{constructor(M){super(M);this.L=M;this.BY=[];this.Zs={};this.MK={};this.W=!1;this.B="NONE";this.V=this.X=this.gK=this.xk=this.Ds=null;this.XX={ZJ:()=>{this.ZJ()},
Lq:(T,q,X,G,V=0)=>{const J=Number(this.videoData.G().hT().Z.UY(g.CMQ)??0);V>0&&J>0&&this.videoData.lengthSeconds>0&&V/this.videoData.lengthSeconds>J?this.L.dK("tts",{dropcap:V}):this.Lq(T,q,X,G)}};
this.Z=null;this.uV=this.L.G();this.videoData=this.L.getVideoData();this.bV=this.L.qe();this.S={qa:{}};this.C={qa:{}};this.videoData.cP()?this.B="OFFLINE":g.lvq(this.videoData,this.L)?this.B="HLS":Z37(this.videoData,this.L)?this.B="SABR_LIVE":g.tBG(this.videoData,this.L)?this.B="LIVE":this.videoData.captionTracks.length?this.B="INNERTUBE":this.videoData.oT&&(this.B="TTS");this.Lp=this.uV.controlsType==="3";this.jT=new m6r(this.L,this.uV);this.sY=new g.Cq(this);this.D=new g.w({K:"div",N:"ytp-caption-window-container",
Y:{id:"ytp-caption-window-container"}});this.O={top:0,right:0,bottom:0,left:0,width:1,height:1};let W=null;const b=g.us("yt-html5-player-modules::subtitlesModuleData");b&&(W=new g.tt(b));this.storage=W;this.EY=!!M.E2()?.yz();this.A=zE4(this);this.yz=!this.A&&this.Lp&&this.EY&&(this.B==="LIVE"||this.B==="SABR_LIVE");g.t(this,this.jT);this.A?this.An=this.lV=null:(this.lV=new g.O9(this.vP,void 0,this),g.t(this,this.lV),this.An=new g.d9(this.WP,2E3,this),g.t(this,this.An));g.t(this,this.sY);g.Im(this.player,
this.D.element,4);g.t(this,this.D);this.A||this.sY.J(M,"resize",this.OY);(this.d9=g.bb(this.uV)&&!g.OL()&&!this.L.isFullscreen()&&!this.A&&!this.yz)&&this.sY.J(M,"resize",this.cP);this.sY.J(M,"onPlaybackAudioChange",this.oT);this.sY.J(M,g.kJ("captions"),T=>{this.onCueRangeEnter(T)});
this.sY.J(M,g.KX("captions"),T=>{this.onCueRangeExit(T)});
Ra(this,J_()||{});g.Vc(this.player,"onCaptionsModuleAvailable");this.B==="HLS"&&this.A&&(M=this.L.E2().BP(),this.EY&&this.sY.J(M.textTracks,"addtrack",this.fv))}vY(){if(this.A||this.yz){const M=this.L.E2();M&&!M.ST()&&M.W()}else rg(this,!1);super.vY()}rR(){return this.uV.j("html5_honor_caption_availabilities_in_audio_track")&&this.B!=="LIVE"&&this.B!=="SABR_LIVE"}Wi(){if(this.Lp)return this.A||this.yz;if(this.B==="HLS")return this.A;var M=this.getAudioTrack();if(this.rR()){if(!M.captionTracks.length)return!1;
if(!this.V)return!0}M=Ge(M,g.Zk(this.uV));return M==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:M==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?F_(this):x8(this)||F_(this)?!0:O3c(this)}load(){super.load();this.X=this.getAudioTrack();if(this.V)this.Z&&(this.jT.clear(),this.A?P8r(this,!0):this.player.getPresentingPlayerType()!==3&&this.V.A(this.Z,"json3",this.XX),this.B!=="HLS"&&this.A||this.yz||i$(this)||g.Vc(this.player,"captionschanged",g.rL(this.Z)));else{let M;this.B==="OFFLINE"?M=new Ey5(this.player,this.videoData,
this.getAudioTrack()):this.B==="SABR_LIVE"?M=new CW7(this.videoData.Z,this.player):this.B==="HLS"?M=new YUh(this.player):this.B==="LIVE"?M=new W2r(this.videoData.Z,this.player):this.B==="INNERTUBE"?M=new g.h0(this.player,this.videoData,this.getAudioTrack()):M=new g.A0(this.player,this.videoData.oT,this.videoData.videoId,g.DmJ(this.videoData),this.videoData.Px,this.videoData.eventId);this.V=M;g.t(this,this.V);this.V.S(this.XX)}}unload(){this.A&&this.Z?P8r(this,!1):(this.An&&this.An.n3(),this.player.lN("captions"),
this.BY=[],this.V&&this.V.B(),this.jT.clear(),this.gK&&this.player.QV(this.gK),this.OY());super.unload();this.player.Fn();g.Vc(this.player,"captionschanged",{})}create(){this.Wi()&&this.load();var M;a:{if(this.uV.j("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(M=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(const W of M)if(W.kind==="asr"&&W.languageCode===
"en"){M=!0;break a}M=!1}M&&this.L.publish("showpromotooltip",this.D.element)}ZJ(){var M=Ge(this.player.getAudioTrack(),g.Zk(this.uV));var W=M==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?A_(this,this.W):M==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&F_(this)?h_(this):x8(this)||this.W||O3c(this)?A_(this,this.W):F_(this)?h_(this):null;if(this.B!=="HLS"&&this.A||this.yz){const b=g.nk(this.V.Z,!0);M=[];for(let T=0;T<b.length;T++){const q=b[T],X=g.Gr("TRACK");X.setAttribute("kind","subtitles");X.setAttribute("label",
g.RU(q));X.setAttribute("srclang",g.xj(q));X.setAttribute("id",q.toString());this.yz||X.setAttribute("src",this.V.C(q,"vtt"));q===W&&X.setAttribute("default","1");M.push(X)}W=this.L.E2();W.gK(M);M=W.BP();this.EY&&this.sY.J(M.textTracks,"change",this.FT)}else!this.Z&&W&&OC(this,W),g.Vc(this.player,"onCaptionsTrackListChanged"),g.Jp(this.player,"onApiChange")}getTrackById(M){const W=g.nk(this.V.Z,!0);for(let b=0;b<W.length;b++)if(W[b].toString()===M)return W[b];return null}FT(){const M=this.L.E2().BP().textTracks;
let W=null;for(let b=0;b<M.length;b++)M[b].mode==="showing"&&(W=this.getTrackById(M[b].id));(this.loaded?this.Z:null)!==W&&OC(this,W,!0)}fv(){this.V?.S(this.XX)}eM(){!this.Z&&this.A||this.unload()}Lq(M,W,b,T){if(M){Sb(this,this.Z??void 0);this.V.O()&&(this.BY=[],this.L.lN("captions"),jb(this.lV),this.jT.reset());a:{var q=this.jT;T=T||0;b=F1r(q,M,b||0);M=[];try{for(const R of b){const f=R.trackData,x=R.GG,A=q.uV.j("safari_live_drm_captions_fix");if(typeof f!=="string"){b=M;var X=b.concat;if(A&&f$V(f))var G=
hEA(q,f,x);else{var V=q,J=W,B=f,D=x,a=T;if(!K1p(B))throw Error("Invalid binary caption track data");V.Z||(V.Z=new yl7(a,J));G=V.Z.B(B,D)}var E=X.call(b,G)}else{if(f.substring(0,6)==="WEBVTT")var n=M.concat(hEA(q,f,x));else{b=M;var C=b.concat;b:{J=q;V=W;if(f[0]==="{")try{J.Z||(J.Z=new aVc(A6h(V)));var l=J.Z.B(f,x);break b}catch(uQ){g.O(uQ);l=[];break b}const qa=g.UD(f);if(!qa||!qa.firstChild){const uQ=Error("Invalid caption track data");uQ.params=f;throw uQ;}if(qa.firstChild.tagName==="timedtext"){if(Number(qa.firstChild.getAttribute("format"))===
3){B=qa;J.Z||(J.Z=new BN4(A6h(V)));l=J.Z.B(B,x);break b}const uQ=Error("Unsupported subtitles format in web player (Format2)");uQ.params=f;throw uQ;}if(qa.firstChild.tagName==="transcript"){const uQ=Error("Unsupported subtitles format in web player (Format1)");uQ.params=f;throw uQ;}const Xs=Error("Invalid caption track data");Xs.params=f;throw Xs;}n=C.call(b,l)}E=n}M=E}var N=M;break a}catch(R){g.SV(q.logger,187101178,`Captions parsing failed: ${R.message}. `);q.clear();N=[];break a}N=void 0}W=N;W.length>
0&&(N=this.Z,this.Ts(N,!!N,i$(this)?"g":this.W?"m":"s"));this.player.QV(W,void 0,this.B==="LIVE"||this.B==="SABR_LIVE");!this.W||this.yz||i$(this)||g.XD(this.uV)||g.WQ(this.uV)||g.dB(this.uV)||this.uV.Zs==="shortspage"||this.player.isInline()||(this.An.n3(),W=a$E({Um:0,BO:5,WM:5,mM:2,textAlign:0,mq:0,lang:"en-GB"}),this.xk=[W],N=["Click "," for settings"],this.Ds||(q=new g.ig(g.Lu()),g.t(this,q),this.Ds=q.element),q=W.end-W.start,(E=g.RU(this.Z))&&this.xk.push(new Ch(W.start,q,0,W.id,E)),this.xk.push(new Ch(W.start,
q,0,W.id,N[0]),new Ch(W.start,q,0,W.id,this.Ds,!0),new Ch(W.start,q,0,W.id,N[1],!0)),this.player.QV(this.xk),this.An.Wr());!this.W||this.yz||i$(this)||(g.Zk(this.uV)?ze(this,!0):u$(this,!0),this.X&&(this.X.A=this.Z),this.player.Fn());this.W=!1}}onCueRangeEnter(M){this.BY.push(M);jb(this.lV)}onCueRangeExit(M){g.X9(this.BY,M);this.V instanceof W2r&&this.V.Zs&&this.player.Ng([M]);jb(this.lV)}getCaptionWindowContainerId(){return this.D.element.id}WP(){uWV(this,this.xk);this.xk=null}vP(){if(!this.d9||
!this.A){this.lV.stop();g.ep(this.MK);this.BY.sort(g.CX);var M=this.BY;if(this.gK){const W=g.et(M,function(b){return this.gK.indexOf(b)===-1},this);
W.length&&(M=W)}for(const W of M)W instanceof Kh?ox9(this,W):c6$(this,W);for(const [W,b]of Object.entries(this.Zs)){const T=W,q=b;this.MK[T]?(q.element.parentNode||(q instanceof sFc||q instanceof gxJ||g.RQ(this.Zs,(X,G)=>{G!==T&&X.V.params.Um===q.V.params.Um&&X.V.params.BO===q.V.params.BO&&X.V.params.WM===q.V.params.WM&&(X.dispose(),delete this.Zs[G]);return G===T},this),this.D.element.appendChild(q.element)),q.D(this.MK[T])):(q.dispose(),delete this.Zs[T])}}}JY(){Ra(this,{},!0);
g.Vc(this.player,"captionssettingschanged")}bB(){var M=fh.qa;M={background:M.background,backgroundOpacity:M.backgroundOpacity,charEdgeStyle:M.charEdgeStyle,color:M.color,fontFamily:M.fontFamily,fontSizeIncrement:M.fontSizeIncrement,fontStyle:M.bold&&M.italic?3:M.bold?1:M.italic?2:0,textOpacity:M.textOpacity,windowColor:fh.windowColor,windowOpacity:fh.windowOpacity};const W=J_()||{};W.background!=null&&(M.background=W.background);W.backgroundOverride!=null&&(M.backgroundOverride=W.backgroundOverride);
W.backgroundOpacity!=null&&(M.backgroundOpacity=W.backgroundOpacity);W.backgroundOpacityOverride!=null&&(M.backgroundOpacityOverride=W.backgroundOpacityOverride);W.charEdgeStyle!=null&&(M.charEdgeStyle=W.charEdgeStyle);W.charEdgeStyleOverride!=null&&(M.charEdgeStyleOverride=W.charEdgeStyleOverride);W.color!=null&&(M.color=W.color);W.colorOverride!=null&&(M.colorOverride=W.colorOverride);W.fontFamily!=null&&(M.fontFamily=W.fontFamily);W.fontFamilyOverride!=null&&(M.fontFamilyOverride=W.fontFamilyOverride);
W.fontSizeIncrement!=null&&(M.fontSizeIncrement=W.fontSizeIncrement);W.fontSizeIncrementOverride!=null&&(M.fontSizeIncrementOverride=W.fontSizeIncrementOverride);W.fontStyle!=null&&(M.fontStyle=W.fontStyle);W.fontStyleOverride!=null&&(M.fontStyleOverride=W.fontStyleOverride);W.textOpacity!=null&&(M.textOpacity=W.textOpacity);W.textOpacityOverride!=null&&(M.textOpacityOverride=W.textOpacityOverride);W.windowColor!=null&&(M.windowColor=W.windowColor);W.windowColorOverride!=null&&(M.windowColorOverride=
W.windowColorOverride);W.windowOpacity!=null&&(M.windowOpacity=W.windowOpacity);W.windowOpacityOverride!=null&&(M.windowOpacityOverride=W.windowOpacityOverride);return M}Qd(M,W){const b={};Object.assign(b,J_());Object.assign(b,M);Ra(this,b,W);g.Vc(this.player,"captionssettingschanged")}OY(){!this.A&&this.loaded&&(g.NE(this.Zs,function(M,W){M.dispose();delete this.Zs[W]},this),this.vP())}nK(M,W){switch(M){case "fontSize":if(isNaN(W))break;
M=g.fy(W,-2,4);this.Qd({fontSizeIncrement:M});return M;case "reload":W&&!this.A&&OC(this,this.Z,!0);break;case "stickyLoading":W!==void 0&&this.uV.D&&(g.Zk(this.uV)?ze(this,!!W):u$(this,!!W));break;case "track":return wbA(this,W);case "tracklist":return this.V?g.dG(g.nk(this.V.Z,!(!W||!W.includeAsr)),b=>g.rL(b)):[];
case "translationLanguages":return this.V?this.V.X.map(b=>Object.assign({},b)):[];
case "sampleSubtitles":this.A||W===void 0||rg(this,!!W);break;case "sampleSubtitlesCustomized":this.A||rg(this,!!W,W);break;case "recommendedTranslationLanguages":return g.Ic();case "defaultTranslationSourceTrackIndices":return this.V?this.V.sY:[]}}getOptions(){const M="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.uV.D&&M.push("stickyLoading");return M}Jv(){let M=this.Z;if(this.L.rr("captions")){if(this.uV.j("html5_modify_caption_vss_logging"))return(M=this.videoData.fH??
null)?{cc:g.Wkt(M)}:{};if(M){let W=M.vssId;M.translationLanguage&&W&&(W=`t${W}.${g.xj(M)}`);return{cc:W}}}return{}}Lk(){this.isSubtitlesOn()?(g.Zk(this.uV)?ze(this,!1):u$(this,!1),Sb(this),OC(this,null,!0)):this.wH()}wH(){const M=i$(this)||!this.Z?A_(this,!0):this.Z;M&&this.zs(M.vssId,"m");this.isSubtitlesOn()||OC(this,i$(this)||!this.Z?A_(this,!0):this.Z,!0)}isSubtitlesOn(){return!!this.loaded&&!!this.Z&&!i$(this)}oT(){const M=i$(this);F_(this,M)?OC(this,this.getAudioTrack().Z,!1):this.videoData.captionTracks.length&&
(this.loaded&&this.unload(),this.rR()&&(this.W=!1,this.Z=null,this.V&&(this.V.dispose(),this.V=null)),this.Wi()&&(M?OC(this,A_(this,!1),!1):this.load()))}ZX(M){M&&(this.O={top:M.top,right:M.right,bottom:M.bottom,left:M.left,width:1-M.left-M.right,height:1-M.top-M.bottom},this.D.element.style.top=`${this.O.top*100}%`,this.D.element.style.left=`${this.O.left*100}%`,this.D.element.style.width=`${this.O.width*100}%`,this.D.element.style.height=`${this.O.height*100}%`,this.D.element.style.position="absolute",
M=QFr(this))&&(this.D.element.style.width=`${M.width}px`,this.D.element.style.height=`${M.height}px`)}onVideoDataChange(M,W){M==="newdata"&&(this.videoData=W,this.loaded&&this.unload(),this.W=!1,this.Z=null,this.V&&(this.V.dispose(),this.V=null,g.Vc(this.player,"captionschanged",{})),this.Wi()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}cP(){const M=this.L.E2();M&&!M.ST()&&M.W();this.L.isFullscreen()?(this.A=this.Lp=!0,this.loaded&&this.ZJ()):(this.Lp=this.uV.controlsType==="3",
this.A=zE4(this));OC(this,this.Z)}wK(){const M=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;M&&g.q8(this.player,"innertubeCommand",M)}Ts(M,W,b){const T=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm;let q="";M&&(q=M.vssId,q=q.replace(T,""));let X="";M&&M.getId()&&(X=M.getId()||"");M&&M.getXtags()&&(M=M.getXtags(),M=M.replace(T,""),X=X.concat(`;${M}`));this.B==="HLS"&&(X="");this.L.Ts(W?q:"",W?X:"",b)}zs(M,W){M=(M||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,
"");M.length>0&&this.L.zs(M,W)}});})(_yt_player);
