(function(g){var window=this;'use strict';var yj=function(M,W){if(!Number.isFinite(M))return String(M);M=String(M);let b=M.indexOf(".");b===-1&&(b=M.length);const T=M[0]==="-"?"-":"";T&&(M=M.substring(1));W="0".repeat(Math.max(0,W-b));return T+W+M},C8=function(M){typeof M==="number"?(this.date=jxA(M,0,1),Uv(this,1)):g.lQ(M)?(this.date=jxA(M.getFullYear(),M.getMonth(),M.getDate()),Uv(this,M.getDate())):(this.date=new Date(g.Hy()),M=this.date.getDate(),this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),
Uv(this,M))},jxA=function(M,W,b){W=new Date(M,W,b);
M>=0&&M<100&&W.setFullYear(W.getFullYear()-1900);return W},Uv=function(M,W){M.getDate()!=W&&M.date.setUTCHours(M.date.getUTCHours()+(M.getDate()<W?1:-1))},kL=function(M){if(M.toggleButtonRenderer){var W=M.toggleButtonRenderer;
if(W.isToggled){var b=W.toggledText?g.Ga(W.toggledText):"";M.update({text:b,icon:GJE(W.toggledIcon)})}else b=W.defaultText?g.Ga(W.defaultText):"",M.update({text:b,icon:GJE(W.defaultIcon)});M.show()}else M.hide()},VaI=function(M,W){!M.toggleButtonRenderer&&W&&W.toggleButtonRenderer?M.toggleButtonRenderer=W.toggleButtonRenderer:W&&W.toggleButtonRenderer||(M.toggleButtonRenderer=null);
kL(M)},GJE=function(M){if(!M)return null;
switch(M.iconType){case "NOTIFICATIONS":return{K:"svg",Y:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},U:[{K:"path",Y:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]};case "NOTIFICATIONS_NONE":return{K:"svg",Y:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},U:[{K:"path",Y:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]};
case "NOTIFICATIONS_ACTIVE":return g.XIy();default:return null}},a6r=function(M,W){const b=g.z(W,JKh),T=g.z(W,Bb9);
if(W&&(b||T)){if(b){var q=b;var X="notification/add_upcoming_event_reminder"}else T&&(q=T,X="notification/remove_upcoming_event_reminder");X&&q&&q.params&&DxA(M,X,q.params)}},DxA=function(M,W,b){M.Z||(M.Z=new g.GF(M.L.G().vg));
const T={context:g.ni(M.Z.config_||g.Ei())};g.nT()&&(T.context.clientScreenNonce=g.nT());T.params=b;g.Q7(M.Z,W,T,{timeout:5E3,onError:()=>{Eq9(M)},
onTimeout:()=>{Eq9(M)}})},Eq9=function(M){M.toggleButtonRenderer&&(M.toggleButtonRenderer.isToggled=!M.toggleButtonRenderer.isToggled,kL(M))},K8=function(M,W,b){if(W){var T=W.subtitleText!=null?g.Ga(W.subtitleText):"";
b=b?b:W.mainText!=null?g.Ga(W.mainText):"";M.update({mainText:b,subtitleText:T,label:W.mainText?.accessibility?.accessibilityData?.label??b});g.H(M.element,"ytp-offline-slate-single-text-line",!T);g.H(M.B,"ytp-offline-slate-bar-hidden",!b&&!T)}},nqc=function(M){try{const W=JSON.parse(M);
return W!=null?W:void 0}catch(W){}},KX$=async function(M){const W=M.player.G(),b=M.getVideoData();
vz(M)&&(yKQ(M)?Uxh(M,W,b):(CX9(M),await kJE(M,W,b)))},CX9=function(M){var W=M.getVideoData();
if(W.KI)if(W.j("use_rta_for_player"))M.attestationResponse=vqJ(M);else{const X=new g.g1l(W);if(g.$b.isInitialized()||M.sequenceNumber>=3){W=Promise;var b=W.resolve;let G=null;if(X.videoData.im){var T=g.zYL(X);if(T){G={};const V={};T=T.split("&");for(q of T)T=q.split("="),T.length===2&&(V[T[0]]=T[1]);var q=V;q.r1a&&(G.webResponse=q.r1a);q.r1c&&(G.error=mxh[Number(q.r1c)]);G.challenge=X.videoData.im}}M.attestationResponse=b.call(W,G||void 0)}}},taQ=function(M){var W=M.getVideoData();
const b=M.player.G();if(W.isLivePlayback)if(g.gp(b.S)){M.A=!0;M.W=!0;if(!g.XD(b)||g.Tb(b))M.offlineSlate=new LXV(M.player),g.t(M,M.offlineSlate),g.Im(M.player,M.offlineSlate.element,4);(W=W.getPlayerResponse())&&W.playabilityStatus&&(M.Z=W.playabilityStatus);M.Z?.status!=="UNPLAYABLE"&&(M.Z?(W=l6Q(void 0,M.Z.liveStreamability&&M.Z.liveStreamability.liveStreamabilityRenderer))?mv(M,W):mv(M,7500):mv(M,L8(M,!0)))}else M.player.J1("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.ME(W.jG,"heartbeat")&&M.player.Vs("heartbeat",M.getPlayerType())},I6$=function(M,W,b){var T=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,q=!(!T||!(T.switchStreamsImmediately||T.transitionTiming&&T.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
W=l6Q(W,T);var X=M.getVideoData();const G=M.player.getPlayerStateObject(M.getPlayerType()),V=G.isPlaying()&&!g.PM(X)&&!M.player.isAtLiveHead(M.getPlayerType());if(X.G().jW()){var J=M.player.E2()?.qd()||{};J.status=b.status||"";J.dvr=`${+V}`;J["switch"]=`${+q}`;J.ended=`${+!(!T||!T.displayEndscreen)}`;M.player.dK("heartbeat",J)}J=T&&T.broadcastId;const B=M.Z&&M.Z.liveStreamability&&M.Z.liveStreamability.liveStreamabilityRenderer&&M.Z.liveStreamability.liveStreamabilityRenderer.broadcastId,D=J!==B&&
J!=null;D&&M.player.dK("lbidh",{broadcastId:J},!0);const a=X.G();if(g.XD(a)&&T&&T.streamTransitionEndpoint){var E=g.z(T.streamTransitionEndpoint,g.Sw)?.commands||[];for(var n of E)if(g.z(n,g.ub)?.signal==="RELOAD_PLAYER"){M.player.J1("qoe.restart",1,void 0,"sa.reload","7");break}}n=M.player.j("always_cache_redirect_endpoint");if(V&&!q&&!n)return W;E=T&&T.streamTransitionEndpoint&&g.z(T.streamTransitionEndpoint,g.Jj);const C=T&&T.transitionTiming;if(C==="STREAM_TRANSITION_TIMING_AT_STREAM_END")M.getVideoData().transitionEndpointAtEndOfStream=
E;else if(a.hT().Z.UY(g.Gog)){if(E&&lc(M,E,b))return W;n&&!E&&M.getVideoData().transitionEndpointAtEndOfStream&&(M.getVideoData().transitionEndpointAtEndOfStream=void 0)}else if(n&&!E&&M.getVideoData().transitionEndpointAtEndOfStream)M.getVideoData().transitionEndpointAtEndOfStream=void 0;else if(!n&&E&&lc(M,E,b))return W;if(V&&!q&&n||n&&E&&(C==="STREAM_TRANSITION_TIMING_IMMEDIATELY"||C==="STREAM_TRANSITION_TIMING_UNSPECIFIED")&&lc(M,E,b))return W;if(b.status.toUpperCase()==="OK"){if(!g.jn(X)||D)return T=
{video_id:X.videoId},X.Xn&&(T.is_live_destination="1"),T.disable_watch_next=!0,T.raw_watch_next_response=X.getWatchNextResponse(),T.autonav_state=X.autonavState,T.oauth_token=X.oauthToken,T.Pc=X.Pc,X.ll&&(T.vss_credentials_token=X.ll,T.vss_credentials_token_type=X.C4),X.Zs&&(T.vvt=X.Zs),q=void 0,g.jn(X)?D&&(q=new Z7p("broadcastIdChanged",`${B},${J}`),M.zX("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(J&&(q=new Z7p("formatsReceived",`${J}`)),M.zX("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE",
"HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b)),D&&M.player.dK("lbidr",{broadcastId:J}),M.player.loadVideoByPlayerVars(T,void 0,void 0,void 0,q),W;M.player.Vs("heartbeat",M.getPlayerType())}T&&T.displayEndscreen&&(M.offlineSlate?(M=M.offlineSlate,M.C=!0,M.Ta&&M.api.NC()):G.isBuffering()&&(X=M.player.E2()?.qd()||{},M.player.dK("hbse",X,!0),M.player.NC(!0,"h"),g.q8(M.player,"onLiveMediaEnded",b)));return W},L8=function(M,W=!1){M=M.getVideoData();
return M.j("html5_use_server_init_heartbeat_delay")?isNaN(M.QG)?15E3:M.QG:W?1E3:2E3},Nb4=function(M){var W=M.getVideoData();
!W.j("use_rta_for_player")&&W.KI&&(W=W.botguardData)&&g.bu(W,M.player.G())},tU=function(M){M.D=0;
M.V.stop();M.S=!1;M.sequenceNumber=0},vqJ=async function(M){if(await g.wsL())return M=M.getVideoData(),g.skq({cpn:M.clientPlaybackNonce,
encryptedVideoId:M.videoId||""},1500);if(M.sequenceNumber>=3)return{error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}},mv=function(M,W){if(!M.V.isActive()&&M.W){var b=M.getVideoData();
if(Z1(M)||b.isLivePlayback)W===void 0&&(W=M.S?M.A?7500:M.heartbeatParams?.interval?M.heartbeatParams.interval*1E3:M.getVideoData().QG||6E4:1E3),M.V.start(W)}},yKQ=function(M){var W=M.getVideoData();
if(!g.z7(M.getVideoData())||W.Lb)return!1;if(W.S){M=W.S.flavor==="playready";const b=W.S.flavor==="widevine"&&W.j("html5_innertube_heartbeats_for_widevine");W=g.S0(W.S)&&W.j("html5_innertube_heartbeats_for_fairplay");return!(M||b||W)}return!0},Z1=function(M){if(yKQ(M))return!!M.heartbeatParams;
const W=M.getVideoData();return!g.z7(M.getVideoData())||W.Qu||W.Vu?!!W.heartbeatToken:!1},Ry7=function(M,W,b){W.bS&&(b=g.JM(b,{internalipoverride:W.bS}));
const T={cpn:W.clientPlaybackNonce};W.contextParams&&(T.context_params=W.contextParams);W.EY&&(T.kpt=W.EY);b=g.JM(b,T);g.Pe(b,{format:"RAW",method:"GET",timeout:3E4,onSuccess:q=>{if(!M.V.isActive()&&vz(M)){M.C.reset();M.sequenceNumber++;q=q.responseText;var X=nqc(q);if(X){g.q8(M.player,"onHeartbeat",X);var G=X.status==="ok"?X.stop_heartbeat?2:0:X.status==="stop"?1:X.status==="live_stream_offline"?0:-1}else G=(G=q.match(H7h))?G[1]==="0"?0:1:-1;f69(M,void 0,X,q,G)}},
onError:q=>{vz(M)&&IT(M,!0,`net-${q.status}`)},
onTimeout:()=>{vz(M)&&IT(M,!0,"timeout")},
withCredentials:!0})},vz=function(M){const W=M.getVideoData();
return M.player.getPresentingPlayerType()===3||!M.player.G().experiments.hT().Z.UY(g.u2y)&&M.player.getPlayerStateObject(M.getPlayerType()).Z(4)?!1:Z1(M)||W.isLivePlayback?!0:(tU(M),!1)},Uxh=function(M,W,b){if(M.heartbeatParams?.url){var T=g.JM(M.heartbeatParams.url,{request_id:g.F$Q()});
b.Zs&&(T=g.JM(T,{vvt:b.Zs}),b.mdxEnvironment&&(T=g.JM(T,{mdx_environment:b.mdxEnvironment})));g.ZI(W,b.oauthToken).then(q=>{q&&(T=g.JM(T,{access_token:q}));Ry7(M,b,T)})}},kJE=async function(M,W,b){const T={videoId:b.videoId,
sequenceNumber:M.sequenceNumber,heartbeatServerData:M.sY??b.heartbeatServerData};M.X=M.attestationResponse;b.KI&&(T.attestationResponse=await M.X);var q=g.LT(b),X=q.client??{};X.utcOffsetMinutes=M.utcOffsetMinutes;T.context=q;T.cpn=b.clientPlaybackNonce;if(q=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)X.timeZone=q;X={heartbeatChecks:[]};if(q=b.getPlayerResponse())b.heartbeatToken&&(T.heartbeatToken=b.heartbeatToken),(q=q.playabilityStatus)&&(q=q.liveStreamability)&&
q.liveStreamabilityRenderer&&X.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");b.heartbeatToken&&X.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.Tb(W)){X.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");var G=rKV(M);q={};G!==null&&(q.clientPlayerPositionUtcMillis=G);G=M.player.lk()?.EL()?.Jx()||0;G>0&&(q.freePreviewWatchedDuration={seconds:`${G}`});X.unpluggedParams=q}T.heartbeatRequestParams=X;b.isLivePlayback?(X=rKV(M),X!==null&&(T.playbackState||(T.playbackState={}),
T.playbackState.playbackPosition={utcTimeMillis:X})):W.j("enable_heartbeat_vod_playback_position")&&(X=xxh(M),X!==null&&(T.playbackState||(T.playbackState={}),T.playbackState.playbackPosition={streamTimeMillis:X}));M.player.publish("heartbeatRequest",T);const V={timeout:3E4,onSuccess:J=>{if(!M.V.isActive()&&vz(M)){var B=M.getVideoData(),D=B.KI&&M.X==null;B.KI=!!J.heartbeatAttestationConfig?.requiresAttestation||D;D=J.playabilityStatus;var a=JSON.stringify(D)||"{}";J.authenticationMismatch&&M.player.dK("authshear",
{});var E=-1;var n=J.playabilityStatus;n&&(g.q8(M.player,"onHeartbeat",n),n.status==="OK"?E=J.stopHeartbeat?2:0:n.status==="UNPLAYABLE"?E=1:n.status==="LIVE_STREAM_OFFLINE"&&(E=0));M.sequenceNumber&&E===-1||M.C.reset();M.sequenceNumber++;J.heartbeatServerData&&(M.sY=J.heartbeatServerData);B.IG=J;(n=J.playerCueRangeSet)&&g.BM(B,n);J.playerCueRanges&&J.playerCueRanges.length>0&&(B.cueRanges=J.playerCueRanges);J.progressBarConfig?.progressBarStartPosition&&J.progressBarConfig?.progressBarEndPosition&&
(B.progressBarStartPosition=J.progressBarConfig.progressBarStartPosition,B.progressBarEndPosition=J.progressBarConfig.progressBarEndPosition);B.compositeLiveIngestionOffsetToken=J.compositeLiveIngestionOffsetToken;J.compositeLiveStatusToken!==B.compositeLiveStatusToken&&(B.compositeLiveStatusToken=J.compositeLiveStatusToken);B.heartbeatLoggingToken=J.heartbeatLoggingToken;B.publish("dataupdated");f69(M,J,D,a,E)}},
onError:J=>{vz(M)&&IT(M,!0,`net-${J.status}`)},
onTimeout:()=>{vz(M)&&IT(M,!0,"timeout")}};
g.ZI(W,b.C()).then(J=>{J&&(V.AP=`Bearer ${J}`);g.Q7(M.Zs,"player/heartbeat",T,V)})},rKV=function(M){return(M=M.player.getProgressState(M.getPlayerType()).ingestionTime)&&isFinite(M)?`${Math.floor(M*1E3)}`:null},xxh=function(M){return(M=M.player.getCurrentTime(M.getPlayerType()))&&isFinite(M)?`${Math.floor(M*1E3)}`:null},f69=function(M,W,b,T,q){q===-1?(b=`decode ${g.NI(T,3)}`,IT(M,!1,b)):q===2?(tU(M),M.S=!0):(M.D=0,M.V.stop(),q===1?(M.S=!1,b&&b.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&M.player.Wg(!0),
q=`pe.${b?.errorCode};ps.${b?.status}`,M.player.J1("heartbeat.stop",2,M.bl(T),q),g.V9("heartbeatActionPlayerHalted",FX5(b)),W?.videoTransitionEndpoint&&b&&(W=W.videoTransitionEndpoint,(T=g.z(W,g.Jj))&&lc(M,T,b,{itct:W?.clickTrackingParams}))):(M.S=!0,T=0,M.A&&b&&(T=I6$(M,W,b),M.player.publish("livestatedata",b)),T?mv(M,T):mv(M)))},IT=function(M,W,b){if(!M.V.isActive()){M.V.stop();
M.D++;var T=W?"heartbeat.net":"heartbeat.servererror";{const X=M.getVideoData();if(X.P9||W&&!g.z7(M.getVideoData())&&!Z1(M)&&X.isLivePlayback)var q=!1;else M.heartbeatParams?.retries?q=M.heartbeatParams.retries:q=X.AF||5,q=M.D>=q}q?(g.V9("heartbeatActionPlayerHalted",W?{enforcedPolicyToHaltOnNetworkFailure:!0}:FX5()),(W=M.getVideoData())&&W.isLivePlayback?M.player.J1(T,1,"Video playback interrupted. Please try again.",b):M.player.J1(T,1,"Sorry, there was an error while licensing this video.",b)):
(mv(M,M.C.getValue()),g.og(M.C))}},FX5=function(M){const W={enforcedPolicyToHaltOnNetworkFailure:!1};
M&&(W.serializedServerContext=M.additionalLoggingData);return W},l6Q=function(M,W){return(M=Number(M?.pollDelayMs))?M:(W=Number(W?.pollDelayMs))?W:0},lc=function(M,W,b,T){const q=W&&W.videoId;
return q?(M.player.jA(q,{autonav:"1",...(T||{})},void 0,!0,!0,W,M.getVideoData().C()),M.zX("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",b),!0):!1},NJ={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
NJ={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sept Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sept Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["am","pm"],DATEFORMATS:["EEEE, d MMMM y",
"d MMMM y","d MMM y","dd/MM/y"],TIMEFORMATS:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:0,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:3};
var mxh=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],i7Q={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.L=C8.prototype;g.L.cG=NJ.FIRSTDAYOFWEEK;g.L.rX=NJ.FIRSTWEEKCUTOFFDAY;
g.L.clone=function(){const M=new C8(this.date);M.cG=this.cG;M.rX=this.rX;return M};
g.L.getFullYear=function(){return this.date.getFullYear()};
g.L.getYear=function(){return this.getFullYear()};
g.L.getMonth=function(){return this.date.getMonth()};
g.L.getDate=function(){return this.date.getDate()};
g.L.getTime=function(){return this.date.getTime()};
g.L.getDay=function(){return this.date.getDay()};
g.L.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.L.getUTCMonth=function(){return this.date.getUTCMonth()};
g.L.getUTCDate=function(){return this.date.getUTCDate()};
g.L.getUTCDay=function(){return this.date.getDay()};
g.L.getUTCHours=function(){return this.date.getUTCHours()};
g.L.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.L.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.L.set=function(M){this.date=new Date(M.getFullYear(),M.getMonth(),M.getDate())};
g.L.setFullYear=function(M){this.date.setFullYear(M)};
g.L.setYear=function(M){this.setFullYear(M)};
g.L.setMonth=function(M){this.date.setMonth(M)};
g.L.setDate=function(M){this.date.setDate(M)};
g.L.setTime=function(M){this.date.setTime(M)};
g.L.setUTCFullYear=function(M){this.date.setUTCFullYear(M)};
g.L.setUTCMonth=function(M){this.date.setUTCMonth(M)};
g.L.setUTCDate=function(M){this.date.setUTCDate(M)};
g.L.add=function(M){if(M.years||M.months){var W=this.getMonth()+M.months+M.years*12,b=this.getYear()+Math.floor(W/12);W%=12;W<0&&(W+=12);a:{switch(W){case 1:var T=b%4!=0||b%100==0&&b%400!=0?28:29;break a;case 5:case 8:case 10:case 3:T=30;break a}T=31}T=Math.min(T,this.getDate());this.setDate(1);this.setFullYear(b);this.setMonth(W);this.setDate(T)}M.days&&(b=this.getYear(),W=b>=0&&b<=99?-1900:0,M=new Date((new Date(b,this.getMonth(),this.getDate(),12)).getTime()+M.days*864E5),this.setDate(1),this.setFullYear(M.getFullYear()+
W),this.setMonth(M.getMonth()),this.setDate(M.getDate()),Uv(this,M.getDate()))};
g.L.equals=function(M){return!(!M||this.getYear()!=M.getYear()||this.getMonth()!=M.getMonth()||this.getDate()!=M.getDate())};
g.L.toString=function(){var M=this.getFullYear();const W=M<0?"-":M>=1E4?"+":"";return[W+yj(Math.abs(M),W?6:4),yj(this.getMonth()+1,2),yj(this.getDate(),2)].join("")+""};
g.L.valueOf=function(){return this.date.valueOf()};var JKh=new g.Y("addUpcomingEventReminderEndpoint");var Bb9=new g.Y("removeUpcomingEventReminderEndpoint");var hy7=class extends g.w{constructor(M){super({K:"div",U:[{K:"button",rK:["ytp-offline-slate-button","ytp-button"],U:[{K:"div",N:"ytp-offline-slate-button-icon",R0:"{{icon}}"},{K:"div",N:"ytp-offline-slate-button-text",R0:"{{text}}"}]}]});this.L=M;this.Z=this.toggleButtonRenderer=null;(this.V=this.hn("ytp-offline-slate-button"))&&this.J(this.V,"click",this.B);this.hide()}B(){if(this.toggleButtonRenderer){const M=this.toggleButtonRenderer;M.isToggled?a6r(this,M.toggledServiceEndpoint):a6r(this,M.defaultServiceEndpoint);
M.isToggled=!M.isToggled;kL(this)}}};var LXV=class extends g.w{constructor(M){super({K:"div",N:"ytp-offline-slate",U:[{K:"div",N:"ytp-offline-slate-background"},{K:"div",N:"ytp-offline-slate-bar",U:[{K:"span",N:"ytp-offline-slate-icon",U:[{K:"svg",Y:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},U:[{K:"path",Y:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{K:"circle",Y:{cx:"12",cy:"12",r:"3"}}]}]},{K:"span",N:"ytp-offline-slate-messages",U:[{K:"div",N:"ytp-offline-slate-main-text",Y:{"aria-label":"{{label}}"},R0:"{{mainText}}"},{K:"div",N:"ytp-offline-slate-subtitle-text",R0:"{{subtitleText}}"}]},{K:"span",N:"ytp-offline-slate-buttons"}]},{K:"button",rK:["ytp-offline-slate-close-button","ytp-button"],U:[g.DR()]},{K:"button",rK:["ytp-offline-slate-open-button","ytp-button"],U:[g.BF()]}]});this.api=M;this.Z=this.V=null;this.background=this.hn("ytp-offline-slate-background");
this.B=this.hn("ytp-offline-slate-bar");this.S=new g.d9(()=>{g.pY(this.B,"ytp-offline-slate-bar-fade")},15E3);
this.C=!1;this.A=new g.d9(()=>{g.pY(this.element,"ytp-offline-slate-collapsed")},15E3);
g.t(this,this.A);g.t(this,this.S);this.countdownTimer=new g.d9(this.W,1E3,this);this.J(M,"presentingplayerstatechange",this.D);this.J(M,"livestatedata",this.zv);this.J(this.hn("ytp-offline-slate-close-button"),"click",()=>{g.pY(this.element,"ytp-offline-slate-collapsed")});
this.J(this.hn("ytp-offline-slate-open-button"),"click",()=>{g.Mw(this.element,"ytp-offline-slate-collapsed")});
this.hide();M=this.getVideoData();M.getPlayerResponse()&&(M=M.getPlayerResponse().playabilityStatus)&&this.zv(M);M=this.api.getPresentingPlayerType()===8&&!this.getVideoData().TL;const W=this.api.getPresentingPlayerType()===8;g.H(this.element,"ytp-offline-slate-premiere-trailer",M);g.H(this.element,"ytp-offline-slate-hide-background",W)}getPlayerType(){if(this.api.getPresentingPlayerType()===8)return 1}getVideoData(){return this.api.getVideoData({playerType:this.getPlayerType()})}zv(M){var W=M?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate;
if(W){this.V=M;W=W.liveStreamOfflineSlateRenderer;W.canShowCountdown?this.W():K8(this,W);var b=M?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate?.liveStreamOfflineSlateRenderer?.thumbnail;if(b){let T=0,q=null;b=b.thumbnails;for(let X=0;X<b.length;X++)b[X].width>T&&(T=b[X].width||0,q=b[X].url);q&&(this.background.style.backgroundImage=`url(${q})`)}else this.background.style.backgroundImage="";W.actionButtons?(this.Z||(this.Z=new hy7(this.api),this.Z.cY(this.hn("ytp-offline-slate-buttons")),
g.t(this,this.Z)),VaI(this.Z,W.actionButtons&&W.actionButtons[0])):this.Z&&VaI(this.Z,null);this.V=M}else this.V=null;this.D()}D(M){if(this.api.getPresentingPlayerType()===8)var W=!0;else{var b=this.api.getPlayerStateObject(),T=this.getVideoData();W=T.isLivePlayback&&(b.isBuffering()||b.Z(2)||b.Z(64));var q=T.autonavState===2&&b.Z(2);b=b.isPlaying()&&!g.PM(T)&&!this.api.isAtLiveHead(void 0,!0);W=W&&!b&&!q}W&&this.V?this.Ta?M?.QN(2)&&!this.getVideoData().TL&&(g.Mw(this.element,"ytp-offline-slate-collapsed"),
this.A.stop(),g.Mw(this.B,"ytp-offline-slate-bar-fade"),this.S.start()):(this.show(),this.A.start(),this.api.publish("offlineslatestatechange"),this.C&&this.api.NC()):this.Ta&&(this.hide(),this.api.publish("offlineslatestatechange"))}W(){const M=this.V?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate?.liveStreamOfflineSlateRenderer;if(M){var W=Math.floor(g.Hy()/1E3),b=M.canShowCountdown&&Number(M.scheduledStartTime);!b||b<=W?(K8(this,M),this.countdownTimer.stop()):(K8(this,M,g.O3(b-W)),
this.countdownTimer.Wr())}}vY(){this.countdownTimer.dispose();this.countdownTimer=null;super.vY()}};var Z7p=class{constructor(M,W){var b=(0,g.u)();this.trigger=M;this.Z=W;this.B=b}V(M){return this.trigger&&M.trigger?this.trigger===M.trigger&&this.Z===M.Z:!1}isExpired(){return(0,g.u)()-this.B>6E4}toString(){return`${"heartbeat"}:${this.trigger}:${this.Z}`}};var H7h=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.FQ("heartbeat",class extends g.F2{constructor(M){super(M);this.W=!1;this.D=0;this.S=!1;this.V=new g.d9(()=>{KX$(this)},0);
this.Z=this.heartbeatParams=null;this.A=!1;this.C=new g.di(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.Zs=new g.GF(void 0);this.attestationResponse=Promise.resolve(void 0);this.X=Promise.resolve(void 0);this.utcOffsetMinutes=-(new C8).getTimezoneOffset();this.B=new g.Cq(this);g.t(this,this.V);g.t(this,this.B);CX9(this);taQ(this);this.B.J(M,"heartbeatparams",this.e0);this.B.J(M,"presentingplayerstatechange",this.gK);this.B.J(M,"videoplayerreset",this.O);this.B.J(M,g.kJ("heartbeat"),
this.onCueRangeEnter);this.A&&this.Z&&I6$(this,void 0,this.Z);const W=new g.Ap(L8(this,!0),0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),b=new g.Ap(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});M.QV([W,b]);Nb4(this)}vY(){tU(this);this.player.lN("heartbeat");super.vY()}onCueRangeEnter(){this.W=!0;mv(this,L8(this))}e0(M){this.heartbeatParams=M;mv(this,L8(this))}gK(M){if(this.player.getPresentingPlayerType()!==8&&this.Z?.status!=="UNPLAYABLE")if(M.state.Z(2)||
M.state.Z(64))tU(this),this.A&&(this.W=!0,mv(this,L8(this,!0)));else{const W=this.player.G().experiments.hT().Z.UY(g.u2y);(M.state.Z(1)||M.state.Z(8)||W&&M.state.Z(4))&&mv(this,L8(this))}}O(){this.player.getPresentingPlayerType()!==3&&mv(this,L8(this))}getPlayerType(){if(this.player.getPresentingPlayerType()===8)return 1}getVideoData(){return this.player.getVideoData({playerType:this.getPlayerType()})}Nm(M){switch(M){case 4:case 3:return!1}return!0}zX(M,W,b){M={trigger:M,reason:W};b&&(M.serializedServerContext=
b.additionalLoggingData);g.V9("heartbeatActionPlayerTransitioned",M)}bl(M){var W="LICENSE";const b=nqc(M);if(b)return b.reason||g.MA[W]||"";if(M=M.match(H7h))if(M=Number(M[1]))W=(W=i7Q[M.toString()])?W:"LICENSE";return g.MA[W]||""}KS(){return!!this.offlineSlate&&this.offlineSlate.Ta}});})(_yt_player);
